// Course spine: weeks, days, canonical agenda, outcomes, and the capstone arc.
// Day content lives in content/days/day-XX.js. The validator checks that every
// agenda topic below is covered by a bite in the matching day file.

export const course = {
  title: 'AI Engineer Pro',
  tagline: 'Twenty short days from using agents to engineering systems of them.',
  defaultStart: '2026-10-26',
  harnesses: ['Claude Code', 'Codex'],

  weeks: [
    {
      n: 1,
      name: 'Core',
      goal: 'Understand generative AI deeply enough to reason beyond current tools.',
      progression: ['models', 'context', 'knowledge', 'harnesses', 'workflows'],
      promise: 'Turn AI into a leverage layer you can reason about.',
    },
    {
      n: 2,
      name: 'Agents',
      goal: 'Design and build a specialized agent with tools, skills, and boundaries tailored to its job.',
      progression: ['primitives', 'building', 'capabilities', 'collaboration', 'reliability'],
      promise: 'Build a specialized agent you can extend, evaluate, and control.',
    },
    {
      n: 3,
      name: 'Product',
      goal: 'Direct AI toward meaningful system changes and verify what ships.',
      progression: ['product mechanics', 'intent', 'development', 'verification', 'learning'],
      promise: 'Deliver quality software at AI leverage.',
    },
    {
      n: 4,
      name: 'Takeoff',
      goal: 'Build autonomous systems that operate, recover, and improve over time.',
      progression: ['autonomy', 'portability', 'orchestration', 'automation', 'self-improvement'],
      promise: 'Give agents more autonomy without losing control.',
    },
  ],

  days: [
    {
      n: 1, week: 1, weekday: 'Mon', title: 'Mechanics Behind Generative AI',
      agenda: [
        { title: 'Introduction', topics: ['generative AI', 'harnesses', 'configuration', 'agentic tooling', 'custom tools'] },
        { title: 'Mechanics', topics: ['instructions', 'completion', 'tokenization', 'prediction', 'attention', 'instruction following'] },
        { title: 'Limitations', topics: ['illusions', 'confabulation', 'base knowledge', 'knowledge cutoff', 'context windows', 'output limits'] },
        { title: 'Providers', topics: ['models', 'capabilities', 'features', 'settings', 'pricing', 'specialization', 'model mixing'] },
        { title: 'Interactions', topics: ['text generation', 'structured outputs', 'function calling', 'native tools', 'external tools'] },
        { title: 'Steering', topics: ['generalization', 'associations', 'self-querying', 'latent space', 'J-space', 'reasoning'] },
      ],
    },
    {
      n: 2, week: 1, weekday: 'Tue', title: 'Steering Models Through Context',
      agenda: [
        { title: 'Settings', topics: ['profiles', 'projects', 'agents', 'permissions', 'history', 'connectors'] },
        { title: 'Context', topics: ['sessions', 'threads', 'metadata', 'environment', 'tools', 'skills', 'modes', 'compression'] },
        { title: 'Processing', topics: ['text', 'threads', 'context', 'multimodality', 'attachments', 'real-time interactions'] },
        { title: 'Skills', topics: ['structure', 'selection', 'scope', 'graphs', 'scripts', 'dynamic resources', 'generation'] },
        { title: 'Tools', topics: ['discovery', 'schemas', 'results', 'hints', 'recovery', 'code mode', 'Bash'] },
        { title: 'Subagents', topics: ['mechanics', 'settings', 'state', 'handoffs', 'shared context'] },
      ],
    },
    {
      n: 3, week: 1, weekday: 'Wed', title: 'Building Knowledge Systems',
      agenda: [
        { title: 'Files', topics: ['Markdown', 'HTML', 'artifacts', 'executables', 'logs'] },
        { title: 'Style Guide', topics: ['dynamic structures', 'extracting the essence', 'levels of depth', 'diff strategies'] },
        { title: 'Specifications', topics: ['structures', 'automatic synchronization', 'global specifications', 'maps', 'exploration', 'history'] },
        { title: 'Tasks', topics: ['source', 'scope', 'requirements', 'progress tracking', 'stage splitting', 'completion indicators'] },
        { title: 'Library', topics: ['personal resources', 'shared resources', 'internal configurations', 'custom generators'] },
        { title: 'Research', topics: ['discovery', 'autonomous research', 'context providers'] },
      ],
    },
    {
      n: 4, week: 1, weekday: 'Thu', title: 'Working with AI Harnesses',
      agenda: [
        { title: 'Harnesses', topics: ['overview', 'common features', 'personalization', 'harness-agnostic workflows'] },
        { title: 'Interfaces', topics: ['desktop', 'CLI', 'chat features', 'programmatic calls', 'custom scripts'] },
        { title: 'Settings', topics: ['providers', 'model routing', 'connectors', 'extensions', 'repositories', 'worktrees'] },
        { title: 'Workflows', topics: ['context loading', 'iteration', 'automatic feedback', 'verification', 'multi-threaded work'] },
        { title: 'Teamwork', topics: ['issue management', 'enriched reviews', 'layered diffs', 'multi-agent review'] },
        { title: 'Product', topics: ['dynamic dashboards', 'issue enrichment', 'automatic issue resolution', 'communication management'] },
      ],
    },
    {
      n: 5, week: 1, weekday: 'Fri', title: 'Building Workflows, Not Tool Stacks',
      agenda: [
        { title: 'Workflows', topics: ['executable Markdown', 'dynamic apps', 'deterministic tools', 'graphs'] },
        { title: 'Quality', topics: ['checklists', 'safeguards', 'review loops', 'performance markers'] },
        { title: 'User Experience', topics: ['synthetic scenarios', 'visual notes', 'recordings', 'deep behavioral analysis'] },
        { title: 'User Interfaces', topics: ['visual prototyping', 'design systems', 'augmented visual analysis'] },
        { title: 'Security', topics: ['critical loops', 'checklists', 'layered reviews', 'dependency reviews'] },
        { title: 'Business', topics: ['product analysis', 'insights', 'dynamic reports', 'roadmap inputs'] },
      ],
    },
    {
      n: 6, week: 2, weekday: 'Mon', title: 'Agentic Primitives',
      agenda: [
        { title: 'Agent Loop', topics: ['model calls', 'tool execution', 'results', 'state', 'stopping conditions', 'runtime responsibilities'] },
        { title: 'Instructions', topics: ['purpose', 'responsibilities', 'profiles', 'configuration', 'behavioral guidance', 'enforced boundaries'] },
        { title: 'Context and Memory', topics: ['messages', 'metadata', 'attachments', 'environmental awareness', 'persistence', 'retrieval', 'context injection', 'prompt caching'] },
        { title: 'Tools', topics: ['available actions', 'function calling', 'Bash', 'browser use', 'code execution', 'filesystems', 'permissions', 'sandboxing'] },
      ],
    },
    {
      n: 7, week: 2, weekday: 'Tue', title: 'Building an Agent',
      agenda: [
        { title: 'Framework', topics: ['agent configuration', 'runtimes', 'execution environments', 'packages', 'storage', 'data structures', 'reusable artifacts'] },
        { title: 'Models', topics: ['model selection', 'task-based routing', 'capability and cost tradeoffs', 'structured judgments', 'ordinary code versus model decisions'] },
        { title: 'Tool Design', topics: ['tools versus APIs', 'focused responsibilities', 'descriptions', 'schemas', 'validated inputs', 'useful results', 'actionable errors', 'structured responses'] },
        { title: 'Context and Memory', topics: ['context assembly', 'conversation history', 'working memory', 'persistent storage', 'retrieval', 'memory scope and lifecycle'] },
        { title: 'Workflows and Controls', topics: ['steps', 'branches', 'graphs', 'jobs', 'queues', 'state transitions', 'side effects', 'execution budgets', 'isolation', 'approval', 'pause and recovery'] },
      ],
    },
    {
      n: 8, week: 2, weekday: 'Wed', title: 'Agentic Capabilities',
      agenda: [
        { title: 'AGENTS.md', topics: ['standing instructions', 'explicit loading', 'instruction scope', 'shared conventions', 'reusable guidance'] },
        { title: 'MCP', topics: ['server and client mechanics', 'tools', 'resources', 'elicitation', 'discovery', 'configuration', 'CLI and API tradeoffs', 'integration security', 'hosting and maintenance'] },
        { title: 'Agent Skills', topics: ['specialized procedures', 'discovery', 'progressive loading', 'supporting references and scripts', 'tools paired with instructions', 'reusable capabilities'] },
        { title: 'Context Management', topics: ['selective retrieval', 'resource loading', 'context compaction', 'filesystem offloading', 'code mode', 'filtering tool results', 'execution and trust boundaries'] },
      ],
    },
    {
      n: 9, week: 2, weekday: 'Thu', title: 'Multi-Agent Collaboration',
      agenda: [
        { title: 'Subagents', topics: ['predefined and dynamic helpers', 'specialization', 'responsibilities', 'isolated contexts', 'shared resources', 'architectural patterns'] },
        { title: 'A2A', topics: ['collaboration between independent agents', 'protocol boundaries', 'messages', 'tasks', 'artifacts', 'interoperability'] },
        { title: 'Agent Card', topics: ['capabilities', 'connection details', 'supported interactions', 'accurate descriptions', 'authentication and authorization boundaries'] },
        { title: 'Discovery', topics: ['finding agents', 'inspecting cards', 'matching capabilities to tasks', 'selecting collaborators'] },
        { title: 'Delegation', topics: ['task scope', 'context assembly', 'handoff contracts', 'ownership', 'progress visibility', 'usable results', 'failure reporting'] },
        { title: 'Orchestration', topics: ['dependencies', 'parallel work', 'shared state', 'synchronization', 'worktrees', 'conflict resolution', 'merge points', 'background triggers and schedules', 'human-agent workflows'] },
      ],
    },
    {
      n: 10, week: 2, weekday: 'Fri', title: 'Agent Reliability',
      agenda: [
        { title: 'Guardrails', topics: ['domain rules', 'input and output checks', 'tool-level restrictions', 'permissions', 'approval boundaries', 'blocking', 'redaction', 'prompt-injection risks'] },
        { title: 'Evals', topics: ['datasets', 'task completion', 'tool use', 'boundary tests', 'deterministic checks', 'model-based scorers', 'human calibration', 'online and offline evaluation', 'versioning and regressions'] },
        { title: 'Observability', topics: ['traces', 'aggregate metrics', 'cost', 'latency', 'failures', 'provenance', 'execution records', 'debugging', 'recovery', 'feedback-driven improvements'] },
      ],
    },
    {
      n: 11, week: 3, weekday: 'Mon', title: 'Mechanics Behind Product Engineering',
      agenda: [
        { title: 'Shift', topics: ['outcome over output', 'product engineer vs. product manager', 'attention as the bottleneck'] },
        { title: 'Ownership', topics: ['scope', 'user impact', 'business value', 'technical consequences'] },
        { title: 'Judgment', topics: ['assumptions', 'tradeoffs', 'taste', 'edge cases', 'uncertainty', 'consequences'] },
        { title: 'Systems Thinking', topics: ['architecture', 'dependencies', 'operational impact', 'system diffs'] },
        { title: 'Leverage', topics: ['AI-assisted exploration', 'looped prototyping', 'generative exploration', 'synthetic inputs'] },
      ],
    },
    {
      n: 12, week: 3, weekday: 'Tue', title: 'Translating Intent into Agent Work',
      agenda: [
        { title: 'Intent', topics: ['definition of done', 'user impact', 'existing behavior', 'desired outcome'] },
        { title: 'Context', topics: ['product knowledge', 'market knowledge', 'codebase maps', 'constraints', 'conventions', 'prior decisions'] },
        { title: 'Requirements', topics: ['assumptions', 'ambiguities', 'contradictions', 'missing information', 'focused questions'] },
        { title: 'Specifications', topics: ['structured briefs', 'negative examples', 'acceptance criteria', 'boundaries'] },
        { title: 'Decomposition', topics: ['simplification', 'dependencies', 'checkpoints', 'rules', 'assignments', 'open-endedness'] },
        { title: 'Evaluation', topics: ['expectations', 'quality bars', 'evidence requirements', 'tests'] },
      ],
    },
    {
      n: 13, week: 3, weekday: 'Wed', title: 'AI-Native Product Development',
      agenda: [
        { title: 'Exploration', topics: ['synthetic user flows', 'interactive maps', 'historical changes', 'architecture visualizations'] },
        { title: 'Planning', topics: ['scope expansion and contraction', 'risk mapping', 'graphs', 'high-level implementation strategies'] },
        { title: 'Execution', topics: ['direct work', 'handoffs', 'parallel agents', 'merge points', 'delegated work'] },
        { title: 'Feedback', topics: ['system logs', 'visual feedback', 'human feedback', 'artifacts'] },
        { title: 'Engineering', topics: ['ownership', 'simplification', 'thinking in primitives', 'conventions', 'technical debt'] },
        { title: 'Delivery', topics: ['integration checks', 'release monitoring', 'unresolved risks'] },
      ],
    },
    {
      n: 14, week: 3, weekday: 'Thu', title: 'Verifying Product Outcomes',
      agenda: [
        { title: 'Acceptance', topics: ['definition of done', 'requirements coverage', 'observable behavior', 'completion evidence'] },
        { title: 'Review', topics: ['code', 'architecture', 'UX', 'accessibility', 'security', 'performance', 'maintainability'] },
        { title: 'Verification', topics: ['regression tests', 'browser tests', 'synthetic scenarios', 'agent reviewers', 'deterministic checks'] },
        { title: 'System Diff', line: 'changes to behavior, user experience, data, architecture, complexity, operations', topics: ['behavior', 'user experience', 'data', 'architecture', 'complexity', 'operations'] },
        { title: 'Quality Gates', topics: ['confidence thresholds', 'release blockers', 'known risks', 'rollback readiness', 'human approval'] },
      ],
    },
    {
      n: 15, week: 3, weekday: 'Fri', title: 'Products That Learn After Release',
      agenda: [
        { title: 'Signals', topics: ['analytics', 'logs', 'incidents', 'support feedback', 'customer language', 'observed behavior'] },
        { title: 'Observation', topics: ['intended vs. actual outcomes', 'friction', 'workarounds', 'regressions', 'unintended effects'] },
        { title: 'Synthesis', topics: ['signal clustering', 'contradiction detection', 'root-cause analysis', 'confidence', 'evidence'] },
        { title: 'Decisions', line: 'expand, revise, simplify, revert, investigate, or stop', topics: ['expand', 'revise', 'simplify', 'revert', 'investigate', 'stop'] },
        { title: 'Feedback Loops', line: 'updates to issues, specifications, evaluations, product memory, agent context', topics: ['issues', 'specifications', 'evaluations', 'product memory', 'agent context'] },
      ],
    },
    {
      n: 16, week: 4, weekday: 'Mon', title: 'Mechanics Behind Autonomous Systems',
      agenda: [
        { title: 'Autonomy', topics: ['supervision levels', 'bounded independence', 'proactive behavior', 'trust calibration'] },
        { title: 'Runtime', topics: ['events', 'triggers', 'jobs', 'queues', 'schedules', 'heartbeats', 'long-running loops'] },
        { title: 'State', topics: ['persistent sessions', 'checkpoints', 'resumability', 'shared state', 'continuity across runs'] },
        { title: 'Control', topics: ['permissions', 'budgets', 'approval gates', 'cancellation', 'escalation', 'human intervention'] },
        { title: 'Observation and Recovery', topics: ['progress', 'traces', 'costs', 'failures', 'retries', 'rollbacks', 'repairs'] },
      ],
    },
    {
      n: 17, week: 4, weekday: 'Tue', title: 'Building Portable Agent Control Planes',
      agenda: [
        { title: 'Configuration', topics: ['executable Markdown', 'profiles', 'skills', 'rules', 'hooks', 'tools', 'agent rosters'] },
        { title: 'Portability', line: 'durable workflow definitions with explicit adapters for different harnesses', topics: ['durable workflow definitions', 'explicit adapters', 'different harnesses'] },
        { title: 'Environment', topics: ['shims', 'policies', 'sandboxes', 'secrets', 'resources', 'safe defaults'] },
        { title: 'Knowledge Delivery', topics: ['contextual loading', 'routing', 'push-based injection', 'code maps', 'documentation'] },
        { title: 'Operations', topics: ['versioning', 'inspection', 'reuse', 'migration', 'rollback', 'Git-native recovery'] },
      ],
    },
    {
      n: 18, week: 4, weekday: 'Wed', title: 'Orchestrating Autonomous Agent Teams',
      agenda: [
        { title: 'Organization', line: 'planner, researcher, builder, reviewer, validator roles with bounded access', topics: ['planner', 'researcher', 'builder', 'reviewer', 'validator', 'bounded access'] },
        { title: 'Coordination', topics: ['shared goals', 'isolated contexts', 'task dependencies', 'bidirectional handoffs'] },
        { title: 'Parallelism', topics: ['worktrees', 'branches', 'sessions', 'tiled panes', 'queues', 'merge points'] },
        { title: 'Routing', line: 'matching work to agents, tools, and models based on capability, risk, cost, and speed', topics: ['capability', 'risk', 'cost', 'speed'] },
        { title: 'Supervision', topics: ['progress visibility', 'collision detection', 'intervention', 'escalation', 'final human control'] },
      ],
    },
    {
      n: 19, week: 4, weekday: 'Thu', title: 'Automating Work Beyond Code',
      agenda: [
        { title: 'Events', topics: ['repository changes', 'issues', 'messages', 'schedules', 'tool calls', 'failures', 'external signals'] },
        { title: 'Hooks', line: 'inspecting, redirecting, blocking, enriching, or continuing agent actions', topics: ['inspecting', 'redirecting', 'blocking', 'enriching', 'continuing'] },
        { title: 'Pipelines', topics: ['observe', 'classify', 'route', 'execute', 'verify', 'communicate'] },
        { title: 'Push Systems', line: 'delivering knowledge and instructions when needed instead of relying on agent discovery', topics: ['just-in-time knowledge', 'instruction delivery', 'discovery gaps'] },
        { title: 'Boundaries', topics: ['deduplication', 'backpressure', 'budgets', 'permissions', 'failure containment', 'human checkpoints'] },
      ],
    },
    {
      n: 20, week: 4, weekday: 'Fri', title: 'Building Self-Improving Engineering Systems',
      agenda: [
        { title: 'Feedback', topics: ['traces', 'failures', 'corrections', 'evaluations', 'review findings', 'human decisions'] },
        { title: 'Evaluation', topics: ['proof ladders', 'baselines', 'validators', 'regression checks', 'versioned results'] },
        { title: 'Distillation', line: 'turning successful runs into skills, rules, workflows, context, reusable agents', topics: ['skills', 'rules', 'workflows', 'context', 'reusable agents'] },
        { title: 'Optimization', line: 'refining profiles, routing, tools, environments, model selection based on observed outcomes', topics: ['profiles', 'routing', 'tools', 'environments', 'model selection'] },
        { title: 'Governance', line: 'proposing, testing, approving, versioning, rolling back system changes', topics: ['proposing', 'testing', 'approving', 'versioning', 'rolling back'] },
      ],
    },
  ],

  outcomes: [
    { n: 1, title: 'Use agents to complete individual tasks', scope: ['Code, tests, debugging, research', 'Direct prompting, synchronous work, manual verification'], days: [1, 2, 4, 5] },
    { n: 2, title: 'Understand and control how agents work', scope: ['Model mechanics, context, inference, reasoning, limitations', 'Agent loops, state, memory, tools, sandboxes, permissions'], days: [1, 2, 6, 7, 8] },
    { n: 3, title: 'Collaborate with agents to solve larger problems', scope: ['Exploration, planning, implementation, review', 'Context shaping, model steering, informed judgment'], days: [2, 3, 4, 11, 13] },
    { n: 4, title: 'Turn effective practices into repeatable systems', scope: ['Skills, tools, integrations, memory', 'Reusable workflows, shared knowledge, verification loops'], days: [3, 5, 8, 17] },
    { n: 5, title: 'Own product outcomes, not just implementation', scope: ['Frame problems, question requirements, understand business needs', 'Balance user value, quality, scope, risk, and engineering effort'], days: [11, 12, 15] },
    { n: 6, title: 'Delegate complete outcomes with confidence', scope: ['Features and end-to-end product workflows', 'Clear intent, constraints, evaluations, quality gates, accountability'], days: [10, 12, 13, 14] },
    { n: 7, title: 'Coordinate specialized agents as an engineering team', scope: ['Parallel execution, shared context, clear responsibilities', 'Handoffs, merge points, observability, conflict resolution'], days: [9, 13, 18] },
    { n: 8, title: 'Build systems that work and improve without constant supervision', scope: ['Remote, proactive, ambient, and self-improving agents', 'Feedback loops, trust levels, monitoring, recovery, escalation'], days: [16, 19, 20] },
    { n: 9, title: 'Become an AI-first developer', scope: ['Combine human creativity, product judgment, and engineered AI leverage', 'Define ambitious problems, invent new ways of working, and own what ships'], days: [5, 10, 15, 20] },
  ],

  levels: ['Not yet', 'Aware', 'Practicing', 'Confident', 'Can teach it'],

  capstone: {
    name: 'Agent Forge',
    repo: 'agent-forge',
    pitch:
      'One TypeScript repository that grows every day. You build Triage, a specialized agent that turns messy product feedback into deduplicated, enriched, well-formed GitHub issues and weekly insight reports. Around it you build the knowledge system, evals, review UI, and automation that let it run and improve with less supervision.',
    why: [
      'Every course topic has a natural home: triage needs tools, memory, structured outputs, evals, approvals, schedules, and feedback loops.',
      'Labels make evaluation honest. You can score Triage against a golden set instead of trusting vibes.',
      'It is a real workflow for a product-minded engineer. Issue enrichment, clustering, and insight reports are daily PM and architect work.',
      'Claude Code and Codex both work on it from one shared AGENTS.md, so the dual-harness setup is exercised every day.',
    ],
    stack: [
      'Node 22+ and TypeScript (ESM), run with tsx',
      'Claude Code and Codex CLI, configured from one AGENTS.md',
      'Anthropic TypeScript SDK (Day 6) and Claude Agent SDK (Day 7 onward)',
      'Zod for schemas, Vitest for tests, Playwright for browser checks',
      'React and Vite for the Inbox review UI (Week 3)',
      'GitHub Actions for CI, schedules, and event pipelines (Weeks 1 and 4)',
    ],
    setup: [
      'Node 22 or newer (`node -v`)',
      'Claude Code installed and logged in (`claude --version`)',
      'Codex CLI installed and logged in (`codex --version`)',
      'GitHub CLI authenticated (`gh auth status`)',
      'An Anthropic API key with a monthly spend limit set in the Console, needed from Day 6',
      'A new empty GitHub repository named `agent-forge`',
    ],
    // Canonical repo map. Every build task uses these paths so the capstone stays coherent across days.
    layout: [
      'agent-forge/',
      '  AGENTS.md                 shared rules for every harness (Day 2)',
      '  CLAUDE.md                 @AGENTS.md plus Claude-only notes (Day 2)',
      '  .claude/                  settings.json, agents/, skills/, hooks (Days 2, 5, 17)',
      '  .agents/skills/           shared Agent Skills, linked into each harness (Days 2, 8)',
      '  .codex/                   project Codex config where supported (Day 2)',
      '  docs/                     style-guide.md, map.md, specs/, decisions/, product/, system-diffs/ (Days 3, 11 to 14)',
      '  tasks/                    _template.md, one file per task, progress.md (Day 3)',
      '  library/prompts/          reusable prompts (Day 3)',
      '  research/                 research briefs with sources (Day 3)',
      '  lab/                      model experiments (Day 1)',
      '  scripts/                  ask.ts, gen-feedback.ts, traces.ts, sync-control.ts, improve.ts',
      '  data/inbox/               feedback items as JSONL (Day 5 onward)',
      '  src/schema.ts             Zod FeedbackItem and TriageResult (Day 4)',
      '  src/loop.ts               raw agent loop on the Anthropic SDK (Day 6)',
      '  src/tools/                tool implementations (Days 6 to 8)',
      '  src/agent.ts              Triage on the Claude Agent SDK (Day 7)',
      '  src/mcp/server.ts         MCP server exposing triage tools (Day 8)',
      '  src/crew/                 specialists and orchestrator (Day 9)',
      '  src/guardrails.ts         input, tool, and output checks (Day 10)',
      '  memory/triage-notes.md    persistent learnings (Day 7)',
      '  .well-known/agent-card.json  A2A Agent Card (Day 9)',
      '  evals/                    golden.jsonl, run.ts, judges/, results/ (Day 10)',
      '  traces/                   JSONL run traces (Day 10)',
      '  apps/inbox/               React and Vite review UI (Days 11 to 15)',
      '  tests/                    Vitest unit tests, e2e/ Playwright specs (Days 4, 14)',
      '  state/                    checkpoints for unattended runs (Day 16)',
      '  control/                  single-source control plane (Day 17)',
      '  reports/                  insight and improvement reports (Days 15, 20)',
      '  .github/workflows/        ci.yml, triage-schedule.yml, triage-issues.yml (Days 5, 14, 16, 19)',
    ],
    conventions: [
      'Scripts in package.json: `typecheck`, `test`, `loop`, `triage`, `eval`, `traces`, `gen:feedback`, `mcp`, `control:sync`, `improve`.',
      'Categories: `bug`, `feature_request`, `question`, `praise`, `noise`. Severities: `critical`, `high`, `medium`, `low`. Confidence: `low`, `medium`, `high`.',
      'A TriageResult holds `id`, `category`, `severity`, `area`, `duplicateOf`, `summary`, `suggestedTitle`, `labels`, `confidence`, `needsHuman`, and `rationale`.',
      'Model IDs come from env vars with defaults: `FORGE_MODEL_MAIN` (`claude-opus-5`) and `FORGE_MODEL_FAST` (`claude-haiku-4-5`, or `claude-sonnet-5` once Haiku 4.5 retires).',
      'Tool names use snake_case verbs: `list_feedback`, `get_feedback`, `search_issues`, `save_triage`, `draft_issue`, `create_issue` (approval-gated).',
      'Data files: feedback in `data/inbox/*.jsonl`, triage results in `data/triage/results.jsonl`, human decisions in `data/decisions.jsonl`, traces in `traces/*.jsonl`.',
      'The Inbox is `apps/inbox` (React and Vite) plus `apps/inbox/server.ts`, a small Node API that reads and writes the `data/` files.',
    ],
    architecture: [
      'flowchart TD',
      '  IN["Inputs<br/>feedback files, synthetic data, GitHub issues"]',
      '  MC["MCP server<br/>triage tools"]',
      '  TR["Triage agent<br/>Claude Agent SDK"]',
      '  UI["Inbox UI<br/>approve, edit, reject"]',
      '  GH["GitHub<br/>enriched issues"]',
      '  EV["Evals and traces"]',
      '  CP["Control plane<br/>AGENTS.md, skills, hooks, roster"]',
      '  H["Claude Code and Codex"]',
      '  IN --> TR',
      '  MC -.-> TR',
      '  TR -->|"proposals"| UI',
      '  UI -->|"approved only"| GH',
      '  UI -->|"decisions"| EV',
      '  EV -->|"improvements"| CP',
      '  CP -.->|"configures"| TR',
      '  CP -.->|"configures"| H',
      '  H -->|"build and review"| TR',
    ],
    milestones: [
      { day: 1, title: 'Open the forge and run a model lab', deliverable: 'Create the agent-forge repo (TypeScript, Node 22) and push it. Run four experiments headless in both Claude Code and Codex: letter counting, sampling variance, knowledge-cutoff probing, and JSON-schema structured output. Record results in lab/01-model-lab.md.', minimum: 'Repo pushed with two experiments logged.' },
      { day: 2, title: 'Wire both harnesses to one source of truth', deliverable: 'AGENTS.md holds shared rules. CLAUDE.md imports it with @AGENTS.md and adds Claude-only notes. Add .claude/settings.json permissions, a Codex profile (approval and sandbox), one shared skill (explain-diff), and one Claude subagent (researcher). Verify both harnesses recite the same rules.', minimum: 'AGENTS.md plus CLAUDE.md import, verified in both harnesses.' },
      { day: 3, title: 'Build the knowledge system', deliverable: 'docs/ with an agent style guide, specs/triage.md, and map.md. tasks/ with a task template, three task files, and progress.md. library/ with reusable prompts. research/ with one autonomous research brief on feedback triage practice, with sources.', minimum: 'Triage spec, task template, and one task file.' },
      { day: 4, title: 'Run harness workflows and cross-review', deliverable: 'A scripts/ask.ts wrapper that runs one prompt headless through claude -p and codex exec. A git worktree for parallel work, GitHub issue templates, and a cross-review loop: one harness implements the Zod feedback schema with tests, the other reviews the diff, then an agent opens the PR.', minimum: 'One cross-reviewed PR.' },
      { day: 5, title: 'Ship through an executable workflow', deliverable: 'A shared ship-change skill (context, plan, implement, verify, review, PR), quality and security checklists, a Claude Code PostToolUse hook that runs typecheck and lint, a GitHub Actions check that enforces the same for Codex work, and a dependency review step. Ship the synthetic feedback generator through it.', minimum: 'Workflow skill, one hook, and one CI check.' },
      { day: 6, title: 'Write the raw agent loop', deliverable: 'src/loop.ts on the Anthropic TypeScript SDK: a messages loop with list_feedback and save_triage tools, stop conditions (end_turn, max turns, token budget), and a transcript log. Run it on five sample items.', minimum: 'A one-tool loop that terminates correctly.' },
      { day: 7, title: 'Rebuild Triage on the Claude Agent SDK', deliverable: 'In-process tools via createSdkMcpServer, a focused system prompt, Zod-typed structured output, model routing (small model classifies, larger model writes), turn and budget limits, a persistent memory file, and a cost report per run.', minimum: 'Ten items triaged into schema-valid JSON with cost printed.' },
      { day: 8, title: 'Package capabilities', deliverable: 'An MCP server exposing triage tools, registered in Claude Code and Codex. A triage-rubric Agent Skill with references and a validation script. Context hygiene: trimmed tool results and large outputs offloaded to files.', minimum: 'MCP server with two tools callable from one harness.' },
      { day: 9, title: 'Assemble the crew', deliverable: 'Specialist subagents (duplicate finder, classifier, issue writer) with typed handoff contracts, an orchestrator that runs batches in parallel, and an A2A Agent Card at .well-known/agent-card.json. Build two specialists in parallel worktrees, one per harness, then merge.', minimum: 'Two specialists, one contract, and the agent card.' },
      { day: 10, title: 'Make Triage reliable', deliverable: 'Guardrails (feedback treated as untrusted data, tool allowlist, approval gate before creating issues, PII redaction), evals (30 labeled items, deterministic checks, an LLM judge calibrated against your labels, a saved baseline), and JSONL traces with tokens, cost, and latency plus a summary command.', minimum: 'A 15-item eval with a saved baseline and traces.' },
      { day: 11, title: 'Frame the Inbox product', deliverable: 'A one-page brief for the Forge Inbox, a web UI to review Triage proposals: outcome, user, success metric, assumptions, tradeoffs, non-goals, and expected system diff. Then three throwaway prototypes via looped prototyping across both harnesses. Pick one and record why.', minimum: 'The brief and one prototype.' },
      { day: 12, title: 'Spec the work for agents', deliverable: 'docs/specs/inbox-v1.md with Gherkin acceptance criteria, negative examples, and boundaries. An agent interrogates the spec for ambiguities and contradictions and you answer. Decompose into task files with dependencies, checkpoints, and a harness assignment.', minimum: 'A spec with five acceptance criteria and a task list.' },
      { day: 13, title: 'Build the Inbox at leverage', deliverable: 'Inbox v1 built by parallel agents (Claude Code on UI, Codex on API and data) in worktrees with planned merge points, Playwright screenshots as a visual feedback loop, and a generated architecture diagram.', minimum: 'One vertical slice: list proposals and approve one.' },
      { day: 14, title: 'Prove it works', deliverable: 'Playwright tests mapped to each acceptance criterion, agent reviewers (security, accessibility, performance) as subagents or skills, a system diff document, and a CI quality gate (typecheck, tests, evals) required before merge.', minimum: 'Three acceptance tests and a system diff.' },
      { day: 15, title: 'Learn after release', deliverable: 'Instrument approve, edit, and reject events. Simulate a week of usage with synthetic users, run a synthesis agent (clusters, contradictions, root causes), write a decision memo, and feed learnings into the spec, evals, and agent memory.', minimum: 'Events, one synthesis report, and one new eval case.' },
      { day: 16, title: 'Let it run on its own', deliverable: 'Supervision levels for Triage (L0 to L4), a scheduled run (GitHub Actions cron or local cron), checkpoint and resume, budgets with a kill switch, and an escalation path.', minimum: 'A scheduled run with a budget stop and resume from checkpoint.' },
      { day: 17, title: 'Consolidate one control plane', deliverable: 'control/ as the single source (rules, skills, agent roster, hooks, policies) with a sync script that generates AGENTS.md, CLAUDE.md, .claude/, and Codex config. Environment policy (sandbox, secrets, safe defaults) and Git-native versioning with a rollback drill.', minimum: 'Sync generates both harness instruction files from one source.' },
      { day: 18, title: 'Run an agent team', deliverable: 'Planner, researcher, builder, reviewer, and validator roles with bounded tools, a routing table (capability, risk, cost, speed), parallel builders across Claude Code and Codex in worktrees, a status board, and file-claim collision detection. Ship the cluster view end to end.', minimum: 'Planner, two builders, and a reviewer on one small feature.' },
      { day: 19, title: 'Automate beyond code', deliverable: 'An event pipeline: GitHub issues.opened, then classify, route, label or comment, verify, and notify with a digest. Hooks that enrich or block, push-based knowledge injection at SessionStart, and boundaries (dedup, backpressure, budgets).', minimum: 'A GitHub Action that auto-triages new issues with a dedup check.' },
      { day: 20, title: 'Close the loop', deliverable: 'forge improve harvests traces and corrections, proposes rubric, skill, or prompt changes, runs a proof ladder (checks, golden set, shadow run), and opens a PR with eval deltas for your approval. Tag the version, practice a rollback, then map your evidence to the nine outcomes.', minimum: 'One proposal evaluated against the baseline with a written decision.' },
    ],
  },
}

export const dayFile = (n) => `day-${String(n).padStart(2, '0')}`
export const getDay = (n) => course.days.find((d) => d.n === n)
export const getWeek = (n) => course.weeks.find((w) => w.n === n)
