export default {
  day: 12,
  hook: "An agent builds the spec you wrote, not the one you meant. Rework, scope creep, and confident wrong answers all start in the gap between the two.",
  anchor: "You already write PRDs, user stories, and acceptance criteria that engineers interpret with shared context and hallway questions.",
  plusOne: "Today you write for a reader with no shared context and no hallway: explicit done, negative examples, boundaries, and tasks sized for agents.",
  tldr: [
    "Define done as observable behavior plus named evidence, and capture existing behavior first so regressions show up.",
    "Have both harnesses interrogate the spec for assumptions, ambiguities, and contradictions. Answer blocking questions before anyone builds.",
    "Decompose by context, not by role: few self-contained tasks, explicit dependencies, a checkpoint after each, one owner per file.",
  ],
  outcomes: [
    "Write Gherkin acceptance criteria with negative examples and boundaries an agent can verify",
    "Run a spec interrogation and resolve each gap as an answer, assumption, or question",
    "Decompose a feature into agent tasks with dependencies, checkpoints, and harness assignments",
  ],
  minutes: { learn: 22, practice: 60 },
  map: {
    title: "From intent to agent-ready tasks",
    mermaid: [
      "flowchart LR",
      '  B["Brief<br/>outcome, non-goals"] --> C["Context pack<br/>schema, map, decisions"]',
      '  C --> S["Spec<br/>criteria, negatives, boundaries"]',
      '  S --> I["Interrogation<br/>both harnesses"]',
      '  I -->|"answers and defaults"| S',
      '  S --> T["Task graph<br/>dependencies, checkpoints"]',
      '  T --> E["Evidence per task<br/>tests, screenshots, reports"]',
    ],
    caption: "The loop between spec and interrogation is the cheapest place to fix a misunderstanding. Once tasks start, every fix costs one rework cycle per agent.",
  },
  sections: [
    {
      id: "intent",
      title: "Intent",
      lead: "State the change as behavior: where users are today, where they should end up, and how done is checked.",
      bites: [
        ["Definition of done", "Done is a list of observable checks, each with the evidence that proves it. Anthropic's long-running harness keeps a JSON feature list where every item starts as `\"passes\": false` and flips only after end-to-end verification. 'Tests pass' is not done, because agents can weaken tests."],
        ["User impact", "Restate the brief's outcome as behavior the agent can reason about: a reviewer decides each proposal without opening raw files. When the agent meets a tradeoff you did not anticipate, this line is what it optimizes, so make it specific."],
        ["Existing behavior", "Capture what happens today before changing it, with characterization tests, recorded flows, or a plain description. Today, proposals sit in `data/triage/results.jsonl` and decisions are hand edits. Without a baseline, a regression looks like a feature."],
        ["Desired outcome", "Describe the end state, not the path. Anthropic's eval guidance is to grade what the agent produced, not the path it took. Prescribed steps lock in your first idea and block a better one the agent might have found."],
      ],
      visual: {
        md: [
          "```json",
          "{ \"id\": \"AC-2\", \"feature\": \"Approve a pending proposal\",",
          "  \"user_impact\": \"reviewer decides without opening raw files\",",
          "  \"existing_behavior\": \"decisions are hand edits to JSONL\",",
          "  \"done_when\": [\"status shows approved\", \"one decision line appended\", \"a second approve returns 409\"],",
          "  \"evidence\": [\"test AC-2 in tests/e2e/inbox.spec.ts\", \"screenshot of the approved card\"],",
          "  \"passes\": false }",
          "```",
        ],
        caption: "One criterion as state an agent can update. It may flip `passes` only after the evidence exists, and it may never edit the test to get there.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "The agent that grades itself",
          body: "Anthropic's harness prompt says it is unacceptable to remove or edit tests, because agents under pressure do both. Put the acceptance tests in a task separate from the implementation, so the agent writing the code never edits its own grader.",
        },
      ],
    },
    {
      id: "context",
      title: "Context",
      lead: "Agents know only what the repo says. A context pack says it once, in files both harnesses can read.",
      bites: [
        ["Product knowledge", "The brief, the user, the outcome, and the non-goals, linked from the spec rather than pasted into it. The Inbox spec points at `docs/product/inbox-brief.md`. Pasted copies drift apart, and then the agent has to guess which one is current."],
        ["Market knowledge", "How others solved the problem, and what you copy or skip. LangChain's Agent Inbox offered accept, edit, respond, and ignore per interrupt before it was archived in Sep 2026. Borrow the verbs you need and write down why you dropped the rest."],
        ["Codebase maps", "A short map beats a long dump. `docs/map.md` names modules, entry points, and data files. Claude Code explores just-in-time with search and file reads, and Codex starts from its AGENTS.md chain, so both reward maps that point rather than describe."],
        ["Constraints", "Hard limits the agent cannot infer: Node 22, no new dependencies without asking, the API binds to 127.0.0.1, no GitHub token in the Inbox process. Give each one its reason, so the agent can apply it to cases you never listed."],
        ["Conventions", "Naming, layout, error shapes, and test style already live in AGENTS.md. Reference them instead of restating them. Agents imitate the code around them, so one inconsistent example file teaches more than a paragraph of rules."],
        ["Prior decisions", "ADRs in `docs/decisions/` record why, which code cannot. 'Triage output is append-only evidence' is a prior decision the Inbox must honor. Leave it out and an agent will helpfully add an endpoint that edits results in place."],
      ],
      visual: {
        table: {
          head: ["Context item", "File", "How it reaches the agent"],
          rows: [
            ["Conventions", "`AGENTS.md`", "Loaded every session by both harnesses"],
            ["Product knowledge", "`docs/product/inbox-brief.md`", "Linked from the spec, read on demand"],
            ["Codebase map", "`docs/map.md`", "Linked, read on demand"],
            ["Data contracts", "`src/schema.ts`", "Read on demand"],
            ["Prior decisions", "`docs/decisions/`", "Linked by id from the spec"],
            ["Market notes", "`research/` from Day 3", "Linked, optional"],
          ],
        },
        caption: "Only AGENTS.md is always loaded. Everything else is a pointer, which keeps context lean and keeps each fact in one place.",
      },
      callouts: [
        {
          type: "pro",
          title: "See what each harness actually loaded",
          body: "In Claude Code, `/context` shows what the session carries. In Codex, `codex debug prompt-input` prints exactly what the model receives, including the AGENTS.md chain. Run both once before the spec task and cut anything neither needs.",
        },
      ],
      deeper: {
        title: "One spec, two loaders",
        body: [
          "The two harnesses assemble context differently, and a spec has to survive both.",
          "- Claude Code loads CLAUDE.md every session (keep it under about 200 lines), loads path-scoped `.claude/rules/*.md` when a matching file is read, expands `@path` imports, and reads AGENTS.md natively when no CLAUDE.md exists.",
          "- Codex concatenates AGENTS.md files from the repo root down to the working directory, caps them at 32 KiB by default, never reads folders below the working directory, and treats `@path` as plain text. An untrusted project contributes no project AGENTS.md at all.",
          "Implications for the Inbox: keep the spec as a file that every task prompt names by path, never reach it through an import, and start Codex from the repo root. If you later add `apps/inbox/AGENTS.md`, Codex reads it only when you run it with `-C apps/inbox`.",
        ],
      },
    },
    {
      id: "requirements",
      title: "Requirements",
      lead: "Most agent failures start as specification problems. Interrogate the spec before anything is built from it.",
      bites: [
        ["Assumptions", "Carry the ledger over from the brief and add what the spec takes for granted: one reviewer, immutable proposals, a local server. An assumption on paper can be checked. One left implicit gets decided silently by whichever agent reaches it first."],
        ["Ambiguities", "Words two competent readers would build differently: 'fast', 'recent', 'edit a proposal'. Replace each with a number or an example. 'Fast' becomes 'the list renders 200 proposals in under a second on a laptop', which an agent can test."],
        ["Contradictions", "Two sources that cannot both be true: the brief forbids GitHub writes while a task says approval opens an issue. Claude Code's docs warn that with conflicting rules the model may pick one arbitrarily. Resolve contradictions before building, never during."],
        ["Missing information", "What the spec never mentions: a malformed line in results.jsonl, a maximum reason length, the timezone of timestamps. The MAST study attributes about 42% of multi-agent failures to specification and system design, and gaps like these are the common case."],
        ["Focused questions", "Ask three to five blocking questions up front, because routines, workflows, and `codex exec` cannot ask mid-run. Convert every non-blocking question into an assumption with a stated default, so work continues and the choice stays visible."],
      ],
      visual: {
        md: [
          "```text",
          "AMBIGUOUS    \"edit a proposal\"       -> which fields? default: category, severity, area, labels, title, summary",
          "MISSING      malformed JSONL line    -> default: skip it, count it, show the count (new AC-9)",
          "CONTRADICTS  brief: no GitHub writes vs T4: \"approve opens an issue\" -> blocking, ask",
          "ASSUMED      single reviewer         -> keep A1 open, add 409 on a second decision (AC-3)",
          "QUESTION     Q1 can a rejected proposal be reopened? -> blocks the status model",
          "```",
        ],
        caption: "Every finding ends as an answer, an assumption with a default, or a blocking question. Nothing stays a vague worry.",
      },
      callouts: [
        {
          type: "pro",
          title: "Interrogate with both harnesses",
          body: "Run the same interrogation prompt in Claude Code and in `codex exec --sandbox read-only`. Different models miss different gaps. Merge the two lists, answer the union, and note which harness caught the finding you would have missed.",
        },
      ],
      deeper: {
        title: "EARS or Gherkin",
        body: [
          "Two structured syntaxes dominate agent-facing requirements.",
          "- EARS (Easy Approach to Requirements Syntax) uses templates such as 'WHEN a trigger occurs, THE SYSTEM SHALL respond', plus While, If-then, and Where forms. Kiro writes its `requirements.md` in EARS. It is compact and good at exposing a missing trigger or condition.",
          "- Gherkin uses Given, When, Then scenarios with concrete data. It reads as prose, runs under Cucumber, and maps one scenario onto one test.",
          "This course uses Gherkin because Day 14 maps every scenario to a Playwright test and checks coverage by tag. EARS is still a useful lens during interrogation: rewrite any criterion that lacks a trigger ('WHEN') or a condition ('IF'), and the missing piece usually becomes obvious.",
        ],
      },
    },
    {
      id: "specifications",
      title: "Specifications",
      lead: "A structured brief with examples of what must not happen gives an agent both a target and a fence.",
      bites: [
        ["Structured briefs", "Fixed headings an agent can find: intent, context, behavior, acceptance criteria, negative examples, boundaries, questions. Spec Kit, Kiro, and plain Markdown converge on this shape. Stable headings let agents search the spec and let you diff it between versions."],
        ["Negative examples", "State what must not happen, with a concrete case: approving twice must not append a second decision, and the Inbox must not call api.github.com. One-sided criteria create one-sided optimization, because an agent will satisfy the happy path by any available means."],
        ["Acceptance criteria", "Given, When, Then scenarios with stable tags such as `@AC-3`. Gherkin reads as prose for you and maps one to one onto tests for the agent. Day 13's reports and Day 14's coverage check key on those tags, so add new ids and never renumber."],
        ["Boundaries", "Paths a task may touch, tools it may use, and actions that need your approval: only `apps/inbox/**`, never `src/` or another task's tests, ask before any dependency. Boundaries turn scope from a hope into something a reviewer can check against the diff."],
        ["Spec levels", "Birgitta Böckeler describes three levels: spec-first (written, then abandoned), spec-anchored (maintained with the code), and spec-as-source (humans edit only the spec). This course is spec-anchored: the spec changes first, and Day 15 feeds learnings back into it."],
      ],
      visual: {
        md: [
          "```gherkin",
          "@AC-3 @negative",
          "Scenario: A proposal is decided at most once",
          "  Given proposal \"fb_102\" is approved",
          "  When another approve, edit, or reject arrives for \"fb_102\"",
          "  Then the API responds with status 409",
          "  And \"data/decisions.jsonl\" still holds exactly one decision for \"fb_102\"",
          "```",
        ],
        caption: "A negative example written as a scenario. It is the test that stops a helpful agent from making approval non-idempotent.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Specs do not enforce themselves",
          body: "A May 2026 Spec Kit issue found that its implement step never loaded the project constitution. Name the spec path in every task prompt, and require the agent to quote the AC ids it is implementing before it writes code.",
        },
      ],
      deeper: {
        title: "The case against spec-driven development",
        body: [
          "The critique is serious. Marmelab's 'Waterfall Strikes Back' and Böckeler's review describe review burden, stale specs, and overkill: one Thoughtworks engineer watched Kiro turn a small bug into four user stories with sixteen acceptance criteria. Kiro later added a lighter Quick Spec mode, and Spec Kit added lighter paths for bugs.",
          "The rebuttal, from Marc Brooker among others, is that specs iterate in short loops like code and need not be written up front in full.",
          "The practical position is to size the spec to the risk. A bug fix gets three lines: the failing behavior, the expected behavior, and a boundary. Inbox v1 gets a page, because two agents will build against it in parallel and a misread costs a day. Anthropic's planner guidance points the same way: stay at product context and high-level design, since wrong low-level detail cascades into the implementation.",
        ],
      },
    },
    {
      id: "decomposition",
      title: "Decomposition",
      lead: "Split work so each agent holds all the context its task needs, and nothing it does not.",
      bites: [
        ["Simplification", "Cut before you split. Anthropic noted that every harness component encodes an assumption about what the model cannot do alone, and dropped sprint decomposition when models improved. If one session can build a slice, fewer tasks means fewer handoffs, where information leaks away."],
        ["Dependencies", "Draw the graph, then start with the node everything waits on. For the Inbox, the shared contract in `apps/inbox/shared/contract.ts` blocks both the API and the UI, so it merges first. A blocked task cannot start, and that is the point."],
        ["Checkpoints", "End each task with a checkpoint: the command that must pass, a commit, and a line in `tasks/progress.md`. Anthropic's long-running rule is one feature per session, then commit. Checkpoints keep a failed task cheap to redo."],
        ["Rules", "Per-task rules: files it owns, files it must not touch, and when to stop and report. Claude Code's agent-teams docs warn that two teammates editing one file leads to overwrites. Disjoint file ownership is the cheapest merge-conflict prevention you have."],
        ["Assignments", "Assign by fit and write the harness into the task file. The Inbox plan gives the UI to Claude Code, where you iterate with screenshots and `/rewind`, and the API to Codex as a test-driven, headless-friendly task. Work spanning both stays with you."],
        ["Open-endedness", "Fixed, predictable subtasks suit a static task graph or a prompt chain. Unpredictable ones suit an orchestrator that plans as it goes. The Inbox tasks are predictable, so a static graph fits. A research question would not."],
      ],
      visual: {
        mermaid: [
          "flowchart LR",
          '  T1["T1 shared contract<br/>you, merge point 1"] --> T2["T2 API and data<br/>Codex"]',
          '  T1 --> T3["T3 list and detail UI<br/>Claude Code"]',
          '  T3 --> T4["T4 decision UI<br/>Claude Code"]',
          '  T2 --> T5["T5 integration<br/>you, merge point 2"]',
          '  T4 --> T5',
          '  T5 --> T6["T6 acceptance tests<br/>Day 14"]',
        ],
        caption: "Two merge points bracket the parallel work. T2 and T3 can run at the same time because they share nothing but the contract.",
      },
      callouts: [
        {
          type: "example",
          title: "The header of a task file",
          body: [
            "```text",
            "T2 Inbox API and data layer",
            "Harness: Codex, own worktree     Blocked by: T1     Blocks: T5",
            "Owns: apps/inbox/server.ts, apps/inbox/lib/**, tests/inbox-api.test.ts",
            "Must not touch: apps/inbox/shared/**, apps/inbox/src/**, tests/e2e/**",
            "Checkpoint: typecheck and API tests green, you commit, progress.md updated",
            "```",
          ],
        },
      ],
    },
    {
      id: "evaluation",
      title: "Evaluation",
      lead: "Decide how you will judge the work before it exists, or the agent's summary becomes the judgment.",
      bites: [
        ["Expectations", "Say what a good result looks like and what the agent must report: criteria met, criteria skipped, commands run, files changed, assumptions made. A required report format turns a success claim into a checklist you can verify in two minutes."],
        ["Quality bars", "Thresholds written before the work: typecheck and lint clean, every AC backed by a passing test, no dependency without approval, a bundle size limit. A bar written after you see the output bends to fit the output."],
        ["Evidence requirements", "Name the artifact that proves each claim: test output, a screenshot, a log line, a diff stat. Cursor attaches videos and screenshots to agent PRs, and Anthropic required browser checks before a feature counted as done. No artifact means not done."],
        ["Tests", "Tests are the evaluation you can rerun. Derive them from the acceptance criteria, keep them in their own task, and grade outcomes rather than paths: check what the system does, not which functions the agent happened to call."],
      ],
      callouts: [
        {
          type: "example",
          title: "The report every task prompt asks for",
          body: [
            "```text",
            "Criteria met:     AC-2, AC-3 (tests/inbox-api.test.ts: 9 passed)",
            "Criteria skipped: AC-5, blocked on Q3",
            "Commands run:     npm run typecheck (ok), npx vitest run (ok)",
            "Files changed:    apps/inbox/server.ts, apps/inbox/lib/store.ts",
            "Assumptions made: malformed lines skipped and counted (A6)",
            "```",
          ],
        },
      ],
      deeper: {
        title: "Transcripts are spec feedback",
        body: [
          "Anthropic's eval guide warns that you will not know whether your graders work unless you read the transcripts. The same holds for specs.",
          "After the first task finishes, skim the transcript for three signals:",
          "- Hesitation: the agent searched for the same fact several times. The context pack is missing a pointer.",
          "- Guessing: the agent wrote 'assuming' or picked a default you never set. That is a gap in the spec.",
          "- Workarounds: it bent a boundary to satisfy a criterion. The criterion and the boundary conflict.",
          "Each signal is a one-line fix to the spec before the next task starts. That is spec-anchored development in practice: the spec improves from evidence, not from rereading it.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "intent",
      q: "Your done criteria for approving a proposal say 'all tests pass'. What is the strongest objection?",
      options: [
        "Tests run too slowly to serve as the definition of done",
        "Tests can be weakened and may not cover the behavior",
        "Done criteria belong in the PR, not in the spec itself",
        "Test output cannot be attached to a pull request as proof",
      ],
      answer: 1,
      why: "Agents under pressure special-case or delete tests, and a green suite may never exercise the criterion. Define done as observable behavior plus named evidence, and keep acceptance tests in a separate task. Speed is a tuning problem, not the objection.",
    },
    {
      id: "q2",
      section: "context",
      q: "Your AGENTS.md says 'Follow @docs/conventions.md'. Claude Code follows those conventions and Codex ignores them. What is the most likely cause?",
      options: [
        "Codex does not expand `@` imports, so it never read the file",
        "Codex caps AGENTS.md at 32 KiB and dropped the imported file",
        "Codex prefers CLAUDE.md whenever both instruction files exist",
        "The Codex model needs the rule repeated in capital letters",
      ],
      answer: 0,
      why: "Codex concatenates AGENTS.md files from the repo root to the working directory but treats `@path` as plain text. Name the file and tell the agent to read it, or inline the rule. The 32 KiB cap truncates long chains, but a short file is not the issue.",
    },
    {
      id: "q3",
      section: "requirements",
      q: "Your spec says the proposal list should load 'fast'. What should interrogation turn this into?",
      options: [
        "A blocking question that stops work until the owner answers",
        "A number with a test: 200 proposals render in under a second",
        "An instruction for the agent to optimize performance where possible",
        "A backlog note to revisit performance once the Inbox launches",
      ],
      answer: 1,
      why: "An ambiguity is resolved by a number the agent can test. It rarely needs to block work, because a sensible default can be proposed and confirmed later. 'Optimize where possible' keeps the ambiguity and adds unbounded scope.",
    },
    {
      id: "q4",
      section: "specifications",
      q: "Which acceptance criterion is a negative example?",
      options: [
        "Given a pending proposal, approving it shows status approved",
        "Approving an approved proposal again records nothing new",
        "Given 50 proposals, the list shows all 50 sorted by severity",
        "Given a proposal, saving an edit lists the fields that changed",
      ],
      answer: 1,
      why: "A negative example states what must not happen, here a duplicate decision. Positive criteria alone let an agent satisfy the happy path by any means, including a non-idempotent endpoint. The other three describe desired behavior.",
    },
    {
      id: "q5",
      section: "decomposition",
      q: "Codex will build the Inbox API while Claude Code builds the UI in parallel. What must merge before either starts?",
      options: [
        "The first working UI screen, so the API can match it",
        "The shared contract file that both sides import",
        "The Playwright acceptance tests for every criterion",
        "A full visual design mock approved by the reviewer",
      ],
      answer: 1,
      why: "Both tasks depend on the contract. Merging it first lets each side build against the same types and routes, and turns integration into a check instead of a negotiation. A UI-first order serializes the work, and acceptance tests come after integration.",
    },
    {
      id: "q6",
      section: "evaluation",
      q: "When should the quality bar for Inbox v1 be written?",
      options: [
        "After the first build, once you know what is feasible",
        "Before any work starts, with the criteria",
        "During code review, when the reviewer sees the diff",
        "After release, once real usage data is available",
      ],
      answer: 1,
      why: "A bar written after you see the output bends to fit it. Set thresholds with the criteria, then tighten them on Day 15 when real usage shows what matters. At review time the reviewer anchors on what already exists.",
    },
    {
      id: "q7",
      q: "A headless `codex exec` run reaches a decision your spec leaves open. Which statement is most accurate?",
      options: [
        "It pauses and waits for your reply in the terminal",
        "No one can answer mid-run, so it guesses or stops",
        "It escalates the question to Claude Code automatically",
        "It retries the task until the spec covers the decision",
      ],
      answer: 1,
      why: "`codex exec` always runs with approval set to never, so there is no one to ask. The model picks a default or ends with a question, and both waste a run. Front-load blocking questions and turn the rest into assumptions with defaults.",
    },
    {
      id: "q8",
      q: "You split Inbox v1 into 14 tiny tasks across four agents. Integration is painful and agents duplicate work. What is the most likely cause?",
      options: [
        "The tasks were too large for each agent's context window",
        "Too many handoffs, where context and intent leaked away",
        "The agents ran different models with different styles",
        "The spec lacked enough Gherkin scenarios per task",
      ],
      answer: 1,
      why: "Fine-grained splits multiply handoffs, and inter-agent misalignment accounts for roughly 37% of failures in the MAST taxonomy. Size tasks as self-contained units with disjoint files. Model differences cause style drift, not duplicated work.",
    },
    {
      id: "q9",
      q: "An agent ends a task with 'All done, everything works.' What should your task prompt have required instead?",
      options: [
        "A longer summary with more detail about every change",
        "Criteria met and skipped, each with its evidence",
        "A confidence score from 1 to 10 for the whole change",
        "A second agent's opinion that the work looks complete",
      ],
      answer: 1,
      why: "A structured report makes the claim checkable: which criteria passed, what proves each one, and what was skipped or assumed. Confidence scores and second opinions add assertion, not evidence, and longer prose is harder to verify.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "Interrogate a real spec with both harnesses",
      goal: "See how differently two harnesses read the same requirements, and what each one catches that you would miss.",
      steps: [
        "Save a recent issue or PRD you wrote as `spec.md` in any repo.",
        "Run `claude -p \"Read spec.md. List ambiguities, contradictions, and missing information, each with the line that raised it. At most 10 items. Do not propose fixes.\"`.",
        "Run the same prompt with `codex exec --sandbox read-only \"...\"`.",
        "Mark each finding as shared or unique, and circle the one you would not have caught alone.",
      ],
      done: "You have two finding lists for one spec, with shared and unique items marked and one finding you would have missed.",
    },
    {
      id: "build",
      level: "build",
      minutes: 60,
      title: "Spec the work for agents",
      goal: "Turn the Inbox brief into an agent-ready spec with Gherkin criteria, negative examples, and boundaries, have both harnesses interrogate it, then decompose it into task files.",
      steps: [
        "Copy the spec template to `docs/specs/inbox-v1.md` and the scenarios to `docs/specs/inbox-v1.feature`. Rewrite both against your brief and the Day 11 prototype decision. Keep the `@AC-n` tags stable.",
        "Run the interrogation prompt in Claude Code, then run it again with `codex exec --sandbox read-only` from the repo root. Merge the two lists.",
        "Answer every blocking question in the spec's Questions log, and turn each non-blocking one into an assumption with a default.",
        "Start `claude --permission-mode plan` and paste the decomposition prompt. Approve the graph and ownership table, then let it write `tasks/inbox-01-contract.md` through `tasks/inbox-06-acceptance.md` from `tasks/_template.md`.",
        "Check the graph: T2 and T3 share only the contract, every task has a checkpoint command, and no two tasks own a file. Commit the spec, the feature file, and the tasks, and list them in `tasks/progress.md`.",
      ],
      prompts: [
        {
          label: "Claude Code or Codex: interrogate the spec",
          text: [
            "Read docs/specs/inbox-v1.md, docs/specs/inbox-v1.feature, docs/product/inbox-brief.md, src/schema.ts, and AGENTS.md.",
            "Goal: find every place where two competent engineers would build different things from this spec. Do not edit files.",
            "",
            "Report, in this order:",
            "1. Contradictions between any two of these files, quoting both sides.",
            "2. Ambiguities: words or criteria without a number, an example, or an owner.",
            "3. Missing information: states, errors, limits, or data cases the spec never covers.",
            "4. Hidden assumptions, each marked safe, risky, or blocking.",
            "5. At most five blocking questions, each with the default you would choose if I do not answer.",
            "",
            "Cite a line or AC id for every item. If a section is already unambiguous, say so. Keep the report under 60 lines.",
          ],
        },
        {
          label: "Claude Code (plan mode): decompose into tasks",
          text: [
            "Read docs/specs/inbox-v1.md, docs/specs/inbox-v1.feature, docs/map.md, and tasks/_template.md.",
            "Goal: decompose Inbox v1 into at most six task files, tasks/inbox-01-contract.md to tasks/inbox-06-acceptance.md.",
            "",
            "Rules:",
            "- T1 is the shared contract in apps/inbox/shared/contract.ts (Zod schemas for Proposal, DecisionInput, Decision, and the route list). Every other task depends on it.",
            "- The API and data layer (apps/inbox/server.ts, apps/inbox/lib/) go to Codex. The React UI (apps/inbox/src/) goes to Claude Code. Integration and merges go to me.",
            "- Each task lists harness, blocked by, blocks, files it owns, files it must not touch, the AC ids it covers, a checkpoint command, and the report it must return.",
            "- No two tasks own the same file. Playwright tests for the acceptance criteria belong to T6 only.",
            "- Mark the two merge points: after T1, and at integration (T5).",
            "",
            "First show me the dependency graph as a Mermaid flowchart and a file ownership table. Wait for my approval before writing any files. If a criterion fits no task, list it instead of forcing it in.",
          ],
        },
      ],
      code: [
        { title: "docs/specs/inbox-v1.md", lang: "md", file: "d12/inbox-v1-spec.md" },
        { title: "docs/specs/inbox-v1.feature", lang: "gherkin", file: "d12/inbox-v1.feature" },
        { title: "tasks/inbox-02-api.md (example task file)", lang: "md", file: "d12/task-inbox-02-api.md" },
      ],
      minimum: "A spec with five acceptance criteria, at least one negative example, and boundaries, plus a task list with dependencies.",
      done: "`docs/specs/inbox-v1.md` and `docs/specs/inbox-v1.feature` are committed with tagged criteria and a filled Questions log, and `tasks/inbox-*.md` list owners, dependencies, harnesses, and checkpoint commands.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 45,
      title: "Size the spec to the risk",
      goal: "Measure what the full spec buys by building one slice from a three-line spec and from the full spec, side by side.",
      steps: [
        "Write a three-line spec for the proposal list only: the outcome, AC-1, and one boundary.",
        "Create two worktrees: `git worktree add ../forge-spec-min -b spec-min` and `git worktree add ../forge-spec-full -b spec-full`. Install dependencies in each, since the Codex sandbox has no network by default.",
        "In each worktree, run the same build request with `codex exec --sandbox workspace-write`, pointing one at the short spec and the other at `docs/specs/inbox-v1.md`.",
        "Score both results against AC-1, AC-6, and AC-9, and count the corrections each one needs.",
        "Record the counts in the spec's change log, with one rule for sizing future specs. Remove both worktrees.",
      ],
      done: "The spec's change log records correction counts for both runs and one sizing rule you will reuse.",
    },
  ],
  glossary: [
    ["Definition of done", "Observable checks, each with named evidence, that must all hold before work counts as finished."],
    ["Context pack", "The files an agent needs for a task, linked from the spec: brief, map, schema, conventions, prior decisions."],
    ["Characterization test", "A test that records what existing code does today, so a change that alters that behavior fails visibly."],
    ["Gherkin", "Given, When, Then syntax for acceptance scenarios that reads as prose and maps onto automated tests."],
    ["EARS", "Easy Approach to Requirements Syntax. Templates such as 'WHEN trigger, THE SYSTEM SHALL response'."],
    ["Negative example", "A criterion stating what must not happen, such as a duplicate decision or a forbidden network call."],
    ["Spec-anchored", "Böckeler's middle level of spec-driven development: the spec is maintained with the code and changes first."],
    ["Checkpoint", "The end of a task: a command that must pass, a commit, and a progress entry, so a failure stays cheap to redo."],
  ],
  resources: [
    { title: "Böckeler: understanding spec-driven development", url: "https://martinfowler.com/articles/exploring-gen-ai/sdd-3-tools.html", note: "The three spec levels and an honest critique of Kiro, Spec Kit, and Tessl." },
    { title: "GitHub Spec Kit", url: "https://github.com/github/spec-kit", note: "A working specify, plan, tasks, and implement flow with adapters for many harnesses." },
    { title: "Kiro specs", url: "https://kiro.dev/docs/specs/", note: "EARS requirements, design, and task files in one opinionated flow." },
    { title: "Effective harnesses for long-running agents", url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents", note: "Feature lists that start failing, progress files, and one feature per session." },
    { title: "Why do multi-agent LLM systems fail? (MAST)", url: "https://arxiv.org/abs/2503.13657", note: "Fourteen failure modes, with specification problems as the largest group." },
    { title: "When to use multi-agent systems", url: "https://claude.com/blog/building-multi-agent-systems-when-and-how-to-use-them", note: "Split by context rather than role, and what extra agents cost." },
    { title: "Claude Code memory and AGENTS.md", url: "https://code.claude.com/docs/en/memory", note: "How Claude Code loads CLAUDE.md, path-scoped rules, and AGENTS.md." },
  ],
  reflect: [
    "Which criterion in your spec could an agent satisfy in a way you did not intend?",
    "Which interrogation finding would you have missed alone, and which harness caught it?",
    "Where in a past project would a checkpoint after each task have saved you a rework cycle?",
  ],
}
