export default {
  day: 16,
  hook: "Until today Triage ran when you typed a command. From now on it runs while you sleep, so every control you relied on by watching must become code.",
  anchor: "You already run `npm run triage` on demand, with turn and budget caps, guardrails, JSONL traces, and an approval gate before `create_issue`.",
  plusOne: "Today Triage runs on a schedule without you, and every step up in autonomy gets a matching control: a level, a budget, a checkpoint, a kill switch, and an escalation.",
  tldr: [
    "Autonomy is a design choice per action: grant it by reversibility and blast radius, then adjust it on evidence.",
    "Unattended runs keep state outside the context window: checkpoints, idempotency keys, and a resume path that never repeats a side effect.",
    "Budgets, kill switches, and escalation are runtime code. A limit written in AGENTS.md advises the model and enforces nothing.",
  ],
  outcomes: [
    "Assign a supervision level to every Triage action by reversibility and blast radius",
    "Run Triage on a schedule that checkpoints, resumes, and never repeats a side effect",
    "Stop a runaway run with a run budget, a kill switch, and a clear escalation",
  ],
  minutes: { learn: 22, practice: 80 },
  map: {
    title: "One unattended run, start to finish",
    mermaid: [
      "flowchart LR",
      '  T["Trigger<br/>cron, event, button"] --> G["Gate<br/>kill switch, budget left"]',
      '  G -->|"go"| R["Resume<br/>load the checkpoint"]',
      '  R --> W["Work<br/>one item within caps"]',
      '  W --> C["Checkpoint<br/>ids, spend, effect keys"]',
      '  C -->|"more items"| W',
      '  C --> V["Report<br/>counts, traces, cost"]',
      '  G -->|"stop"| E["Escalate<br/>one issue, one question"]',
      '  W -->|"cap hit or failure"| E',
    ],
    caption: "Every arrow out of Work is a decision you encode before the run starts, because nobody is watching when it happens.",
  },
  sections: [
    {
      id: "autonomy",
      title: "Autonomy",
      lead: "Grant autonomy per action, scaled to what an error costs and how easily it reverses.",
      bites: [
        ["Supervision levels", "The human role per action, from operator to observer, after Feng, McDonald and Zhang (2025). This course uses L0 suggest, L1 approve each, L2 bounded, L3 sampled review, and L4 audit only. Levels attach to tools, so one agent holds several."],
        ["Bounded independence", "The agent picks the method. You fix the envelope: tools, paths, spend, wall time, and which effects need a human. In Anthropic's API data only 0.8% of agent actions appear irreversible, so a short gate list covers most of the risk."],
        ["Proactive behavior", "Acting on a schedule or event instead of a prompt. Keep it opt-in and quiet: an ambient agent reports nothing when nothing needs attention and escalates only when something does. Every proactive trigger multiplies runs, and with them cost and false alarms."],
        ["Trust calibration", "Set supervision from measured reliability. Claude Code users approved 93% of prompts, which signals fatigue rather than review. In Anthropic's field data experienced users auto-approve more sessions (about 20% rising past 40%) and interrupt more turns (5% to 9%): they monitor instead of gatekeeping."],
        ["Harness autonomy dials", "Claude Code sets autonomy through permission modes (`plan`, Manual, `acceptEdits`, `auto`, `dontAsk`, `bypassPermissions`) plus an optional OS sandbox. Codex uses two axes: `approval_policy` (`on-request` or `never`) and a sandbox (`read-only`, `workspace-write`, `danger-full-access`). Map each level to both."],
      ],
      visual: {
        table: {
          head: ["Level", "Human role", "Claude Code", "Codex", "Triage example"],
          rows: [
            ["L0 Suggest", "Acts on the advice", "`plan` mode", "`/plan` with `:read-only`", "Propose a label taxonomy"],
            ["L1 Approve each", "Approves every effect", "Manual, or the Inbox gate", "`:read-only` plus `-a on-request`", "`create_issue`"],
            ["L2 Bounded", "Approves irreversible effects only", "`dontAsk` plus an allowlist", "`codex exec` (always `never`) in a sandbox", "Scheduled `save_triage` and `draft_issue`"],
            ["L3 Sampled", "Reviews a sample afterwards", "`auto` plus the sandbox", "`--approve-for-me` (auto-review)", "Labels on new issues (Day 19)"],
            ["L4 Audited", "Reads the log", "`bypassPermissions` in a container", "`--yolo` in a container", "A report built in a throwaway sandbox"],
          ],
        },
        caption: "One scheduled Triage run holds `save_triage` at L2 and `create_issue` at L1. Levels describe actions, not agents.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Approval fatigue is a failed control",
          body: "At 93% approval the prompt no longer screens anything. Pre-approve routine reversible actions, keep prompts for irreversible ones, and sample the rest afterwards. Rare prompts get read.",
        },
      ],
      deeper: {
        title: "In the loop, on the loop, and the capability gap",
        body: [
          "In the loop means actions wait for a human. On the loop means the agent acts while a human watches and can interrupt. Anthropic's autonomy research favors making sure people can effectively monitor and intervene over approving each action, because per-action approval decays into reflex.",
          "Capability is rising faster than trust processes. METR's 50% time horizon has doubled roughly every seven months since 2019, and faster in 2024 and 2025. METR itself calls measurements above 16 hours unreliable, and nobody has shown that benchmark hours map onto messy product work.",
          "The contrarian reading: a time horizon is not a trust horizon. A model that finishes a four-hour task half the time also fails it half the time. That is why this course promotes reversible actions first and keeps public, irreversible effects behind a human.",
        ],
      },
    },
    {
      id: "runtime",
      title: "Runtime",
      lead: "Unattended work needs something that wakes the agent, feeds it work, and survives a crash.",
      bites: [
        ["Events · triggers", "An event is a fact: issue opened, deploy finished. A trigger binds an event to a run. Treat payloads as data: Claude Code routines wrap fired API text in a block labeled untrusted, and the saved prompt must opt in before acting on it."],
        ["Jobs · queues", "A job is one unit of work with an id, input, status, and owner. A queue separates arrival from processing, so a burst of 500 feedback items waits instead of starting 500 agents. Give each job a deterministic idempotency key before it touches anything outside."],
        ["Schedules", "GitHub Actions schedules may start late, or be dropped, at busy times such as the top of the hour, so pick an odd minute. Claude Code routines run in the cloud, hourly at most. Codex offers Desktop automations, not a CLI scheduler."],
        ["Heartbeats", "Two meanings. A periodic wake-up that asks whether anything needs attention and usually does nothing, and a liveness signal a long job emits so a supervisor can spot a stall. Make the idle beat cheap and silent, and skip beats while a run is busy."],
        ["Long-running loops", "A loop that outlives one context window hands off through files, not memory. Anthropic's harness has each session read a progress log, do one feature, commit, and update the log. Compaction keeps continuity but not a clean slate, so pair resets with handoff files."],
        ["Durable execution", "Temporal, Inngest, Restate, DBOS, and Cloudflare's agent workflows journal each step so a crash resumes, not restarts. Steps are at-least-once: a crash between an external call and its journal entry reruns it. A Sep 2026 Restate issue hit duplicates in 30 of 30 timed kills."],
      ],
      visual: {
        table: {
          head: ["Runtime", "Survives a closed laptop", "Shortest interval", "State between runs", "Good for"],
          rows: [
            ["Local cron or launchd", "No", "1 minute", "Your disk", "Dev loops next to the Inbox"],
            ["GitHub Actions `schedule`", "Yes", "5 minutes, may run late", "None unless you save it", "Repo chores that end in a PR"],
            ["Claude Code routine", "Yes, in the cloud", "1 hour", "Repo plus the cloud session", "Claude Code work with connectors"],
            ["Claude Code `/loop`", "No, ends with the session", "1 minute, 7-day expiry", "The live session", "Watching a deploy while you work"],
            ["`codex exec` under cron or Actions", "Same as its host", "Same as its host", "Only what you save", "Codex work on a schedule"],
            ["Durable engine", "Yes", "Seconds", "Journaled steps", "Production pipelines with retries"],
          ],
        },
        caption: "Choose by where state must live. An ephemeral runner forgets everything you do not save.",
      },
      callouts: [
        {
          type: "example",
          title: "A schedule that never overlaps itself",
          body: [
            "```yaml",
            "on:",
            "  schedule:",
            "    - cron: '17 6 * * 1-5'",
            "  workflow_dispatch:",
            "concurrency:",
            "  group: triage-schedule",
            "  cancel-in-progress: false",
            "```",
            "The odd minute dodges top-of-hour delays. The concurrency group makes a slow run finish before the next one starts.",
          ],
        },
      ],
      deeper: {
        title: "Why durable engines replay, and where they stop helping",
        body: [
          "A durable engine runs your workflow code, records each step's result in a journal, and after a crash replays the code from the top, returning recorded results instead of re-executing finished steps. Replay only works when the workflow code is deterministic, which is why Claude Code's dynamic workflow scripts throw on `Date.now()` and `Math.random()`.",
          "The gap is the moment between a step's side effect and its journal write. Crash there and the engine cannot know the call succeeded, so it runs it again. Restate's docs issue #410 showed exactly that on every timed kill.",
          "The fix lives outside the engine. Send an idempotency key the external system honors (Restate offers `ctx.uuid()` for this), or check the outside world before retrying. The GitHub API has no idempotency header for creating issues, so today's build does the second.",
        ],
      },
    },
    {
      id: "state",
      title: "State",
      lead: "If state lives only in the context window, a crash, compaction, or timeout erases the run.",
      bites: [
        ["Persistent sessions", "A transcript you can resume by id: `claude -r`, the Agent SDK `resume` option, `codex exec resume`. Resuming restores conversation only, not files or the outside world, and Claude Code sweeps transcripts after 30 days. Keep what a run depends on in your own files."],
        ["Checkpoints", "A record of where a run stopped: finished ids, the item in flight, spend, and pending effects. Write one after every unit of work, atomically (temp file, then rename). Claude Code `/rewind` covers file edits only, not Bash, and Codex removed `/undo` in April 2026."],
        ["Resumability", "A resumable run restarts from its checkpoint and skips finished work. Test it by killing the process mid-batch, twice. The hard case is an effect that happened but was never recorded, which is why each effect carries a key written before the call."],
        ["Shared state", "State several runs or agents touch: the results file, the issue tracker, the spend ledger. Two overlapping schedules can pick the same item. Serialize them with a `concurrency` group, give each writer unique keys, and make every write idempotent by id."],
        ["Continuity across runs", "What the next run must know: cursor, open escalations, today's spend, flaky sources, lessons. Anthropic observed that JSON survives agent edits better than Markdown, so keep machine state in JSON and human notes in Markdown. A CI runner remembers nothing you do not save."],
      ],
      visual: {
        mermaid: [
          "stateDiagram-v2",
          "  [*] --> Running",
          "  Running --> Checkpointed: item saved",
          "  Checkpointed --> Running: next item",
          "  Running --> Paused: budget or kill switch",
          "  Paused --> Running: next run resumes",
          "  Running --> Failed: unrecoverable error",
          "  Failed --> Escalated: human notified",
          "  Checkpointed --> Done: backlog empty",
          "  Done --> [*]",
        ],
        caption: "Every path back into Running starts from saved state, so a crash anywhere costs at most one item. Failed stays failed until a human clears it.",
      },
      callouts: [
        {
          type: "example",
          title: "state/triage-checkpoint.json after a budget stop",
          body: [
            "```json",
            "{",
            "  \"version\": 1,",
            "  \"runId\": \"gh-18234871\",",
            "  \"status\": \"paused\",",
            "  \"stopReason\": \"run_budget\",",
            "  \"completed\": [\"fb_0398\", \"fb_0399\", \"fb_0400\"],",
            "  \"spend\": { \"day\": \"2026-11-16\", \"usd\": 2.03 },",
            "  \"effects\": { \"forge-3f9a1c0d7e2b4a11\": { \"kind\": \"escalation\", \"status\": \"done\" } }",
            "}",
            "```",
          ],
        },
      ],
      deeper: {
        title: "Write the intent before the effect",
        body: [
          "An unattended effect has three crash windows: before the call, during it, and after it but before you record it. The first is harmless. The last one duplicates issues.",
          "Write-ahead intent closes it. Record `{ key, status: 'intent' }` in the checkpoint, then make the call with the key embedded in the effect itself, such as a hidden `<!-- forge-... -->` marker in the issue body. After a crash, an intent without a result means you look outside before retrying. Found means done, so record it. Not found means it never happened, so retry.",
          "Derive the key from the inputs (run id, action, item id), never from a random value. A random key changes on retry, and the check finds nothing.",
        ],
      },
    },
    {
      id: "control",
      title: "Control",
      lead: "Every unattended capability needs a limit enforced in code and a human path for when it trips.",
      bites: [
        ["Permissions", "Restrict, then pre-approve. Agent SDK `allowedTools` only pre-approves, and unlisted tools fall through to the permission mode. Remove tools with `tools` or `disallowedTools` and run with `dontAsk`, which denies anything unlisted. `codex exec` always uses approval `never`, so its sandbox is the boundary."],
        ["Budgets", "`maxTurns` and `maxBudgetUsd` end a query with `error_max_turns` or `error_max_budget_usd`. The dollar cap is a client-side estimate for the current call only, so a run resumed five times can spend five budgets. Codex reports tokens, not dollars, so bound it with a timeout."],
        ["Approval gates", "A gate holds a side effect until a named human decides, and the default answer is no. Gate irreversible or external effects: creating issues, emailing, merging. Unattended, a gate becomes a queue, so Triage drafts to the Inbox and moves on instead of waiting."],
        ["Cancellation", "A kill switch is a flag checked before every side effect and wired to an `AbortController` (Agent SDK `abortController`, Codex SDK `signal`). A flag read only at start leaves a running job free. The fastest stop is a revoked credential, so keep tokens short-lived."],
        ["Escalation", "Escalation turns a stop into a decision for a person. Define the triggers (cap hit, repeated tool failure, policy block, low confidence), one channel, and the payload: run id, checkpoint, spend, and the one question you need answered."],
        ["Human intervention", "Keep cheap ways in: interrupt, pause, edit the plan, resume from the checkpoint. After an incident agent tried to recruit another agent to push fixes, Anthropic drew its boundaries around access and actions rather than instructions, with one single-purpose identity per agent."],
      ],
      visual: {
        mermaid: [
          "flowchart TD",
          '  A["Agent wants a side effect"] --> K{"Kill switch on?"}',
          '  K -->|"yes"| S["Stop and checkpoint"]',
          '  K -->|"no"| B{"Run and daily budget left?"}',
          '  B -->|"no"| S',
          '  B -->|"yes"| L{"Level allows it unattended?"}',
          '  L -->|"no"| D["Draft to the Inbox"]',
          '  L -->|"yes"| I{"Key already recorded?"}',
          '  I -->|"yes"| X["Skip and link the existing one"]',
          '  I -->|"no"| G["Record intent, execute, record result"]',
        ],
        caption: "The guard runs before every effect, not once per run. Each branch is ordinary code you can unit test.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "A budget per call is not a budget per run",
          body: "`maxBudgetUsd` counts spend since the current `query()` started. A scheduler that resumes after every crash can spend its cap many times over. Keep run and daily totals in the checkpoint and pass only the remainder.",
        },
      ],
      deeper: {
        title: "Where permission rules leak",
        body: [
          "Claude Code resolves deny, then ask, then allow, and a hook's allow never overrides a deny rule. The leaks are in matching. `Bash(git push *)` does not match `git -C . push`, and a `curl` deny misses `sh -c \"curl ...\"`. Pair Bash rules with the OS sandbox, which constrains the process whatever string started it.",
          "Codex has the same shape. Exec-policy `prefix_rule` entries match command prefixes, and the sandbox (network off by default in `workspace-write`) is what actually holds.",
          "For unattended runs the credential is the real boundary. The scheduled Triage job gets a token that can write issues and pull requests in one repository and nothing else, so an injected instruction has nowhere to go.",
        ],
      },
    },
    {
      id: "observation-recovery",
      title: "Observation and Recovery",
      lead: "Nobody watches an unattended run, so it must report progress, cost, and failure in a form you can scan.",
      bites: [
        ["Progress", "Report counts, not narration: processed, drafted, skipped, escalated, and spend, in one line per run. A green job means no infrastructure error, not good triage. Read the counts daily and a few transcripts weekly."],
        ["Traces · costs", "Stamp every trace line with run id, item, model, prompt version, tokens, and cost, so one query answers what ran, what it cost, and why it stopped. Watch burn rate per run: runaway loops fall under OWASP's LLM06 Unbounded Consumption, also called denial of wallet."],
        ["Failures · retries", "Classify before retrying. Transient faults (overload, dropped connection) get bounded backoff. Unrecoverable ones (auth, credits, context overflow) stop and escalate. Semantic failures repeat on retry, and retrying a tool that is not idempotent repeats its side effect."],
        ["Rollbacks", "Each effect needs its own undo: `git revert` for files, a version move for prompts and skills, close and link for a wrong issue. Verify undo claims yourself: Replit's agent said a rollback was impossible, and it was not."],
        ["Repairs", "A repair fixes the cause and lands as a reviewed change: an eval case, a guardrail, a rule. Inside a run, returning tool errors to the agent lets it adapt, which Anthropic found works well. Changes to the system go through a PR you approve."],
      ],
      visual: {
        table: {
          head: ["Failure", "Detect", "Automatic action", "Escalate when"],
          rows: [
            ["529 overload", "`api_error` in the trace", "Backoff, 3 tries", "Still failing after 3"],
            ["Budget hit", "`run_budget` or `error_max_budget_usd`", "Stop, save the checkpoint", "Always, with the spend"],
            ["Tool error", "`is_error` result", "Return the error once", "Same tool fails twice"],
            ["Duplicate effect", "Key already in the ledger", "Skip and link", "Never"],
            ["Bad output", "Zod parse fails", "One repair turn", "Second failure"],
            ["Kill switch", "`state/STOP` or a cancelled run", "Stop, save the checkpoint", "Always"],
          ],
        },
        caption: "Write the runbook before the first unattended run. Each row is also a test case.",
      },
      callouts: [
        {
          type: "pro",
          title: "Drill the crash, not the happy path",
          body: "Run `timeout -s KILL 30 npm run triage -- --scheduled`, then run it again. `KILL` gives the process no chance to clean up. Compare result lines and escalation comments before and after. If either doubled, resume repeats side effects.",
        },
      ],
      deeper: {
        title: "Autonomy that steps down on its own",
        body: [
          "SRE error budgets translate well to agents. Set a target per action, such as 95% of scheduled runs finishing without escalation and under $2, and measure it weekly from traces.",
          "Tie the budget to supervision levels. An action earns promotion after a window of clean runs with sampled human agreement, and it drops a level automatically when the budget burns, for example after a wrong label on a critical issue. The demotion is code, not a meeting.",
          "This makes trust calibration symmetric. Most teams only ever promote, so autonomy ratchets up and never down. A demotion rule is what lets you promote sooner, because a mistake reverses itself.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "autonomy",
      q: "Your team approves 93% of the agent's permission prompts without reading them. What is the best change?",
      options: [
        "Require a second human approver on every single prompt",
        "Allowlist routine actions and gate only irreversible ones",
        "Switch to `bypassPermissions`, since the approvals are rubber stamps anyway",
        "Lower the effort setting so the agent asks for fewer approvals",
      ],
      answer: 1,
      why: "At 93% approval the prompt stopped being a control. Pre-approving reversible routine actions frees attention for the few irreversible ones. Bypassing permissions removes the remaining gates, and a second approver doubles the fatigue.",
    },
    {
      id: "q2",
      section: "runtime",
      q: "A GitHub Actions triage job scheduled at `0 9 * * *` sometimes starts 20 minutes late and once did not run at all. What is the most likely cause?",
      options: [
        "Runs queued at the top of the hour can be delayed or dropped",
        "The cron line is invalid, so GitHub falls back to a best-effort interval",
        "The runner image is cold, so the first job of the day waits for it",
        "The concurrency group cancelled the run, so remove the concurrency key",
      ],
      answer: 0,
      why: "GitHub documents that scheduled runs can be delayed at high-load times such as the start of each hour, and some queued runs are dropped. Schedule at an odd minute and alert on missed runs. A concurrency group with `cancel-in-progress: false` queues runs rather than cancelling them.",
    },
    {
      id: "q3",
      section: "state",
      q: "A scheduled run crashed after GitHub created an escalation issue but before the run recorded it. On resume, what prevents a second issue?",
      options: [
        "A key written before the call and searched for before any retry",
        "Durable execution, which guarantees every step runs exactly once",
        "Resuming the Agent SDK session, which restores prior tool results",
        "A lower `maxTurns`, so the agent cannot afford to repeat the call",
      ],
      answer: 0,
      why: "The crash window sits between the effect and its record, so any engine that replays repeats the call. A write-ahead key embedded in the issue lets resume detect the earlier success. Durable engines give at-least-once steps, and a resumed session restores conversation, not the outside world.",
    },
    {
      id: "q4",
      section: "control",
      q: "Scheduled Triage uses `allowedTools` listing two MCP tools and `permissionMode: 'bypassPermissions'` so it never blocks. A trace shows it ran `curl`. What went wrong?",
      options: [
        "`allowedTools` only pre-approves, so bypass approved the rest",
        "An MCP tool spawned a shell internally, which permissions cannot see",
        "Bypass mode ignores both `allowedTools` and `disallowedTools` entirely",
        "The model ignored its instructions, so the fix is a firmer system prompt",
      ],
      answer: 0,
      why: "Pre-approval is not restriction. Remove tools with `tools` or `disallowedTools`, and run unattended with `dontAsk` so anything unlisted is denied. Deny rules hold in every mode, so a `disallowedTools` entry for Bash would have stopped the call.",
    },
    {
      id: "q5",
      section: "observation-recovery",
      q: "The nightly triage job has been green for two weeks. What does that tell you?",
      options: [
        "Only that nothing crashed, not that triage was right",
        "Triage quality holds, since failing evals would have turned the job red",
        "Costs are stable, since GitHub fails any job that exceeds its budget",
        "No escalations happened, since an escalation always fails the job",
      ],
      answer: 0,
      why: "A green job means the workflow exited zero. Quality needs counts, sampled transcripts, and eval checks. Unless you wire evals or budgets to fail the job, neither turns it red, and GitHub knows nothing about your model spend.",
    },
    {
      id: "q6",
      q: "You want Triage to label new issues without you. Which first step up the ladder is right?",
      options: [
        "Move the whole agent to L4 in a container, since labels are reversible",
        "Stay at L1 until the model makes zero labeling mistakes for a week",
        "Grant labels L2 while `create_issue` stays gated, then sample",
        "Grant L3 to every tool at once, since auto mode will catch the mistakes",
      ],
      answer: 2,
      why: "Autonomy is granted per action. Labels are reversible and cheap, so they move up while irreversible creation stays gated. Waiting for zero errors never ends, and auto mode missed 17% of real overeager actions in Anthropic's own measurement.",
    },
    {
      id: "q7",
      q: "A resumed run hits its $2 cap again after already spending $2 before the crash. Total spend is $4 against a $2 run budget. What is the fix?",
      options: [
        "Store spend in the checkpoint and pass only the remainder",
        "Lower `maxTurns`, since turns are what the budget really counts",
        "Nothing, because the SDK tracks spend across resumed sessions",
        "Set the budget in AGENTS.md so every resumed session reads it",
      ],
      answer: 0,
      why: "`maxBudgetUsd` covers spend since the current `query()` started. A resumed run starts a fresh count, so the run and daily totals must live in your state. A number in AGENTS.md advises the model and enforces nothing.",
    },
    {
      id: "q8",
      q: "Which failure should an unattended run not retry automatically?",
      options: [
        "A 529 overload response from the API",
        "A connection dropped mid-stream",
        "An expired API key",
        "A timeout on a read-only search tool",
      ],
      answer: 2,
      why: "Auth failures are unrecoverable: every retry fails the same way and burns attempts, so stop and escalate. Overloads and dropped connections are transient, and a read-only search is safe to retry because it has no side effect.",
    },
    {
      id: "q9",
      q: "Your kill switch is checked only when the scheduled run starts. What gap remains?",
      options: [
        "A run already in progress keeps acting until it ends",
        "None, because a scheduled run cannot outlive its runner",
        "Only cost, since the budget will stop the run anyway",
        "The flag must also live in AGENTS.md so the model obeys it",
      ],
      answer: 0,
      why: "A switch read once cannot stop a run that has started. Check it before every side effect and wire it to an `AbortController`. Budgets bound spend, not harm, and a flag the model reads is only a request.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "Watch a budget end a run",
      goal: "See stop reasons as data your scheduler can branch on, in both harnesses.",
      steps: [
        "In any git repo, run `claude -p \"Read every file here and summarize each in one line\" --max-turns 2 --output-format json | jq '{subtype, num_turns, total_cost_usd}'`. Expect `error_max_turns`.",
        "Run it again with `--max-turns 50 --max-budget-usd 0.02`. Expect `error_max_budget_usd`, and note how far past the cap the reported cost landed.",
        "Run `codex exec --json --ephemeral \"Read every file here and summarize each in one line\" | jq -c 'select(.type==\"turn.completed\") | .usage'`. Codex reports tokens, not dollars, and has no dollar cap.",
        "Write one line per stop reason: what should a scheduler do when it sees it?",
      ],
      done: "You have seen `error_max_turns` and `error_max_budget_usd` as JSON subtypes and a Codex token count, and written the action each should trigger.",
    },
    {
      id: "build",
      level: "build",
      minutes: 80,
      title: "Let it run on its own",
      goal: "Triage runs on a schedule without you, stops at its budget or kill switch, resumes from a checkpoint without repeating work, and escalates to a named human.",
      steps: [
        "Save the supervision table as `docs/supervision-levels.md` and adjust any level you disagree with. `create_issue` stays at L1.",
        "Add `src/run/checkpoint.ts`, `src/run/guard.ts`, and `src/run/escalate.ts` from the snippets, then run `npm run typecheck`.",
        "Paste the wiring prompt into Claude Code. It adds `npm run triage -- --scheduled` with Vitest tests and leaves the interactive path alone.",
        "Drill locally: run with `--budget-usd 0.30` until it pauses, run again to resume, then interrupt one run with `timeout -s KILL 20` and rerun. `jq -r .id data/triage/results.jsonl | sort | uniq -d` must print nothing.",
        "One-time setup from the workflow header: the `ANTHROPIC_API_KEY` secret, the `TRIAGE_ENABLED` variable, and two labels. Add `.github/workflows/triage-schedule.yml` and push.",
        "Trigger it once with `gh workflow run triage-schedule.yml -f budget_usd=0.50`, then let the cron fire on its own the next weekday morning.",
        "Paste the review prompt into Codex, fix what it finds, and open the PR.",
      ],
      prompts: [
        {
          label: "Claude Code: wire the scheduled mode",
          text: [
            "Goal: add an unattended mode, `npm run triage -- --scheduled --budget-usd 2 --daily-cap-usd 5`.",
            "",
            "Context: read src/agent.ts, src/guardrails.ts, src/schema.ts, docs/supervision-levels.md, and the new src/run/checkpoint.ts, guard.ts, and escalate.ts. Feedback lives in data/inbox/*.jsonl and results in data/triage/results.jsonl.",
            "",
            "Build src/run/scheduled.ts:",
            "1. Pending items are inbox ids with no result yet and not in the checkpoint's completed list. Use GITHUB_RUN_ID as the run id when set, otherwise local-<ISO time>.",
            "2. Call guard.check() before each item. Pass its maxBudgetUsd, the guard's abortController, and permissionMode 'dontAsk' into the per-item query. If src/agent.ts has no per-item function, extract triageOne(item, options) without changing current behavior.",
            "3. After each item, upsert the result by id (never append a duplicate line), then call completeItem() with the result's total_cost_usd.",
            "4. Only L2 and L3 tools from docs/supervision-levels.md may run. Deny create_issue in this mode and fall back to draft_issue.",
            "5. On any stop other than done, call escalate() with counts and one clear question. Stop after two consecutive item failures.",
            "6. Exit 0 when done, 3 when paused, 1 when failed.",
            "",
            "Tests (Vitest): a fake triageOne that charges $0.10 per item proves the run pauses at the budget, a second run resumes without re-triaging, and a crash between intent and done does not post a second escalation.",
            "",
            "Constraints: no new dependencies, and the interactive path of npm run triage must behave exactly as before. Run npm run typecheck and npm test and show both outputs.",
            "Ask before changing any supervision level or editing src/guardrails.ts.",
          ],
        },
        {
          label: "Codex: review against the levels",
          text: [
            "Review the diff on this branch against docs/supervision-levels.md and the runbook in src/run/.",
            "Check four things: (1) can any path in --scheduled mode call create_issue, (2) is guard.check() called before every side effect and not only at start, (3) can a crash between an effect and its record duplicate an escalation or a result line, (4) can a secret reach logs or traces.",
            "Report findings as file:line with a severity. Do not edit files. Run npm test and include the summary line.",
          ],
        },
      ],
      code: [
        { title: "docs/supervision-levels.md", lang: "md", file: "d16/supervision-levels.md" },
        { title: "src/run/checkpoint.ts", lang: "ts", file: "d16/checkpoint.ts" },
        { title: "src/run/guard.ts", lang: "ts", file: "d16/guard.ts" },
        { title: "src/run/escalate.ts", lang: "ts", file: "d16/escalate.ts" },
        { title: ".github/workflows/triage-schedule.yml", lang: "yaml", file: "d16/triage-schedule.yml" },
      ],
      minimum: "A scheduled run (cron or Actions) that stops at its budget with the checkpoint saved, and a second run that resumes without re-triaging finished items.",
      done: "`state/triage-checkpoint.json` shows a paused run with `stopReason` set to `run_budget`, the next run finishes the backlog with no duplicate ids in `data/triage/results.jsonl`, and an Actions run triggered by `schedule` (or a cron log) proves it fired on its own.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 45,
      title: "Prove resume is crash-safe",
      goal: "Show with a property test that no crash point can duplicate an effect or lose an item.",
      steps: [
        "Add `fast-check` as a dev dependency if Day 14 did not.",
        "Write `tests/run/crash.test.ts`: a fake GitHub records created issues, and a wrapper throws at a random step boundary (after the intent, after the call, after the record).",
        "Property: for any sequence of crash points followed by clean reruns, each idempotency key maps to at most one created issue and every item ends with exactly one result.",
        "Break it on purpose: build the key with `randomUUID()` instead of hashing the inputs. Watch the property fail and read the shrunk counterexample.",
      ],
      done: "The property passes 500 runs with deterministic keys and fails with random ones, and your notes explain why in two sentences.",
    },
  ],
  glossary: [
    ["Supervision level", "The human's role for one action, from operator (the agent only suggests) to auditor (the human reads the log afterwards)."],
    ["Bounded independence", "Freedom to choose methods inside fixed limits on tools, paths, spend, time, and which effects need a human."],
    ["Trust calibration", "Matching supervision to measured reliability, and promoting or demoting each action on evidence."],
    ["Heartbeat", "A periodic wake-up that checks for work and stays silent when there is none. Also a liveness signal from a long job."],
    ["Durable execution", "Journaling each workflow step so a crash resumes instead of restarting. Steps are at-least-once, not exactly-once."],
    ["Checkpoint", "A saved record of where a run stopped, written atomically after each unit of work."],
    ["Idempotency key", "A deterministic id attached to a side effect so a retry can detect that the effect already happened."],
    ["Write-ahead intent", "Recording an effect before performing it, so a crash leaves evidence to reconcile on resume."],
    ["Kill switch", "A control that stops a run between steps, checked before every side effect and wired to cancellation."],
    ["Escalation", "Handing a stopped or uncertain run to a named human with the state and the single question they must answer."],
  ],
  resources: [
    { title: "Measuring AI agent autonomy in practice", url: "https://www.anthropic.com/research/measuring-agent-autonomy", note: "Field data on auto-approval, interrupts, and irreversible actions." },
    { title: "Levels of Autonomy for AI Agents", url: "https://arxiv.org/abs/2506.12469", note: "The five user roles behind today's supervision ladder." },
    { title: "Effective harnesses for long-running agents", url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents", note: "Progress files, feature lists, and commits as continuity across context windows." },
    { title: "Claude Code auto mode", url: "https://www.anthropic.com/engineering/claude-code-auto-mode", note: "Measured false-positive and false-negative rates for an action classifier." },
    { title: "Agent SDK TypeScript reference", url: "https://code.claude.com/docs/en/agent-sdk/typescript", note: "`maxBudgetUsd`, `abortController`, `permissionMode`, and result subtypes." },
    { title: "Codex security: sandbox and approvals", url: "https://developers.openai.com/codex/security", note: "Approval policies, sandbox modes, trust, and network defaults." },
    { title: "Restate docs issue #410", url: "https://github.com/restatedev/docs-restate/issues/410", note: "A reproduction showing why durable steps still need idempotency keys." },
    { title: "Idempotency and durable execution", url: "https://temporal.io/blog/idempotency-and-durable-execution", note: "Temporal's explanation of at-least-once activities and how to design for them." },
  ],
  reflect: [
    "Which Triage action would you promote first, and what evidence would convince a skeptical colleague?",
    "Where in your current deploys does a crash between a side effect and its record already exist?",
    "What must an escalation message contain for you to decide in under a minute at 7 a.m.?",
  ],
}
