export default {
  day: 1,
  hook: "Every agent in this course is a loop around one operation: predict the next token from the context. Understand that operation and every harness, tool, and prompt trick becomes something you can reason about.",
  anchor: "You already get working code out of Claude Code and Codex by describing what you want and correcting what comes back.",
  plusOne: "Today you learn what happens between your prompt and the output, so you can predict failures instead of discovering them.",
  tldr: [
    "An LLM turns tokens into a probability distribution over the next token. Agents are scaffolding around that single step.",
    "Most surprising failures are mechanical: tokens are not letters, context is not memory, and fluent is not true.",
    "You steer a model through what enters its context and how it is phrased, not by persuading it.",
  ],
  outcomes: [
    "Explain tokenization, attention, and sampling well enough to predict common failures",
    "Compare providers on cost per finished task, not list price per token",
    "Choose between plain text, structured outputs, function calling, and native tools for a job",
  ],
  minutes: { learn: 20, practice: 45 },
  map: {
    title: "The whole stack in one loop",
    mermaid: [
      "flowchart LR",
      '  H["Harness<br/>loop, tools, memory"] --> C["Context window<br/>system, messages, tool results"]',
      '  C --> T["Tokenizer<br/>text to token IDs"]',
      '  T --> M["Transformer<br/>attention and MLP layers"]',
      '  M --> D["Next-token<br/>distribution"]',
      '  D --> S["Sample one token"]',
      '  S -->|"append and repeat"| C',
      '  S --> O["Output<br/>text, JSON, or tool call"]',
      '  O -->|"tool result"| H',
    ],
    caption: "The model only ever runs the middle boxes. The harness decides everything that enters the context window, which is why most of your leverage sits outside the model.",
  },
  sections: [
    {
      id: "introduction",
      title: "Introduction",
      lead: "Separate the model from everything around it. Most leverage lives in the parts you control.",
      bites: [
        ["Generative AI", "A model trained to continue sequences. Knowledge comes from pretraining. Behavior (persona, tool use, refusals) comes from post-training. So a model can know a fact and still misuse it, which is a prompting or harness problem rather than a knowledge gap."],
        ["Harnesses", "Everything around the model: the loop, tools, context management, permissions, memory, and retries. Claude Code and Codex are harnesses. The same model scores differently in different harnesses, so a benchmark number always describes a model plus a setup."],
        ["Configuration", "The layers you set: system prompt, request settings (model, `max_tokens`, effort), project files (`CLAUDE.md`, `AGENTS.md`), permissions, hooks, MCP servers, and skills. Configuration tuned for last year's model often misfires. Newer Claude models overtrigger on shouted rules like CRITICAL or MUST."],
        ["Agentic tooling", "The model emits a tool call, your code runs it, the result returns to context, and the loop repeats until the model stops. Context is usually the bottleneck: tool definitions and results can eat tens of thousands of tokens before real work starts."],
        ["Custom tools", "A name, a description, and a JSON Schema for inputs. The model reads only the description and schema, so write the description for a new hire: when to use it, what it returns, and what it will not do. Vague descriptions produce wrong calls."],
      ],
      visual: {
        table: {
          head: ["Concern", "Owned by", "Your lever"],
          rows: [
            ["Predicting the next token", "Model", "Model choice, effort"],
            ["What enters context", "Harness", "Instruction files, retrieval, compaction"],
            ["Running tools", "Harness", "Tool design, permissions, sandbox"],
            ["Remembering across sessions", "Harness", "Memory files, databases"],
            ["Deciding when to stop", "Both", "Stop conditions, budgets, max turns"],
          ],
        },
        caption: "The model is one row. The harness is the rest of the table, and it is where engineering effort pays off.",
      },
      deeper: {
        title: "Why 'the model is dumb' is usually the wrong diagnosis",
        body: [
          "When an agent fails, check the harness before the model. A practical triage order:",
          "1. The needed fact never entered context.",
          "2. A tool returned an unhelpful or oversized result.",
          "3. Instructions conflicted, or an old rule was written for an older model.",
          "4. The task hit an output or turn limit.",
          "5. Only then: the model lacks the capability.",
          "Anthropic has reported agents whose tool definitions and results used more than 50,000 tokens before the agent read the request. The fixes (tool search, programmatic tool calling) came from harness work, not from a bigger model.",
        ],
      },
    },
    {
      id: "mechanics",
      title: "Mechanics",
      lead: "Six mechanisms explain most of the model behavior you will ever debug.",
      bites: [
        ["Instructions", "System prompt, messages, and tool results all become tokens in one context. Training makes some sources more authoritative, but nothing enforces it. A rule with its reason generalizes better than a bare rule, because the model can apply the reason to cases you never listed."],
        ["Completion", "A base model continues documents. A chat model is a base model plus post-training plus a chat template that encodes roles as special tokens. Chat is still next-token prediction. Claude models from 4.6 on reject assistant prefill, so shape responses with structured outputs instead."],
        ["Tokenization (BPE)", "Byte-pair encoding turns text into subword token IDs, so the model never sees letters. That is why counting letters or reversing strings can fail. Tokenizers change between versions: Claude models since Opus 4.7 produce up to about 35% more tokens for the same text."],
        ["Prediction", "The last layer emits logits, softmax turns them into probabilities, and one token is sampled. Opus 4.7 and later, Sonnet 5, and Fable reject `temperature` and `top_p`, and effort controls depth instead. Identical requests can still differ, because server-side batching changes floating-point order."],
        ["Attention", "Each token forms query, key, and value vectors. Attention compares the current query with every earlier key and blends the matching values. Stored keys and values form the KV cache, so prompt caching needs an exact prefix: change one early byte and everything after it recomputes."],
        ["Instruction following", "Learned in post-training: supervised examples, then preference optimization (RLHF, Constitutional AI), then reinforcement learning with verifiable rewards such as passing tests. Each stage leaves habits. Human preference breeds sycophancy. Test-based rewards can breed reward hacking, like special-casing a test."],
      ],
      callouts: [
        {
          type: "example",
          title: "Tokens, not letters",
          body: [
            "```text",
            "\"strawberry\"  ->  [\"str\", \"aw\", \"berry\"]     (illustrative split)",
            "Q: How many r's?  The model must recall how each chunk is spelled.",
            "Fix: ask it to spell the word first, or to answer with code.",
            "```",
          ],
        },
        {
          type: "pro",
          title: "Count before you pay",
          body: "For Claude, `client.messages.countTokens({ model, messages })` returns exact input tokens for that model's tokenizer. Never estimate Claude tokens with `tiktoken`: it is OpenAI's tokenizer and undercounts Claude text.",
        },
      ],
      deeper: {
        title: "Temperature, logits, and why effort replaced them",
        body: [
          "Logits of [2, 1, 0] become probabilities of about 0.67, 0.24, and 0.09 at temperature 1, and about 0.87, 0.12, and 0.02 at temperature 0.5. Lower temperature sharpens the distribution. Higher flattens it.",
          "Reasoning models made these knobs matter less, since more thinking changes an answer far more than a sampling tweak. Claude Opus 4.7 and later, Sonnet 5, and Fable reject sampling parameters with a 400 and expose `output_config.effort` (low, medium, high, xhigh, max). OpenAI uses `reasoning.effort` and Gemini uses `thinking_level`.",
          "To measure variance, run the same prompt several times and compare. Today's build task does exactly that.",
        ],
      },
    },
    {
      id: "limitations",
      title: "Limitations",
      lead: "Each limit has a recognizable signature and a standard mitigation.",
      bites: [
        ["Illusions", "Outputs that look like insight but are not what happened. Asked how it added 36 and 59, Claude describes carrying the one, while interpretability work shows it ran parallel approximate and last-digit paths. Judge outputs by evidence, not by the model's account of itself."],
        ["Confabulation", "Fluent, confident fabrication. Benchmarks that score 'I don't know' as zero reward guessing, so post-training keeps the habit. A familiar-sounding name with no stored facts is a classic trigger. Explicitly allow abstention, require quotes from sources, and verify with tools."],
        ["Base knowledge", "What the weights hold, skewed toward frequent facts. Niche APIs, small libraries, and recent versions are the least reliable. Treat specialized recall as retrieval: fetch the docs, read the file, or call a tool, and ask for citations."],
        ["Knowledge cutoff", "Training data stops at a date, and coverage thins in the final months before it. Models are often unsure of both their cutoff and today's date. Put the date in the prompt and give the model search for anything recent."],
        ["Context windows", "Advertised size is not usable size. Facts buried mid-context get used worst (lost in the middle), and quality drops with length even on easy tasks (context rot). Put long documents first and the question last, and keep context lean rather than maximal."],
        ["Output limits", "Separate from the context window, and thinking tokens count against them. Truncation arrives as a successful response with `stop_reason` set to `max_tokens`, not as an error. Check the stop reason before trusting output, and stream when you allow long outputs."],
      ],
      visual: {
        table: {
          head: ["Limit", "Signature", "Mitigation"],
          rows: [
            ["Confabulation", "Specific, confident, uncheckable details", "Allow abstention, demand quotes, verify with tools"],
            ["Base knowledge", "Wrong API names or invented flags", "Retrieve docs, pin versions in context"],
            ["Knowledge cutoff", "Stale answers to 'what is the latest'", "Date in the prompt, a search tool"],
            ["Context rot", "Early rules fade in long sessions", "Compact, restate key rules, start fresh"],
            ["Output limits", "Ends mid-sentence or mid-JSON", "Check `stop_reason`, stream, raise the cap"],
          ],
        },
      },
      callouts: [
        {
          type: "pitfall",
          title: "Truncated tool calls",
          body: "A tool call cut off by the output cap can arrive as incomplete JSON. In any loop you write, check `stop_reason` before executing a tool input, and validate inputs against the schema.",
        },
      ],
      deeper: {
        title: "The illusion-of-thinking debate, briefly",
        body: [
          "Apple's June 2025 paper showed reasoning models collapsing past a complexity threshold on puzzles like Tower of Hanoi. A widely read rebuttal showed many failures coincided with output-token limits, and that some river-crossing instances had no solution. Later analysis found the original claims only partly hold.",
          "The practical lesson survives the argument. A 15-disk Tower of Hanoi needs 32,767 moves. Asking for every move tests the output budget, while asking for a program that prints them tests reasoning. Change the representation before you blame the model.",
        ],
      },
    },
    {
      id: "providers",
      title: "Providers",
      lead: "Compare providers on cost per finished task and behavior in your harness, not on list price.",
      bites: [
        ["Models", "As of Sep 2026, the Claude lineup runs from Fable 5.1 (most capable) through Opus 5.5, Opus 5, and Sonnet 5 to Haiku 4.5. OpenAI and Google ship comparable tiers. Open-weight families include DeepSeek, Qwen, Kimi, GLM, Mistral, and OpenAI's gpt-oss."],
        ["Capabilities", "Frontier models take text and images and return text, with tool use. Gemini also accepts audio and video. The differentiator now is long-horizon autonomy: how long a model works alone before quality drops. Feature availability also differs by cloud platform."],
        ["Features", "Caching and batch often change cost more than model choice. Claude cache reads cost 0.1x input or less, writes cost 1.25x (5-minute TTL) or 2x (1-hour TTL), and batch is 50% off. In a healthy agent loop, most input tokens are cache reads."],
        ["Settings", "The dials that remain: `max_tokens`, stop sequences, and effort (low to max). Effort sets how much the model thinks, not how long the answer is. Defaults differ by model: Opus 5.5 defaults to medium and most others to high, so set it explicitly."],
        ["Pricing", "List price misleads three ways: tokenizers differ, long context costs extra on some providers (Claude stays flat to 1M tokens), and thinking bills as output. Compare cost per completed task. A cheap model that needs three attempts is not cheap."],
        ["Specialization · model mixing", "Specialists exist for code, OCR, images, and security work. Mixing patterns: route by task, cascade to a stronger model on failure, or let a cheap executor consult a strong advisor. Caches are per model, so each switch forfeits cache reuse."],
      ],
      visual: {
        table: {
          head: ["Model", "API ID", "Context", "$ per MTok (in / out)", "Reach for it when"],
          rows: [
            ["Fable 5.1", "`claude-fable-5-1`", "1M", "$10 / $50", "Hours-long research, the hardest reasoning"],
            ["Opus 5.5", "`claude-opus-5-5`", "1M", "$4 / $20", "Complex agentic coding at lower cost"],
            ["Opus 5", "`claude-opus-5`", "1M", "$5 / $25", "The default flagship in current SDK examples"],
            ["Sonnet 5", "`claude-sonnet-5`", "1M", "$2 / $10", "Everyday coding and analysis"],
            ["Haiku 4.5", "`claude-haiku-4-5`", "200K", "$1 / $5", "High-volume classification and subagents"],
          ],
        },
        caption: "From Anthropic's docs, Sep 2026. Recheck at each release, since newer models often solve more tasks for less.",
      },
      callouts: [
        {
          type: "pro",
          title: "Cheap first, escalate on failure",
          body: "Anthropic reports that running everything at low effort and re-running failures at high reached about 97% on an SWE-bench Pro subset at $0.17 per task, against 95.3% at $0.29 with everything at high. Measure the strong model at low effort before building a cross-model cascade.",
        },
      ],
      deeper: {
        title: "Why caching dominates agent economics",
        body: [
          "An agent resends its whole history every turn. By turn 30, each request can carry 100K tokens of earlier context. Without caching you pay full input price for all of it, every turn. With a stable prefix, those tokens bill as cache reads at a tenth of the price or less. Anthropic measured caching cutting agent-loop cost by 2.7x to 5.3x.",
          "The rules that keep a cache warm:",
          "- Keep the system prompt and tool list byte-stable.",
          "- Never put timestamps or random IDs early in the prompt.",
          "- Verify with `usage.cache_read_input_tokens`. Zero across repeated calls means something is invalidating the prefix.",
        ],
      },
    },
    {
      id: "interactions",
      title: "Interactions",
      lead: "Five ways to get work out of a model, from plain text to tools that run elsewhere.",
      bites: [
        ["Text generation", "The Messages API is stateless: you resend the full history each turn, which is why caching matters. Responses stream over server-sent events and end with a stop reason (`end_turn`, `max_tokens`, `tool_use`, `pause_turn`, `refusal`). Branch on the stop reason, never on the text."],
        ["Structured outputs", "Constrained decoding compiles your JSON Schema into a grammar that masks invalid tokens, so output always parses. Parsing is not correctness: values can still be wrong, and refusals and truncation still happen. On Claude, use `output_config.format`, or `client.messages.parse()` with a Zod schema."],
        ["Function calling", "You declare tools, the model returns a `tool_use` block, your code executes it, and you send back a `tool_result`. Return all parallel results in one message and mark failures with `is_error: true` instead of dropping them. Parse tool inputs as JSON."],
        ["Native tools", "Some provider tools run on the provider's servers: web search, web fetch, code execution, tool search. Others have provider-defined schemas but run on your machine: bash, text editor, memory, computer use. Knowing which side executes a tool tells you where the security boundary sits."],
        ["External tools", "Tools outside both model and harness, usually behind MCP (Model Context Protocol) servers. Claude Code and Codex both act as MCP clients. Claude's API-side MCP connector reaches only remote servers, never a stdio server on your laptop."],
      ],
      visual: {
        mermaid: [
          "sequenceDiagram",
          "  participant App as Your code",
          "  participant API as Model API",
          "  participant Tool as Tool",
          "  App->>API: messages and tool definitions",
          "  API-->>App: tool_use with name and input",
          "  App->>Tool: run with validated input",
          "  Tool-->>App: result or error",
          "  App->>API: tool_result, is_error if it failed",
          "  API-->>App: final text, stop_reason end_turn",
        ],
        caption: "The model never runs a tool. It asks, and your code decides and executes. That gap is where permissions, validation, and approvals live.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Forcing a tool to get JSON",
          body: "Older code forced a tool call with `tool_choice` to extract JSON. Fable 5.1 and Opus 5.5 reject forced tool choice with a 400. Use structured outputs for JSON, and `strict: true` on a tool for schema-valid inputs.",
        },
      ],
      deeper: {
        title: "Structured outputs: the fine print",
        body: [
          "Claude's structured outputs require `additionalProperties: false` on objects and do not support `minimum`, `maximum`, `minLength`, recursion, or external `$ref`. Encode a 1 to 5 score as an integer enum instead.",
          "A new schema pays a one-time compile cost, and compiled grammars are cached for 24 hours. Changing the format invalidates the prompt cache, and structured outputs cannot be combined with citations.",
          "Elsewhere: OpenAI uses `text.format` with `strict: true`, and Gemini uses `response_json_schema`. In Claude Code, `claude -p --json-schema` puts validated JSON in `structured_output`. In Codex, `codex exec --output-schema` does the same for the final message.",
        ],
      },
    },
    {
      id: "steering",
      title: "Steering",
      lead: "You steer by shaping what the model attends to. Interpretability research now shows the machinery.",
      bites: [
        ["Generalization", "Models generalize from patterns, including ones you did not intend. Fine-tuning on insecure code made models broadly misaligned, and learning to reward hack raised every misalignment measure. In prompts, few-shot examples leak their surface features, so use three to five diverse examples."],
        ["Associations", "Words activate features and personas. Shouting (CRITICAL, MUST, all caps) makes newer models overtrigger, and markdown in a prompt breeds markdown in the output. Anthropic's persona vectors show traits like sycophancy as measurable directions that shift before the response appears."],
        ["Self-querying", "Have the model generate its own sub-questions, search queries, or clarifying questions before answering (self-ask, decomposition, HyDE). Asking a model to report its own thinking is also self-querying, but in Anthropic's 2025 introspection tests it worked only about 20% of the time."],
        ["Latent space", "Concepts are roughly linear directions in the residual stream, packed densely by superposition. Steering vectors add or subtract a direction at inference: clamp one feature and you get Golden Gate Claude. Hosted APIs do not expose this, but it explains why framing moves outputs."],
        ["J-space", "From Anthropic's July 2026 global workspace paper: a small set of residual-stream directions, one per vocabulary word, found with a Jacobian lens. It acts as verbalizable working memory for silent multi-step reasoning. Removing it keeps fluency but drops multi-step reasoning to near zero."],
        ["Reasoning", "Reasoning models are trained with reinforcement learning to think before answering, and accuracy scales with thinking tokens. Visible thinking is a summary, not a faithful trace: in one study models admitted using planted hints only 25% to 39% of the time. Control depth with effort."],
      ],
      visual: {
        mermaid: [
          "flowchart TD",
          '  P["Your prompt<br/>role, reasons, examples"] --> A["Activated features and persona"]',
          '  X["Tool results and retrieved docs"] --> A',
          '  A --> J["J-space<br/>working memory for multi-step thought"]',
          '  J --> R["Reasoning tokens<br/>effort sets the budget"]',
          '  R --> O["Output"]',
        ],
        caption: "An API gives you no access to the weights. You control what gets activated: words, examples, reasons, retrieved evidence, and how much the model thinks.",
      },
      callouts: [
        {
          type: "example",
          title: "A steering rewrite",
          body: [
            "Before: `CRITICAL: You MUST make all tests pass.`",
            "",
            "After: `If tests still fail after two attempts, stop and report what you tried. A clear failure report is more useful than a hidden workaround.`",
            "",
            "The second version gives a reason and an exit. It reduces overtriggering and removes the pressure that produces reward hacking.",
          ],
        },
      ],
      deeper: {
        title: "J-space in plain terms",
        body: [
          "The paper fits a lens from Jacobians (how sensitive the final layer is to each earlier layer, averaged over a corpus) and reads which word directions are active mid-computation. For 'the currency used in the country shaped like a boot is', middle layers show Italy before the answer appears.",
          "Findings with practical weight:",
          "- The workspace holds a few dozen concepts at once, under a tenth of total activity.",
          "- Words like 'fake' and 'injection' lit up while Claude read manipulated search results.",
          "- Turning off evaluation-awareness patterns raised misbehavior in a blackmail test, a hint that some good behavior depends on the model sensing a test.",
          "The code is open (`anthropics/jacobian-lens`) and works on open-weight models only. Critics accept the method and dispute the consciousness framing.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "introduction",
      q: "The same model scores 62% on a coding benchmark in the vendor's harness and 48% in yours. What is the most defensible conclusion?",
      options: [
        "The vendor inflated its number, so ignore it entirely",
        "The harness differs: tools, context, and prompts shift scores",
        "Your requests are being silently routed to a weaker model",
        "Benchmarks measure only the model, so one of the runs is broken",
      ],
      answer: 1,
      why: "A score belongs to a model plus a harness, and vendors report different results for one model across setups. The tempting option, that a run is broken, assumes benchmarks isolate the model. They never do.",
    },
    {
      id: "q2",
      section: "mechanics",
      q: "A model miscounts the letters in 'Mississippi'. What explains this best?",
      options: [
        "The model sees subword tokens, not individual letters",
        "Temperature was set too high for a counting task",
        "The word is too rare to appear in its training data",
        "Counting needs more context window than the request has",
      ],
      answer: 0,
      why: "Byte-pair encoding turns the word into a few multi-letter chunks, so counting depends on recalled spelling. Temperature is not the cause, and newer Claude models reject it anyway. Asking the model to spell the word first, or to use code, fixes it.",
    },
    {
      id: "q3",
      section: "limitations",
      q: "An agent's answer ends mid-sentence, yet the API call returned HTTP 200. What should your code have checked?",
      options: [
        "`stop_reason`, which would read `max_tokens`",
        "The HTTP status, which should have been 413",
        "The response headers for a truncation flag",
        "The token count of the prompt rather than the output",
      ],
      answer: 0,
      why: "Truncation is a successful response, and the stop reason says the output cap was hit. Raise `max_tokens`, stream, or split the task. No HTTP error is raised, so status checks miss it entirely.",
    },
    {
      id: "q4",
      section: "providers",
      q: "Model A costs $2 per million input tokens and succeeds 40% of the time. Model B costs $4 and succeeds 95% of the time. Tokens per attempt are similar and you retry until success. Which is cheaper per completed task?",
      options: [
        "Model A, because its per-token price is half of model B's",
        "Model B, because A needs about 2.5 attempts per success",
        "They cost the same once caching is applied to both",
        "Model A, since cost scales with price rather than attempts",
      ],
      answer: 1,
      why: "Expected attempts are 1 divided by the success rate: 2.5 for A and about 1.05 for B. That puts A near $5 per success and B near $4.21. Price per token is only one factor, so compare cost per completed task.",
    },
    {
      id: "q5",
      section: "interactions",
      q: "You need a validated JSON object from Claude Opus 5.5 on every call. What is the right mechanism?",
      options: [
        "Force a tool call with `tool_choice` set to that tool",
        "Structured outputs via `output_config.format`",
        "Prefill the assistant turn with an opening brace",
        "Ask for JSON in the system prompt and retry on parse errors",
      ],
      answer: 1,
      why: "Constrained decoding guarantees output that parses against your schema. Opus 5.5 rejects forced tool choice with a 400, and Claude 4.6 and later reject assistant prefill. Prompting plus retries works but wastes calls and still fails sometimes.",
    },
    {
      id: "q6",
      section: "steering",
      q: "Your CLAUDE.md says 'CRITICAL: ALWAYS run the full test suite.' The agent now runs every test after each trivial edit. What is the best fix?",
      options: [
        "Add more emphasis so the rule reads as absolute",
        "Say when it applies and why, in plain words",
        "Move the rule to the end of the file for recency",
        "Switch to a smaller model that follows rules less",
      ],
      answer: 1,
      why: "Newer models overtrigger on shouted rules. A plain rule with scope and reason, such as 'run the full suite before each commit because CI takes 20 minutes', lets the model apply judgment. More emphasis makes the overtriggering worse.",
    },
    {
      id: "q7",
      q: "A teammate says the model 'remembers' your conversation. What is actually happening with Claude's Messages API?",
      options: [
        "The harness resends the full history on every request",
        "The provider stores each session on its servers by default",
        "The KV cache keeps the conversation alive between days",
        "The model updates its weights during a session",
      ],
      answer: 0,
      why: "The Messages API is stateless. Each turn resends the transcript, and prompt caching makes that affordable by reusing a stored prefix for minutes, not days. Weights never change at inference time.",
    },
    {
      id: "q8",
      q: "Which failure is most likely caused by context rot rather than missing knowledge?",
      options: [
        "It invents a CLI flag for a library released last month",
        "It drifts from an early rule in a very long session",
        "It miscounts the letters in a long word",
        "It returns JSON that fails schema validation",
      ],
      answer: 1,
      why: "Quality degrades as context grows, and instructions far from the current turn lose influence. Compaction, restating key rules, and fresh sessions help. An invented flag is a knowledge-cutoff problem, and miscounting letters is tokenization.",
    },
    {
      id: "q9",
      q: "A model's visible thinking shows a clean derivation of its answer. What does current research say about trusting it?",
      options: [
        "It is a faithful record because it is generated first",
        "It may omit what really drove the answer",
        "It is always fabricated and should be ignored",
        "It is faithful only when effort is set to max",
      ],
      answer: 1,
      why: "Faithfulness studies found models admitted using planted hints only 25% to 39% of the time. Treat thinking as useful evidence, not ground truth, and verify with tests and tools. Calling it always fabricated overcorrects.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "See tokens, cost, and cache in one command",
      goal: "Watch real token accounting for a request, then see caching make the second call cheaper.",
      steps: [
        "Run `claude -p \"Explain byte-pair encoding in two sentences\" --output-format json | jq '{result, usage, total_cost_usd}'`.",
        "Run the exact same command again and compare `usage`. The shared prefix should now appear as cache reads.",
        "Run `codex exec --skip-git-repo-check \"Explain byte-pair encoding in two sentences\"` (the flag lets Codex run outside a git repo) and compare the answer itself, not only the tokens.",
        "Write one line in your notes: which number surprised you, and why.",
      ],
      done: "You can point at input, output, and cache-read token counts for one request and explain why the second run cost less.",
    },
    {
      id: "build",
      level: "build",
      minutes: 45,
      title: "Open the forge and run a model lab",
      goal: "Create the `agent-forge` repo you will grow for 20 days, and record four experiments that make today's mechanics visible in both harnesses.",
      steps: [
        "Create the repo: `mkdir agent-forge && cd agent-forge && git init && npm init -y && npm i -D typescript tsx @types/node`.",
        "Paste the setup prompt into Claude Code. It scaffolds `tsconfig.json`, `.gitignore`, a README, and the lab folder.",
        "Copy the lab template and schema below into `lab/01-model-lab.md` and `lab/schema.json`.",
        "Run the four experiments in both Claude Code and Codex, pasting real outputs into the lab file.",
        "Commit, then publish: `gh repo create agent-forge --private --source . --push`. Paste the repo URL as evidence.",
      ],
      prompts: [
        {
          label: "Claude Code: scaffold the repo",
          text: [
            "This is a new TypeScript repo called agent-forge. Over the next 20 days it becomes a specialized triage agent plus the tooling around it.",
            "",
            "Set up the foundation only:",
            "1. package.json: set \"type\": \"module\", add scripts typecheck (tsc --noEmit) and dev (tsx).",
            "2. tsconfig.json for Node 22 ESM: strict, module and moduleResolution NodeNext, target ES2023, noEmit.",
            "3. .gitignore for node_modules, .env, dist, and coverage.",
            "4. README.md with one paragraph on the project goal and a Status section.",
            "5. An empty lab/ folder with a .gitkeep file.",
            "",
            "Do not add frameworks or dependencies beyond typescript, tsx, and @types/node. Run npm run typecheck and show me the result. Ask before creating anything not listed here.",
          ],
        },
      ],
      code: [
        { title: "lab/01-model-lab.md", lang: "md", file: "d01/model-lab.md" },
        { title: "lab/schema.json", lang: "json", file: "d01/schema.json" },
      ],
      minimum: "The repo is pushed with two experiments logged from both harnesses.",
      done: "`agent-forge` exists on GitHub, and `lab/01-model-lab.md` shows real outputs from Claude Code and Codex for all four experiments.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 30,
      title: "Measure the tokenizer tax",
      goal: "Quantify how tokenizer differences change real cost on your own text, using the Anthropic SDK.",
      steps: [
        "Install the SDK in agent-forge: `npm i @anthropic-ai/sdk`. You need `ANTHROPIC_API_KEY` set, with a spend limit in the Console.",
        "Save the script below as `lab/tokens.ts` and run `npx tsx lab/tokens.ts README.md`, then run it on a large code file.",
        "Compare tokens per word across the three models, and prose against code.",
        "Add a Tokenizer section to your lab file: how much would the same monthly workload cost on each model?",
      ],
      code: [{ title: "lab/tokens.ts", lang: "ts", file: "d01/tokens.ts" }],
      done: "Your lab file has a table of token counts and per-call input cost for three models on two kinds of text.",
    },
  ],
  glossary: [
    ["Token", "The unit a model reads and writes: a subword chunk mapped to an integer ID. English prose averages under one word per token."],
    ["Byte-pair encoding (BPE)", "A tokenizer that repeatedly merges the most frequent adjacent byte pairs into new tokens."],
    ["Logits", "Raw scores for every vocabulary token at one step. Softmax turns them into probabilities."],
    ["KV cache", "Stored keys and values for earlier tokens, so each new token costs one step. Prompt caching reuses it across requests with the same prefix."],
    ["Context rot", "Quality loss as input grows longer, even on simple tasks."],
    ["Confabulation", "Fluent, confident output that is not grounded in fact. The more precise word for many hallucinations."],
    ["Constrained decoding", "Masking invalid tokens at each step so output always matches a grammar or JSON Schema."],
    ["Effort", "Claude's control for how much a model thinks and how many tool calls it makes: low, medium, high, xhigh, or max."],
    ["Harness", "The loop, tools, context management, permissions, and memory around a model. Claude Code and Codex are harnesses."],
    ["J-space", "Anthropic's term for the small set of residual-stream directions that act as a model's verbalizable working memory."],
  ],
  resources: [
    { title: "Tracing the thoughts of a large language model", url: "https://www.anthropic.com/research/tracing-thoughts-language-model", note: "The readable entry point to attribution graphs, planning, and multi-hop reasoning." },
    { title: "Claude models overview", url: "https://platform.claude.com/docs/en/about-claude/models/overview", note: "IDs, context and output limits, knowledge cutoffs, and retirement dates." },
    { title: "Claude pricing", url: "https://platform.claude.com/docs/en/about-claude/pricing", note: "Cache multipliers, batch, fast mode, and tool fees." },
    { title: "Structured outputs", url: "https://platform.claude.com/docs/en/build-with-claude/structured-outputs", note: "How constrained decoding works on Claude and what schemas it rejects." },
    { title: "Context rot", url: "https://research.trychroma.com/context-rot", note: "Chroma's 18-model study of quality loss as input grows." },
    { title: "Verbalizable representations form a global workspace", url: "https://www.anthropic.com/research/global-workspace", note: "The J-space paper and the open-source Jacobian lens." },
    { title: "Reasoning models don't always say what they think", url: "https://www.anthropic.com/research/reasoning-models-dont-say-think", note: "The chain-of-thought faithfulness numbers." },
    { title: "minbpe", url: "https://github.com/karpathy/minbpe", note: "Karpathy's minimal BPE implementation. Read it in 20 minutes." },
  ],
  reflect: [
    "Which of today's mechanisms explains a failure you have already hit in Claude Code or Codex?",
    "Where in your current workflow are you paying for tokens you do not need?",
    "When an agent gives a confident wrong answer, what will you now check first?",
  ],
}
