export default {
  day: 6,
  hook: "Claude Code and Codex hide a loop that decides when tools run, when work stops and what you pay. Write that loop yourself once and every harness becomes readable.",
  anchor: "You already watch Claude Code and Codex call tools, ask permission and stop, and you correct them when they drift.",
  plusOne: "Today you write the loop they run, so stop reasons, permissions and cache hits become code you own.",
  tldr: [
    "An agent is a loop: call the model, run the tools it asks for, append results, stop on a condition you check.",
    "The model proposes. Your runtime enforces permissions, sandboxes, budgets and persistence, so anything that must hold belongs there, not in the prompt.",
    "Loops resend everything each turn. A byte-stable prefix turns most of that input into cache reads at a tenth of the price or less.",
  ],
  outcomes: [
    "Write a tool-use loop that handles every stop reason and enforces turn, token and dollar limits",
    "Move rules that must hold from instruction files into permissions, sandboxes and code in both harnesses",
    "Keep a loop's prompt cache warm and prove it from usage fields",
  ],
  minutes: { learn: 25, practice: 75 },
  map: {
    title: "One turn of an agent loop",
    mermaid: [
      "flowchart LR",
      '  T["System prompt, tools, transcript"] --> C["Model call"]',
      '  C --> R{"stop_reason"}',
      '  R -->|"tool_use"| P["Permission and input check"]',
      '  P -->|"allowed"| X["Run tool"]',
      '  P -->|"denied"| E["Error result with a next step"]',
      '  X --> A["Append all tool_results"]',
      '  E --> A',
      '  A -->|"budget left"| C',
      '  R -->|"end_turn"| D["Done"]',
      '  R -->|"max_tokens or refusal"| H["Stop and report"]',
    ],
    caption: "The model only fills the stop_reason diamond. Every other box is your code, which is why one model behaves differently in different harnesses.",
  },
  sections: [
    {
      id: "agent-loop",
      title: "Agent Loop",
      lead: "Six moving parts, and the model owns one of them.",
      bites: [
        ["Model calls", "Every turn resends the system prompt, tool definitions and the whole transcript, because the Messages API keeps no state. Turn 30 pays for turn 1's context again. Caching makes that cheap, but only while every earlier byte stays identical."],
        ["Tool execution", "A `tool_use` block is a request, not an action. Your code finds the tool, validates the input, checks permission, runs it and times it. Return every result from one turn in a single user message, or the model learns to stop calling tools in parallel."],
        ["Results", "The `tool_result` is the model's only evidence of what happened. Return compact, specific text and mark failures `is_error: true` with a next step. A vague 'failed' invites a blind retry, and an empty result invites the model to invent the outcome."],
        ["State", "The transcript is the loop's state, and it lives in your process, not at the provider. Write it to disk each turn as JSONL and a run becomes resumable, replayable and auditable. Keep it only in memory and a crash costs the whole run."],
        ["Stopping conditions", "Branch on `stop_reason`, never on reply text. `end_turn` is done, `tool_use` continues, `max_tokens` is truncation, `pause_turn` means resend so a server tool can finish, and `refusal` means stop and escalate. Add caps the API cannot know: turns, tokens and dollars."],
        ["Runtime responsibilities", "The model proposes and the runtime disposes. Permissions, sandboxing, retries, compaction, caching, persistence and budgets are all harness code. That is why one model behaves differently in Claude Code, in Codex and in your 150-line loop."],
      ],
      visual: {
        table: {
          head: ["`stop_reason`", "What happened", "What the loop does"],
          rows: [
            ["`end_turn`", "The model finished", "Stop and report success"],
            ["`tool_use`", "It wants tools run", "Validate, run, append all results, continue"],
            ["`max_tokens`", "Output hit your cap", "Never run a cut-off tool call. Raise the cap or stop"],
            ["`pause_turn`", "A server tool paused a long turn", "Append the content unchanged and resend"],
            ["`refusal`", "A safety classifier declined", "Stop, log `stop_details`, route to a human"],
            ["`model_context_window_exceeded`", "The context window is full", "Compact, or restart from a summary"],
            ["`stop_sequence`", "A custom stop string matched", "Treat it as done"],
          ],
        },
        caption: "Every row arrives as HTTP 200. Your loop, not an exception handler, decides what happens next.",
      },
      callouts: [
        {
          type: "pro",
          title: "Budget in three units",
          body: "Cap turns (runaway loops), tokens (context growth) and dollars (what you actually care about). The Agent SDK has `maxTurns` and `maxBudgetUsd`, and `claude -p` has `--max-turns` and `--max-budget-usd`. Codex reports tokens rather than dollars: `codex exec --json` emits usage on every `turn.completed` event, and `/goal` accepts a token budget.",
        },
        {
          type: "pitfall",
          title: "The polite infinite loop",
          body: "A list tool that returns the same page on every call, or an error the model cannot fix, repeats until something stops it. Without a turn cap that something is your budget. Make list results say when nothing is left, and put a concrete next step in every error.",
        },
      ],
      deeper: {
        title: "What Claude Code's loop adds on top of yours",
        body: [
          "Your 150 lines cover the core. Claude Code layers on, in order of how often they matter:",
          "- A permission pipeline: hooks, deny rules, ask rules, the permission mode, allow rules, then `canUseTool`.",
          "- Read-only tools run in parallel and mutating tools run one at a time.",
          "- Output caps: MCP results warn at 10,000 tokens and cap at 25,000 with the overflow saved to a file. Bash output inline is about 30,000 characters.",
          "- Auto-compaction near the context limit, and Stop hooks that can force another turn (overridden after 8 consecutive blocks).",
          "- `/goal`, where a fast model checks a completion condition after each turn.",
          "Codex layers the same kinds of controls: approval policy, sandbox, hooks, compaction thresholds and its own `/goal`.",
          "The contrarian reading: much of this compensates for model weaknesses. Anthropic has removed harness parts as models improved, so every layer you copy deserves a comment naming the weakness it covers.",
        ],
      },
    },
    {
      id: "instructions",
      title: "Instructions",
      lead: "Instructions change what the model tries. Only enforcement changes what it can do.",
      bites: [
        ["Purpose", "Open with the job and who consumes the output: 'You turn feedback into triage records a PM reviews.' A stated purpose lets the model handle cases your rules never listed, because it can reason from the goal instead of matching prohibitions."],
        ["Responsibilities", "State what the agent owns and what it hands back. Triage classifies and drafts, and a human decides what ships. Naming non-responsibilities stops helpful overreach, such as an agent that fixes the bug it was only asked to file."],
        ["Profiles", "A profile bundles instructions, tools, model and permissions for one role. Claude Code has no profile switcher, so use `--agent`, a subagent file or `--settings`. Codex layers `~/.codex/NAME.config.toml` with `-p NAME`, and legacy `[profiles]` tables are now rejected."],
        ["Configuration", "Where an instruction lives decides when it loads and what it costs: the system prompt every turn, `CLAUDE.md` and `AGENTS.md` at session start, skills on demand, hook output at events. Both harnesses inject instruction files as user messages, not as system prompt."],
        ["Behavioral guidance", "Guidance with a reason generalizes: 'Set needsHuman for anything about money, because refunds need a person.' Use plain language, diverse examples and no shouting. Even good guidance holds most of the time, not every time, and that ceiling is the case for the next bite."],
        ["Enforced boundaries", "What must hold goes where the model cannot argue with it: the tool list, permission rules, hooks, the sandbox and schema validation in code. `CLAUDE.md` and `AGENTS.md` are context. A deny rule, a Codex sandbox mode or a missing tool is enforcement."],
      ],
      visual: {
        table: {
          head: ["Rule", "Advisory version", "Enforced version"],
          rows: [
            ["Never read `.env`", "'Do not open .env' in `CLAUDE.md`", "`\"deny\": [\"Read(./.env)\"]` in `.claude/settings.json`"],
            ["Only triage tools", "'Use only list_feedback and save_triage'", "Send only those two tools in the request"],
            ["Valid records", "'Return JSON with these fields'", "`strict: true` plus Zod validation before saving"],
            ["No writes outside the repo", "'Stay in the repo' in `AGENTS.md`", "Codex `sandbox_mode = \"workspace-write\"`"],
            ["Tests before commit", "'Always run the tests'", "A PreToolUse hook on `git commit` plus a required CI check"],
          ],
        },
        caption: "Keep both columns. The left explains intent so the model cooperates. The right holds when it does not.",
      },
      callouts: [
        {
          type: "example",
          title: "One boundary in both harnesses",
          body: [
            "```json .claude/settings.json",
            '{ "permissions": { "deny": ["Read(./.env)", "Bash(curl *)"], "ask": ["Bash(git push *)"] } }',
            "```",
            "```toml ~/.codex/forge.config.toml (run with codex -p forge)",
            'approval_policy = "on-request"',
            'sandbox_mode = "workspace-write"',
            "```",
            "Claude Code judges each tool call against rules. Codex confines the whole process: in `workspace-write`, `.git` stays read-only and the network stays off unless you enable it.",
          ],
        },
      ],
      deeper: {
        title: "Why the system prompt is not a security boundary",
        body: [
          "System prompt, instruction files and tool results all become tokens in one context. Training gives the system prompt more weight, but nothing enforces it, so text inside a tool result can still steer the model.",
          "Two mitigations exist. On the API, Opus 5.x and Fable 5.x accept a mid-conversation `role: \"system\"` message, an operator channel that tool output cannot forge. In Claude Code, subagent reports are labeled as carrying no user authority.",
          "Neither makes it safe to hand a persuadable model a dangerous tool. Design so that a fully persuaded model still cannot do damage: no tool that sends email, no writes outside `data/`, and a human gate on anything irreversible. Day 10 turns this into a counting rule you can apply to any agent.",
        ],
      },
    },
    {
      id: "context-memory",
      title: "Context and Memory",
      lead: "Everything the model knows this turn is in the request. You decide what enters and in what order.",
      bites: [
        ["Messages", "Alternating user and assistant turns, with tool results riding in user messages. Keep history append-only: rewriting an old turn misses the cache from that point, and on Fable 5.1 and Opus 5.5 it can also invalidate earlier thinking blocks."],
        ["Metadata", "Harnesses add facts you never typed: working directory, OS, git status, date, memory paths. Claude Code snapshots git status at startup, so caches never match across worktrees. `/context` in Claude Code and `codex debug prompt-input` in Codex show what was injected."],
        ["Attachments", "Files, images and PDFs become tokens like any text. The Files API gives a reusable `file_id`, but every read still bills, and large images are downscaled. When the agent can read files itself, pass a path instead of the contents."],
        ["Environmental awareness", "An agent knows only what it is shown or can probe. Claude Code's auto mode trusts the cwd and git remotes present at start, not ones added later. Tell your loop where data lives and what is out of scope, after the cached prefix."],
        ["Persistence · retrieval", "The model keeps nothing between requests. Persistence is files you write, such as instruction files, auto memory's `MEMORY.md` or a JSONL transcript. Retrieval is how they return: loaded at start, grepped on demand, or fetched by a tool. Codex memories are off by default."],
        ["Context injection", "Adding facts mid-run without breaking the cache. Claude Code hooks return `additionalContext` (capped at 10,000 characters) as a system reminder, and Codex hooks mirror the same JSON output shape. On the API, Opus 5.x takes a `role: \"system\"` message after the cached history."],
        ["Prompt caching", "In a loop, mark the system block and add top-level `cache_control` for the moving tail. Each turn then reads the whole prior prefix and writes only the new turn. A model switch, a changed tool list or an early timestamp resets everything after it."],
      ],
      visual: {
        mermaid: [
          "flowchart LR",
          '  T["tools<br/>byte-stable"] --> S["system prompt<br/>breakpoint 1"]',
          '  S --> H["turns 1 to n-1<br/>read from cache"]',
          '  H --> N["turn n<br/>moving breakpoint"]',
          '  N --> Q["next request<br/>reads all of it"]',
        ],
        caption: "Render order is tools, then system, then messages. A byte change in any box invalidates that box and everything to its right.",
      },
      callouts: [
        {
          type: "example",
          title: "The healthy-loop signature (illustrative numbers)",
          body: [
            "```text",
            "turn 1   input 3,210   cache_write 3,180   cache_read 0",
            "turn 2   input 42      cache_write 610     cache_read 3,180",
            "turn 3   input 38      cache_write 540     cache_read 3,790",
            "```",
            "Reads grow and writes stay small. If writes stay near the full prompt size every turn, something upstream of the breakpoint changes between requests.",
          ],
        },
        {
          type: "pitfall",
          title: "Silent minimums",
          body: "A prefix shorter than the model's minimum never caches and raises no error: 512 tokens on Opus 5 and 4,096 on Haiku 4.5, as of Sep 2026. The same triage prompt caches on Opus 5 and silently does not on Haiku, so check `cache_creation_input_tokens` after every model change.",
        },
      ],
      deeper: {
        title: "Cache math for a 30-turn loop",
        body: [
          "Take a 20,000-token stable prefix on Opus 5 ($5 per million input tokens, writes at 1.25x, reads at 0.1x).",
          "- No caching: 30 turns × 20,000 tokens = 600,000 tokens, about $3.00.",
          "- Caching: one write ($0.125) plus 29 reads ($0.29), about $0.42.",
          "That is roughly 7x on the prefix alone, before the growing transcript gets the same treatment. Manus reports agents running near 100 input tokens per output token and calls cache hit rate the most important metric for a production agent.",
          "The rules that keep it warm: append-only history, deterministic serialization (sorted keys, stable tool order), no timestamps or run ids before the last breakpoint, and hide unused tools rather than removing them. Claude Code caches the main conversation for an hour on a subscription within plan limits and for 5 minutes otherwise.",
        ],
      },
    },
    {
      id: "tools",
      title: "Tools",
      lead: "Tools are the agent's hands. Which side executes each one decides where your security boundary sits.",
      bites: [
        ["Available actions", "The tool list is the agent's action space: the model cannot call what the request does not contain. Removing a tool beats any rule about it. In Claude Code, `--tools` and the SDK's `tools: []` remove built-ins, while `allowedTools` only pre-approves."],
        ["Function calling", "You send names, descriptions and JSON Schemas, the model returns `tool_use` with arguments, and you send back `tool_result`. `strict: true` guarantees schema-valid arguments, not true ones, so check meaning in code: does this feedback id exist?"],
        ["Bash", "One tool covering thousands of actions: powerful and hard to govern. Claude Code runs each command as its own process and checks compound commands part by part. Codex runs them inside its sandbox. When the action set is known, a narrow tool is safer."],
        ["Browser use", "Claude in Chrome drives your real browser with your logins, and Claude Code Desktop and the Codex desktop app each have a built-in browser. A logged-in browser is the widest exfiltration channel you own, so point agents at test accounts and local origins."],
        ["Code execution", "Where code runs is the question. Claude Code and Codex run it on your machine. The API code execution tool runs Python and bash in an Anthropic container, and programmatic tool calling lets that code call your tools so bulky intermediate data skips the context."],
        ["Filesystems", "Files are the cheapest shared memory between turns, tools and agents. Claude Code path rules use `//abs`, `~/` and `./` prefixes, and a `Read` deny also blocks edits. Codex keeps `.git`, `.codex` and `.agents` read-only even in `workspace-write`. Validate every model-supplied path."],
        ["Permissions", "Claude Code checks deny, then ask, then allow, and the first match wins regardless of specificity. Codex sets `approval_policy` to `on-request` (the default), `never` or granular per-category rules, and `codex exec` always runs with `never`. Both judge a call by pattern before it runs."],
        ["Sandboxing", "An OS sandbox limits files and network for a process and all its children, whatever the command text says. Claude Code uses Seatbelt on macOS and bubblewrap on Linux with a proxy that pre-allows no domains. Codex uses the same mechanisms, with network off in `workspace-write`."],
      ],
      visual: {
        table: {
          head: ["Tool", "Runs on", "Your boundary"],
          rows: [
            ["Your own tools (`save_triage`)", "Your process", "Input validation and the tool list"],
            ["Claude Code Bash, Read, Edit", "Your machine", "Permission rules, hooks, OS sandbox"],
            ["Codex shell and `apply_patch`", "Your machine", "Sandbox mode, approval policy, exec-policy rules"],
            ["API code execution, web fetch", "Anthropic servers", "Tool settings and what you put in context"],
            ["Claude in Chrome", "Your logged-in browser", "Site permissions and test accounts"],
          ],
        },
        caption: "Knowing which side executes a tool tells you which layer can stop it.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Command patterns are not a boundary",
          body: "`Bash(git push *)` misses `git -C . push`, a `curl` deny misses `sh -c`, and `Bash(git * main)` matches every git subcommand, including `-c` program execution. Patterns are good for prompting less. For anything that must never happen, add the OS sandbox and an egress allowlist.",
        },
        {
          type: "pitfall",
          title: "Strict mode speaks a subset of JSON Schema",
          body: "Strict tools reject `minimum`, `maximum`, `minLength` and `maxLength`, and Zod 4's `z.toJSONSchema()` adds integer bounds for every `.int()`. Strip those keys before sending, as today's `src/loop.ts` does, and keep the full rules in Zod where your code enforces them.",
        },
      ],
      deeper: {
        title: "An approval prompt is a classifier with a 93% yes rate",
        body: [
          "Anthropic found users approved 93% of Claude Code permission prompts. At that rate a prompt trains the human to click yes, and it protects least on the day it matters. The OS sandbox cut prompts by 84% while making the boundary stronger, because it limits what a process can reach rather than asking about each command.",
          "Auto mode adds a classifier in front of the sandbox. Anthropic measured 0.4% false positives on real actions and 17% false negatives on real overeager ones, and says so plainly. Its containment write-up describes a phish, arriving through the user, that only filesystem and egress boundaries would have stopped.",
          "A practical order for any agent you build: sandbox with an egress allowlist first, narrow tools second, approvals only for the irreversible remainder. Codex follows the same logic with `--approve-for-me`, which sends escalations to an auto-review subagent while `workspace-write` holds the line.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "agent-loop",
      q: "Your loop runs every `tool_use` block it finds. One run saved a TriageResult with an empty rationale, and every API call returned HTTP 200. What most likely happened?",
      options: [
        "The response stopped at `max_tokens` and the loop ran a truncated call",
        "Prompt caching replayed an older copy of the tool schema from a previous run",
        "The context window filled up and the model silently dropped the schema",
        "The previous `tool_result` was marked `is_error` and confused the next turn",
      ],
      answer: 0,
      why: "A truncated turn is still a 200 with `stop_reason: \"max_tokens\"`, and the SDK can parse the partial input into a valid-looking object. Check the stop reason before running tools. Caching reuses the prompt prefix only and never changes what the model generates.",
    },
    {
      id: "q2",
      section: "instructions",
      q: "`AGENTS.md` says 'Never push to main.' During a long session, Codex pushes to main anyway. What is the durable fix?",
      options: [
        "Repeat the rule in capital letters at the top of AGENTS.md so it cannot be overlooked",
        "Enforce it with branch protection and Codex's sandbox and approval settings",
        "Move the rule into a skill so it loads fresh whenever git comes up",
        "Switch Codex to a larger model that follows instructions more reliably",
      ],
      answer: 1,
      why: "Instructions are context and hold most of the time, not always. Branch protection on the server, plus a sandbox that keeps `.git` read-only and the network off, makes the push impossible whatever the model decides. Extra emphasis tends to cause overtriggering, not compliance.",
    },
    {
      id: "q3",
      section: "context-memory",
      q: "Your loop on Haiku 4.5 shows `cache_read_input_tokens: 0` on every turn. The system prompt and tools never change, and turns are seconds apart. What explains it?",
      options: [
        "The cached prefix is shorter than Haiku 4.5's 4,096-token minimum",
        "Top-level `cache_control` only caches the first request of a conversation",
        "Cache reads are not reported on turns that carry tool results",
        "The 5-minute cache lifetime resets whenever a tool runs between turns",
      ],
      answer: 0,
      why: "Below a model's minimum cacheable prefix, caching silently does nothing: 4,096 tokens on Haiku 4.5 against 512 on Opus 5 (as of Sep 2026). Running a tool does not reset the lifetime, and reads are reported on every turn. Check `cache_creation_input_tokens` after each model change.",
    },
    {
      id: "q4",
      section: "tools",
      q: "You deny `Bash(curl *)` in `.claude/settings.json`, yet the agent still reaches an external host. What is the most likely explanation?",
      options: [
        "It ran `sh -c` or another tool that the pattern never matched",
        "Deny rules in project settings wait for workspace trust before applying",
        "A broader allow rule elsewhere overrode the narrower deny rule",
        "Deny rules only apply in auto mode, not in the default Manual mode",
      ],
      answer: 0,
      why: "Command patterns match text, so `sh -c \"curl ...\"` or a different network tool slips past. Deny rules apply immediately, in every mode, and always beat allow rules. The fix is an OS sandbox with a domain allowlist, which limits the process whatever the command says.",
    },
    {
      id: "q5",
      q: "Two teams run the same model with nearly identical prompts. Team A's agent is far more reliable. Where should Team B look first?",
      options: [
        "The runtime: tool results, input validation, stop handling and budgets",
        "The sampling temperature, which Team A has probably tuned much lower",
        "The provider region, since latency differences change model quality",
        "The system prompt length, since shorter prompts always follow instructions better",
      ],
      answer: 0,
      why: "The model proposes and the runtime decides what happens next, so result quality, validation and stop handling separate reliable agents from flaky ones. Current Claude models reject `temperature` outright, and region changes latency, not capability.",
    },
    {
      id: "q6",
      q: "Triage must never write outside `data/`. Which control guarantees it?",
      options: [
        "A system prompt line explaining that every write belongs in `data/`",
        "Tool code that resolves each path and rejects anything outside `data/`",
        "A PostToolUse hook that logs every write so you can review it later",
        "Asking the model to state the target path and confirm it before writing",
      ],
      answer: 1,
      why: "Only a check that runs before the side effect, in code the model cannot bypass, guarantees the rule. A PostToolUse hook fires after the write has happened, and a prompt line or a confirmation step still depends on the model complying.",
    },
    {
      id: "q7",
      q: "A 30-turn run costs about ten times what you estimated from its first turn. What most likely explains it?",
      options: [
        "Each turn resends the growing transcript, and none of it was cached",
        "Tool results bill at the output rate because the model must process them",
        "The API adds a per-turn fee to any request that includes tools",
        "Tool definitions bill at full price on every turn even when cached",
      ],
      answer: 0,
      why: "The Messages API is stateless, so turn 30 carries everything from turns 1 to 29. Without caching, that prefix bills at full input price every turn. Tool results bill as input, and cached tool definitions bill as cheap reads.",
    },
    {
      id: "q8",
      q: "After a web search call, your loop gets `stop_reason: \"pause_turn\"`. What should it do?",
      options: [
        "Append the assistant content unchanged and send the request again",
        "Treat it as `end_turn` and return the partial answer to the user",
        "Retry the same request without the assistant content it just returned",
        "Raise `max_tokens` and restart the conversation from the first message",
      ],
      answer: 0,
      why: "`pause_turn` means a server tool paused a long turn. Sending the paused content back lets the model continue where it stopped. Dropping that content repeats work, and treating the pause as done returns an unfinished answer.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "Make a harness stop on purpose",
      goal: "See the stop conditions Claude Code enforces for you, and what Codex reports, before you write your own.",
      steps: [
        "In any repo, run `claude -p \"Summarize every TypeScript file here, one line each\" --max-turns 1 --output-format json | jq '{subtype, num_turns, total_cost_usd}'`. Expect `error_max_turns`.",
        "Run it again with `--max-budget-usd 0.01` instead of the turn cap and look for `error_max_budget_usd`.",
        "Run the same task in Codex with no cap: `codex exec --json \"Summarize every TypeScript file here, one line each\" | jq -c 'select(.type==\"turn.completed\") | .usage'`. Codex reports tokens, not dollars.",
        "Write one line in your notes: which cap would you want that neither harness gives you by default?",
      ],
      done: "You have seen both error subtypes and a Codex usage line, and you can say which caps each harness enforces.",
    },
    {
      id: "build",
      level: "build",
      minutes: 75,
      title: "Write the raw agent loop",
      goal: "Build `src/loop.ts`, a manual tool-use loop on the Anthropic SDK, so every decision Claude Code usually makes for you becomes code you can read and change.",
      steps: [
        "Set a monthly spend limit in the Claude Console, export `ANTHROPIC_API_KEY`, then run `npm i @anthropic-ai/sdk zod` in agent-forge.",
        "Copy the four files below to `src/models.ts`, `src/tools/spec.ts`, `src/tools/inbox.ts` and `src/loop.ts`.",
        "Paste the Claude Code prompt. It adapts field names to `src/schema.ts` and adds tests and the `loop` script without calling the API.",
        "Run `npm run loop -- --limit 1`. When it ends with `done`, run `npm run loop -- --limit 5` and read the cost line.",
        "Open the newest `traces/loop-*.jsonl`: `cache_read_input_tokens` should be above zero from turn 2, and every `save_triage` call should have a matching `tool` event.",
        "Break it twice: `--max-turns 2` must end with `max_turns`, and `--max-tokens 300` must end with `max_tokens` without saving a truncated record.",
        "Run `codex exec review --uncommitted` with the Codex prompt as its instructions, fix what it finds, then ship through your `ship-change` skill.",
      ],
      prompts: [
        {
          label: "Claude Code: wire the loop in",
          text: [
            "Goal: wire the Day 6 agent loop into agent-forge without calling the API.",
            "",
            "Context: src/schema.ts exports the Zod schemas FeedbackItem and TriageResult (Day 4). scripts/gen-feedback.ts writes items to data/inbox/*.jsonl (Day 5). I pasted src/models.ts, src/tools/spec.ts, src/tools/inbox.ts and src/loop.ts from the course.",
            "",
            "Do:",
            "1. Read src/schema.ts. If FeedbackItem calls the text field something other than text, adapt clip() in src/tools/inbox.ts. Do not change the schema.",
            "2. Add tests/tools.test.ts with Vitest, using a temp directory through FORGE_DATA_DIR. Cover: list_feedback pages with next_cursor and skips ids already in triage/results.jsonl, save_triage rejects an unknown id, and runTool returns an actionable error for invalid input.",
            "3. Add \"loop\": \"tsx src/loop.ts\" to package.json scripts and add traces/ to .gitignore, since transcripts contain customer text.",
            "",
            "Constraints: no dependencies beyond @anthropic-ai/sdk and zod, no semicolons, ESM imports with .js extensions.",
            "",
            "Verify: run npm run typecheck and npm test and show me the output. Do not run npm run loop, because it spends money.",
            "",
            "Ask before changing src/schema.ts or any file outside src/, tests/, package.json and .gitignore.",
          ],
        },
        {
          label: "Codex: review the loop",
          text: [
            "Review the uncommitted changes in src/loop.ts, src/tools/ and tests/. Do not edit files.",
            "",
            "Check that: every stop_reason has a branch, no tool runs when stop_reason is max_tokens, tool inputs are validated with Zod before use, every error result names a next step, the SYSTEM string contains nothing that changes per run, all tool results from one turn return in one user message, and costUsd prices cache reads and writes.",
            "",
            "Report findings as a numbered list with file:line and a severity of high, medium or low. Say so explicitly if you find nothing.",
          ],
        },
      ],
      code: [
        { title: "src/models.ts", lang: "ts", file: "d06/models.ts" },
        { title: "src/tools/spec.ts", lang: "ts", file: "d06/spec.ts" },
        { title: "src/tools/inbox.ts", lang: "ts", file: "d06/inbox.ts" },
        { title: "src/loop.ts", lang: "ts", file: "d06/loop.ts" },
      ],
      minimum: "A one-tool loop, with only `save_triage` and the items pasted into the prompt, that ends on `end_turn` and stops at a turn cap.",
      done: "`npm run loop -- --limit 5` saves five schema-valid lines to `data/triage/results.jsonl` and prints a cost line, and its transcript shows cache reads above zero from turn 2.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 45,
      title: "Break the loop on purpose",
      goal: "Learn the transcript signature of four common loop failures so you can diagnose them in any harness.",
      steps: [
        "Build the system text per request with `Now: ${new Date().toISOString()}` at the top, then compare `cache_read_input_tokens` with a clean run.",
        "Make `save_triage` fail every third call with the bare message `failed`, then with a message that names the field and its allowed values. Count retries in each transcript.",
        "Run with `FORGE_MODEL_MAIN=claude-haiku-4-5` and compare cost, cache reads and schema errors against Opus 5.",
        "Write `lab/06-loop-failures.md` with one row per failure: symptom, transcript signature, fix.",
      ],
      done: "`lab/06-loop-failures.md` has four rows, each with a transcript line quoted as its signature.",
    },
  ],
  glossary: [
    ["Agent loop", "Code that calls the model, runs the tools it requests, appends the results and repeats until a stop condition holds."],
    ["Stop reason", "The API's `stop_reason` field, which says why generation ended: `end_turn`, `tool_use`, `max_tokens`, `pause_turn`, `refusal` and a few others."],
    ["Tool result", "The block in a user message that carries a tool's output back to the model, with `is_error: true` for failures."],
    ["Enforced boundary", "A limit the runtime applies whatever the model says: a missing tool, a deny rule, a sandbox or a schema check."],
    ["Cache breakpoint", "A `cache_control` marker. Everything before it can be stored and reread at a fraction of input price while the bytes match exactly."],
    ["OS sandbox", "Kernel-level filesystem and network limits on a process and its children: Seatbelt on macOS, bubblewrap on Linux."],
    ["Approval policy", "Codex's setting for when to ask before acting: `on-request` by default, `never`, or granular rules per category."],
    ["Transcript", "The ordered record of every request, response and tool call in a run. It is both the loop's state and its audit log."],
  ],
  resources: [
    { title: "Handling stop reasons", url: "https://platform.claude.com/docs/en/build-with-claude/handling-stop-reasons", note: "Every `stop_reason` value and what a loop should do with it." },
    { title: "Tool use overview", url: "https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview", note: "The request and result shapes your loop sends and parses." },
    { title: "Prompt caching", url: "https://platform.claude.com/docs/en/build-with-claude/prompt-caching", note: "Breakpoints, minimum prefix sizes, lifetimes and what invalidates a cache." },
    { title: "Claude Code permissions", url: "https://code.claude.com/docs/en/permissions", note: "Rule syntax, evaluation order and the path prefixes that trip people up." },
    { title: "Claude Code sandboxing", url: "https://code.claude.com/docs/en/sandboxing", note: "Filesystem and network isolation, with its stated limits." },
    { title: "Codex config schema", url: "https://github.com/openai/codex/blob/main/codex-rs/core/config.schema.json", note: "The exact keys behind `approval_policy`, `sandbox_mode` and permission profiles." },
    { title: "Context engineering lessons from Manus", url: "https://manus.im/blog/Context-Engineering-for-AI-Agents-Lessons-from-Building-Manus", note: "Why cache hit rate dominates the economics of production loops." },
  ],
  reflect: [
    "Which decision in your loop surprised you by not belonging to the model?",
    "Which rule in your CLAUDE.md or AGENTS.md should become a permission rule, hook or sandbox setting?",
    "What would you need in a transcript to debug a bad triage a week from now?",
  ],
}
