export default {
  day: 2,
  hook: "Before your prompt arrives, each harness has already decided which rules, tools, and skills the model sees. Make those decisions in files you own, and every session starts steered.",
  anchor: "You already run Claude Code and Codex side by side, and yesterday you created `agent-forge` and ran the same experiments in both.",
  plusOne: "Today both harnesses load one rulebook, one skill, and matching permissions from the repo, and you prove it by making them quote the same rules.",
  tldr: [
    "Settings decide what the harness allows. Instructions, skills, and subagents decide what enters context, and when.",
    "Instruction files advise. Permissions, sandboxes, and hooks enforce. Put each rule where it cannot be skipped.",
    "One AGENTS.md, one skill folder, and two thin configs give Claude Code and Codex the same rules, verifiably.",
  ],
  outcomes: [
    "Configure Claude Code permissions and Codex approvals and sandbox, and predict which rule wins",
    "Write one skill both harnesses load, and control when it fires",
    "Delegate research to a subagent through a clear handoff contract",
  ],
  minutes: { learn: 22, practice: 50 },
  map: {
    title: "What reaches the model, and when",
    mermaid: [
      "flowchart TD",
      '  S["Settings and permissions<br/>enforced by the harness"] --> H["Harness"]',
      '  I["AGENTS.md and CLAUDE.md<br/>session start"] --> C["Context window"]',
      '  K["Skill catalog<br/>names and descriptions"] --> C',
      '  P["Prompt, @files, images"] --> C',
      "  H --> C",
      '  C --> M["Model"]',
      '  M -->|"tool call"| H',
      '  M -->|"skill fires"| B["Skill body<br/>loaded on demand"]',
      "  B --> C",
      '  M -->|"delegate"| A["Subagent<br/>its own context"]',
      '  A -->|"final report only"| C',
    ],
    caption: "Settings act outside the window: they decide what the harness allows. Everything else competes for the same context, so each layer should load as late as it can.",
  },
  sections: [
    {
      id: "settings",
      title: "Settings",
      lead: "Settings decide what the harness allows. Know which file wins and which ones wait for trust.",
      bites: [
        ["Profiles", "Claude Code has no named profile switcher: use scope files, `--settings <file>` per session, or `CLAUDE_CONFIG_DIR` for a separate `~/.claude`. Codex profiles are files: `codex -p review` layers `~/.codex/review.config.toml` over your user config. Legacy `[profiles.x]` tables are rejected, so 2025 guides break."],
        ["Projects", "Claude merges JSON scopes, highest first: managed, CLI flags, `.claude/settings.local.json`, `.claude/settings.json`, user. Arrays like `allow` combine. Codex ranks TOML layers: session flags, project `.codex/config.toml`, profile, user. A committed Codex project config beats your profile, and loads only in trusted repos."],
        ["Agents", "`claude --agent reviewer` runs the whole session as that subagent, replacing the default system prompt while CLAUDE.md still loads. Claude's `/agents` wizard was removed in v2.1.198, so edit `.claude/agents/` instead. Codex keeps roles as TOML in `.codex/agents/` and spawns them only when asked."],
        ["Permissions", "Claude checks deny, then ask, then allow, and the first match wins regardless of specificity, so a narrow allow never rescues a broad deny. Codex splits control into two axes: `approval_policy` (`on-request` or `never`) decides when to ask, and `sandbox_mode` decides what the OS allows."],
        ["History", "Claude keeps transcripts under `~/.claude/projects/` for 30 days (`cleanupPeriodDays`), and `/usage` splits cost by skill, subagent, and MCP server. Codex keeps `~/.codex/sessions` and reports tokens, not dollars. Claude's transcript format is internal, so use `/export`, which both harnesses have, instead of parsing."],
        ["Connectors", "Claude.ai connectors appear in `/mcp` only under a subscription login, and a local server with the same URL wins. In Codex, an API key grants no connector or cloud access: those need ChatGPT sign-in. CI runs on API keys, so configure MCP servers explicitly there."],
      ],
      visual: {
        table: {
          head: ["Concern", "Claude Code", "Codex"],
          rows: [
            ["Shared project file", "`.claude/settings.json`", "`.codex/config.toml`, trusted repos only"],
            ["Personal, per project", "`.claude/settings.local.json`, kept out of git", "No local file: use a profile or `-c` flags"],
            ["User defaults", "`~/.claude/settings.json`", "`~/.codex/config.toml`"],
            ["Named variant", "`--settings <file>` or `CLAUDE_CONFIG_DIR`", "`-p NAME` loads `~/.codex/NAME.config.toml`"],
            ["Admin control", "Managed settings win outright", "`requirements.toml` constrains allowed values"],
            ["See what loaded", "`/context`, `/memory`, `/hooks`", "`/debug-config`, `codex debug prompt-input`"],
          ],
        },
        caption: "Same concerns, different mechanics. The two gaps that bite most: Codex has no gitignored local project file, and its project config does nothing until you trust the folder.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Rules that silently do nothing",
          body: "Claude holds committed `allow` rules, `additionalDirectories`, and most `env` until you accept workspace trust, while `deny` and `ask` apply at once. It also ignores `defaultMode` values `auto` and `bypassPermissions` in project files. Codex loads no project config, hooks, rules, or AGENTS.md in an untrusted folder. After a fresh clone, check trust first.",
        },
      ],
      deeper: {
        title: "Two permission models, one policy",
        body: [
          "Claude Code filters each tool call through rules: hooks, then deny, ask, the permission mode, and allow. Its Bash runs outside any sandbox unless you enable `sandbox` in settings, and network access is open by default.",
          "Codex starts from containment. Its OS sandbox (Seatbelt on macOS, bubblewrap on Linux) confines writes to the workspace and blocks network in `workspace-write`. Inside the workspace, `.git`, `.codex`, and `.agents` stay read-only, so commits and skill edits need an approval. Exec-policy files in `.codex/rules/*.rules` add Starlark `prefix_rule` entries that allow, prompt, or forbid command prefixes.",
          "Nearest pairs: Claude `auto` and Codex `--approve-for-me` (an auto-review subagent), `bypassPermissions` and `--yolo`, plan mode and Codex `/plan` with a read-only sandbox.",
          "The practical consequence: the same `npm install` succeeds in Claude and fails in Codex. Treat that as the policy working, and make installs an explicit human step in AGENTS.md.",
        ],
      },
    },
    {
      id: "context",
      title: "Context",
      lead: "Every session carries more than your prompt. Know what rides along and what survives compaction.",
      bites: [
        ["Sessions", "Claude: `/clear` starts fresh, `claude --continue --fork-session` copies history under a new ID, and `/rewind` restores file edits, though not Bash changes. Codex: `codex resume --last` and `codex fork`, with no file checkpoints since `/undo` was removed. Commit before risky experiments in both."],
        ["Threads", "Parallel lines of work on one setup. Claude Projects (beta) spawn cloud sessions that share instructions and memory, and locally `/subtask` forks a subagent. Codex's `codex agents` lists every session on its local daemon. Each thread adds review load, so split only independent work."],
        ["Metadata · environment", "Claude injects cwd, platform, shell, and a git status snapshot at start, so prompt caches never match across worktrees. Bash exports do not persist between Claude commands: write them to `CLAUDE_ENV_FILE` from a SessionStart hook. In Codex, `codex debug prompt-input` prints everything the model receives."],
        ["Tools", "Tool definitions sit in the cached prefix, so adding an MCP server rebuilds the cache. Claude's Glob and Grep are off by default on macOS and Linux, so a hook matching `Grep` never fires. Codex edits through `apply_patch`, which hooks match as `Edit` or `Write`."],
        ["Skills", "Only names and descriptions sit in context until a skill fires. Claude budgets that listing at 1% of the window, Codex at 2% capped at 10,000 tokens. In Claude, a fired skill's body then stays for the session, so keep bodies short."],
        ["Modes", "Since v2.1.283, interactive Claude Code starts in auto mode: a classifier approves actions and blocks force pushes or `curl | bash`. Anthropic measured it missing about 17% of overeager actions. `claude -p` still starts in Manual. Codex's nearest is `--approve-for-me`, where a reviewer model approves."],
        ["Compression", "Claude auto-compacts near the limit, then re-injects the root CLAUDE.md, unscoped rules, auto memory, and up to five recent files. Path-scoped rules return only when a matching file is read. Steer it with `/compact keep the failing test names`. Codex compacts via `/compact` or `model_auto_compact_token_limit`."],
      ],
      visual: {
        table: {
          head: ["You want", "Claude Code", "Codex"],
          rows: [
            ["Ask before most actions", "Manual (`default`)", "`-s read-only` with `-a on-request`"],
            ["Edit freely, ask for the rest", "`acceptEdits`", "`-s workspace-write` with `-a on-request`"],
            ["A model approves for you", "`auto`, the interactive default", "`--approve-for-me`"],
            ["Plan before touching files", "`plan` (Shift+Tab)", "`/plan`"],
            ["No prompts at all", "`bypassPermissions`", "`--yolo`, which also drops the sandbox"],
            ["Headless default", "`claude -p` starts in Manual", "`codex exec` always uses `never`"],
          ],
        },
        caption: "Nearest pairs, not equivalents. Claude's modes change who approves. Codex separates who approves from what the sandbox allows.",
      },
      callouts: [
        {
          type: "example",
          title: "See what each harness loaded",
          body: [
            "```text",
            "Claude Code",
            "  /context                       token use by source: system, tools, memory files, skills",
            "  /memory                        which CLAUDE.md, rules, and AGENTS.md files loaded",
            "Codex",
            "  codex debug prompt-input \"hi\"  the exact input the model receives",
            "  /debug-config                  which config layers are active",
            "```",
          ],
        },
      ],
      deeper: {
        title: "What invalidates the cache mid-session",
        body: [
          "Claude Code caches the prefix of every request. Cheap to change mid-session: permission modes, output styles, invoked skills, and `/rewind`. Expensive: switching models, changing effort (except on Opus 5.5 and Fable 5.1), toggling fast mode, adding or removing MCP servers or plugins, denying a whole tool, and compaction itself.",
          "On a subscription, the main conversation keeps a 1-hour cache TTL within plan limits, and 5 minutes otherwise. So `/compact` is cheap while the cache is warm and costly after a long break, when the whole history bills as fresh input.",
          "Practical rule: pick the model and the MCP servers before a long session, then switch modes freely. For Codex, compare the `usage` totals that `codex exec --json` reports across runs rather than assuming the same rules apply.",
        ],
      },
    },
    {
      id: "processing",
      title: "Processing",
      lead: "Where input lands decides how much it weighs and how long it lasts.",
      bites: [
        ["Text", "CLAUDE.md arrives as a user message after the system prompt, so it is context, not enforcement. `--append-system-prompt` is Claude's system-level channel. Codex injects each AGENTS.md as a user-role message titled with its folder, and `developer_instructions` in config.toml is its nearest system-level channel."],
        ["Threads", "Claude queues messages typed mid-turn into the running turn, with no checkpoint. For a side question, Claude's `/btw` answers with full context, no tools, and nothing added to history. Codex's `/side` (alias `/btw`) opens an ephemeral fork. Both keep tangents out of the main thread."],
        ["Context", "Claude's `@path` attaches a file, `@agent-researcher` forces delegation, and `@server:resource` pulls an MCP resource. Naming a subagent in prose does not guarantee delegation, only the mention does. Codex attaches files with `/mention` and invokes a skill explicitly with `$skill-name`."],
        ["Multimodality", "Claude's Read returns images as visuals and PDFs in slices of up to 20 pages. Codex takes `-i mock.png`, pasted images, and a `view_image` tool. Claude downscales large images, so crop to the region that matters before asking about spacing or small text."],
        ["Attachments", "Paste images into either harness (Ctrl+V in Claude Code). The Claude API's Files API (GA) returns a `file_id` you reuse instead of re-uploading. Every read still costs tokens, and many images can invalidate the prompt cache, so attach only what each step needs."],
        ["Real-time interactions", "Stream instead of waiting: `claude -p --output-format stream-json --verbose --include-partial-messages`, or `codex exec --json` for JSONL events like `turn.completed`. A wrapper can then show progress and stop a runaway run. To push input into a live session, Claude has channels and Codex has `codex queue`."],
      ],
      visual: {
        table: {
          head: ["Channel", "Claude Code", "Codex"],
          rows: [
            ["Project rules", "CLAUDE.md, first line `@AGENTS.md`", "AGENTS.md chain from repo root to cwd"],
            ["System-level text", "`--append-system-prompt`", "`developer_instructions`"],
            ["Files", "`@path`", "`/mention`"],
            ["Images", "Ctrl+V, Read, PDF pages", "`-i`, paste, `view_image`"],
            ["Side question", "`/btw`", "`/side` or `/btw`"],
            ["Explicit skill", "`/skill-name`", "`$skill-name`"],
          ],
        },
        caption: "Rules belong in files that are re-read from disk, not in chat, where the next compaction summarizes them away.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "`@AGENTS.md` is plain text to Codex",
          body: "Codex never expands `@` imports. If you list CLAUDE.md in `project_doc_fallback_filenames`, Codex reads the literal line `@AGENTS.md`. Keep AGENTS.md as the real file and let CLAUDE.md import it. Also delete any old SessionStart hook that prints AGENTS.md, or Claude gets two copies.",
        },
      ],
      deeper: {
        title: "Why rules in files outlast rules in chat",
        body: [
          "Instruction following is learned, not enforced. Models are trained to weight system text above user text, but CLAUDE.md and AGENTS.md both arrive as user-role messages, and so does everything you paste into the conversation.",
          "Survival matters more than wording. A rule stated mid-conversation is summarized at the next compaction and may not survive it. A rule in the root CLAUDE.md, or in the AGENTS.md it imports, is re-injected from disk after every compaction.",
          "Recency still helps. In a long session, restate the one rule that matters in the prompt that needs it, instead of adding emphasis to the file.",
          "Anything that must hold regardless of what the model attends to belongs in a permission rule, a sandbox setting, or a hook.",
        ],
      },
    },
    {
      id: "skills",
      title: "Skills",
      lead: "A skill is a procedure loaded only when needed. Write it once and both harnesses can run it.",
      bites: [
        ["Structure", "A folder with `SKILL.md`: YAML frontmatter starting on line 1, a Markdown body under 500 lines, and optional `scripts/`, `references/`, and `assets/`. Codex parses only `name`, `description`, and `metadata.short-description` and ignores the rest, so shared skills should stick to open-spec fields."],
        ["Selection", "Models pick a skill by matching its description, so lead with the use case in the user's words. Claude caps description plus `when_to_use` at 1,536 characters. `disable-model-invocation: true` makes a Claude skill manual-only, but Codex ignores it and may still fire the skill."],
        ["Scope", "Claude loads enterprise, personal (`~/.claude/skills/`), and project (`.claude/skills/`) skills. Codex loads `.agents/skills/` from repo root to cwd, plus `~/.agents/skills/`. Claude does not read `.agents/skills/`, so keep the real folder there and symlink it into `.claude/skills/`."],
        ["Graphs", "SKILL.md has no dependency field. In Claude, compose by linking files from the body, a subagent's `skills:` list, or `context: fork` for a fresh subagent. Codex ignores `context: fork`, so a shared skill should name its next step in prose."],
        ["Scripts", "Bundled scripts run, and only their output enters context, so a 300-line validator costs only what it prints. Claude expands `${CLAUDE_SKILL_DIR}` in script paths. Codex documents no such variable, so shared skills should use repo-relative paths. Codex's sandbox also keeps `.agents/` read-only."],
        ["Dynamic resources", "In Claude, a body line like !`gh pr diff` runs before the model reads the skill and inlines the output, and a non-zero exit aborts the invocation. Codex documents no command injection, so shared skills should also tell the model which command to run."],
        ["Generation", "Draft skills from a run that worked: Anthropic's skill-creator, Codex's bundled `skill-creator` system skill, or Claude's `/run-skill-generator`. Then measure triggering and output quality separately, for example with `claude plugin eval`, because a skill that fires can still produce the wrong result."],
      ],
      visual: {
        mermaid: [
          "flowchart LR",
          '  C["Catalog<br/>name and description<br/>every session"] -->|"request matches"| B["SKILL.md body<br/>loaded once"]',
          '  U["/explain-diff in Claude<br/>$explain-diff in Codex"] --> B',
          '  B -->|"body points to it"| R["references/<br/>read on demand"]',
          '  B -->|"body runs it"| S["scripts/<br/>only output enters context"]',
        ],
        caption: "Cost grows only as the skill proves relevant. That makes the description the most important line in the file.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "A manual-only skill that fires anyway",
          body: "`disable-model-invocation: true` works only in Claude. Codex reads the description and may invoke a deploy skill on its own. For any skill with side effects, write 'Only run when the user explicitly asks' into the description itself, which both harnesses read.",
        },
      ],
      deeper: {
        title: "Instruction file, skill, or MCP server",
        body: [
          "- **AGENTS.md**: rules true for every task. Every session pays for them.",
          "- **Skill**: a procedure needed sometimes, with its scripts and references. Its catalog entry costs about 100 tokens until it fires.",
          "- **MCP server**: a capability the shell cannot reach, such as a SaaS API behind OAuth, or access you want governed and audited.",
          "A useful rule of thumb from the MCP-versus-CLI debate: prefer a CLI plus a skill when a mature CLI exists and the shell is sandboxed (`git`, `gh`). Use MCP for services without a CLI, remote hosts, and clients with no shell. Past about ten tools, reach for tool search or code mode.",
          "Agent Skills became an open standard in December 2025. Anthropic's application to the Agentic AI Foundation, still in vote, claims 46 supporting products, including Codex and Gemini CLI.",
        ],
      },
    },
    {
      id: "tools",
      title: "Tools",
      lead: "Every tool costs context and invites calls. Load few, describe them well, and make failures readable.",
      bites: [
        ["Discovery", "Claude Code defers MCP tool schemas behind `ToolSearch` by default: names load, schemas arrive when searched. Anthropic measured tool search cutting about 77K tokens to 8.7K. Set `alwaysLoad: true` for a tool used every turn. Codex trims its surface with per-server `enabled_tools` and `disabled_tools` lists."],
        ["Schemas", "The model sees a tool's name, description, and input schema, nothing else, so `.describe()` on each Zod field is documentation it actually reads. For structured final answers, Claude takes `--json-schema` inline and Codex takes `--output-schema FILE`, which needs `additionalProperties: false` and every property required."],
        ["Results", "Return what the next decision needs, not the raw payload. Claude Code warns at 10,000 tokens of MCP output, caps at 25,000 (`MAX_MCP_OUTPUT_TOKENS`), and saves overflow to a file it reads on demand. In both, paginate, filter, and return names rather than opaque IDs."],
        ["Hints", "MCP annotations such as `readOnlyHint` and `destructiveHint` are metadata, not enforcement. Claude uses `readOnlyHint` to run calls in parallel. Codex sets approval per tool instead, with `approval_mode = \"prompt\"` under `[mcp_servers.NAME.tools.TOOL]`. A malicious server can label a delete tool read-only."],
        ["Recovery", "Return failures as readable results (`isError: true`) instead of throwing, so the model can correct itself. Exit code 1 is normal for `grep`, `diff`, and `test`. Claude's `PostToolUseFailure` hook can react. Codex has no failure hook event, so handle failures in the tool itself."],
        ["Code mode", "Expose tools as a typed API the model writes code against, and intermediate data never enters context: Anthropic cut a workflow from 150,000 tokens to 2,000. The API calls it programmatic tool calling. In either CLI, ask for a script that prints only the summary."],
        ["Bash", "Claude matches Bash rules with `*`, so `Bash(npm run *)` allows every npm script. Codex runs commands in its sandbox and applies `prefix_rule` entries from `.codex/rules/*.rules`. Patterns miss rephrased commands: containment needs a sandbox, which Codex enables by default and Claude does not."],
      ],
      visual: {
        mermaid: [
          "sequenceDiagram",
          "  participant M as Model",
          "  participant H as Harness",
          "  participant T as Tool",
          "  M->>H: tool call with input",
          "  H->>H: hooks, then deny, ask, mode, allow",
          "  H->>T: run it, sandboxed if enabled",
          "  T-->>H: error with a readable message",
          "  H-->>M: result marked isError",
          "  M->>H: corrected call",
          "  H->>T: run it again",
          "  T-->>H: result trimmed to what matters",
          "  H-->>M: result",
        ],
        caption: "The harness, not the model, runs every check before a tool executes. A readable error turns a failed call into a corrected one. An empty or cryptic result invites a blind retry.",
      },
      callouts: [
        {
          type: "example",
          title: "An error the model can act on",
          body: [
            "```json",
            "{",
            "  \"content\": [{ \"type\": \"text\", \"text\": \"No feedback item fb_0142. Ids in data/inbox/sample.jsonl run fb_0001 to fb_0050. Call list_feedback to search by text.\" }],",
            "  \"isError\": true",
            "}",
            "```",
            "It says what failed, what exists, and which tool to call next.",
          ],
        },
      ],
      deeper: {
        title: "Code mode, with the numbers",
        body: [
          "Cloudflare's Code Mode (September 2025) and Anthropic's Code execution with MCP (November 2025) share one finding: models write code against a typed API more reliably than they emit long chains of tool calls. Anthropic's version presents MCP tools as files such as `./servers/google-drive/getDocument.ts`, loads only the definitions a script needs, and filters results inside the sandbox. One workflow fell from 150,000 tokens to 2,000.",
          "Anthropic's advanced tool use results (November 2025): tool search cut 77K tokens to 8.7K and raised Opus 4.5 accuracy from 79.5% to 88.1%. Programmatic calling cut 43,588 tokens to 27,297. Tool use examples raised complex-parameter accuracy from 72% to 90%.",
          "The contrarian read: tool search removes much of MCP's token cost, and a mature CLI plus a skill often beats a server. Measure on your own tools before rebuilding around either.",
        ],
      },
    },
    {
      id: "subagents",
      title: "Subagents",
      lead: "A subagent buys a clean context for a side task. You pay in tokens and in the handoff.",
      bites: [
        ["Mechanics", "Claude's `Agent` tool (formerly `Task`) spawns a worker with its own context that returns only a final report. In interactive sessions subagents run in the background, nest three deep, and cap at 20 at once. Codex spawns children with `spawn_agent`, but only when asked."],
        ["Settings", "A Claude subagent is Markdown in `.claude/agents/` with required `name` and `description`, plus optional `tools`, `model`, `permissionMode`, `skills`, `memory`, and `isolation: worktree`. A Codex role is TOML in `.codex/agents/` with `description`, `sandbox_mode`, and `developer_instructions`. In both, the description routes work."],
        ["State", "Claude keeps every subagent transcript, so you can resume one by name, and `memory: project` gives it a persistent `MEMORY.md`. Explore and Plan are one-shot. A `maxTurns` cap returns partial output you can continue. Codex children stay addressable through `/subagents` and tools like `followup_task`."],
        ["Handoffs", "Down, a subagent gets only the delegation prompt. Up, you get its final report, which Claude scans for injected instructions and labels as carrying no user authority. So the delegation prompt is a contract: objective, output format, sources, boundaries, and what to do when blocked."],
        ["Shared context", "A regular Claude subagent gets its prompt, the delegation, CLAUDE.md, git status, and preloaded skills, but not your history. Forks share history and the prompt cache. In both harnesses subagents share the filesystem, so parallel writers need Claude's `isolation: worktree` or separate files."],
        ["When to delegate", "Delegate work whose context you do not want in the main thread: broad searches, log trawls, web research. Anthropic puts the cost at 3 to 10 times the tokens. Split by the context each task needs, not by role, and keep writes in one thread."],
      ],
      visual: {
        mermaid: [
          "sequenceDiagram",
          "  participant Y as You",
          "  participant P as Main session",
          "  participant R as researcher subagent",
          "  Y->>P: research triage failure modes, sources required",
          "  P->>R: delegation prompt with objective, scope, output format",
          "  R->>R: search, fetch, read in its own context",
          "  R-->>P: final report with sources",
          "  P-->>Y: summary, and the report saved to research/",
        ],
        caption: "The subagent's search results never enter the main context. Only the report does, so the report format is the whole interface.",
      },
      callouts: [
        {
          type: "example",
          title: "A delegation prompt that works",
          body: [
            "```text",
            "Objective: find three documented failure modes of LLM feedback triage.",
            "Scope: the web plus research/ in this repo. Read-only.",
            "Sources: primary only (papers, vendor engineering posts, docs).",
            "Output: the report format in your instructions, under 700 words.",
            "Done when: each failure mode has two sources or is marked unverified.",
            "If blocked: stop and report what you tried.",
            "```",
          ],
        },
      ],
      deeper: {
        title: "One agent or many",
        body: [
          "Anthropic's research system beat single-agent Opus 4 by 90.2% on an internal eval while using about 15 times the tokens of chat, and token spend explained 80% of the variance on BrowseComp.",
          "Two findings temper that. Cognition's Don't Build Multi-Agents (June 2025) argued that parallel agents make conflicting implicit decisions, and its April 2026 follow-up settled on single-threaded writes, with helper agents contributing reads and reviews. Tran and Kiela (Stanford, April 2026) found single agents matched or beat multi-agent systems on multi-hop reasoning at equal thinking budgets, which suggests part of the reported gain is extra compute.",
          "The working consensus: parallelize reading, serialize writing. Today's researcher subagent follows it. It reads widely and writes nothing.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "settings",
      q: "Your `.claude/settings.json` allows `Bash(git push origin feature-*)` and denies `Bash(git push *)`. What happens when Claude runs `git push origin feature-login`?",
      options: [
        "It is denied, because deny is checked first",
        "It is allowed, because the narrower rule wins",
        "Claude asks you, because the two rules conflict",
        "It is allowed only while auto mode is on",
      ],
      answer: 0,
      why: "Claude evaluates deny, then ask, then allow, and the first match wins regardless of specificity. Deny rules hold in every mode, including bypassPermissions. To allow feature pushes, narrow the deny rule instead of adding a more specific allow.",
    },
    {
      id: "q2",
      section: "context",
      q: "Late in a long Claude Code session, the agent stops following `.claude/rules/api.md`, which has a `paths:` glob. Compaction just ran. What is the most likely cause?",
      options: [
        "Path-scoped rules return only when a matching file is read",
        "Compaction deletes every rule until you restart the session",
        "The rule file went over a 200-line limit and was dropped",
        "Auto mode filters out rules that carry a `paths:` field",
      ],
      answer: 0,
      why: "After compaction Claude re-injects the root CLAUDE.md, unscoped rules, auto memory, and recent files. Path-scoped rules and nested CLAUDE.md files come back only when a matching file is read again. Nothing drops rules at 200 lines, and modes do not filter rules.",
    },
    {
      id: "q3",
      section: "processing",
      q: "You paste a full-page screenshot and ask Claude to match the header's 4px spacing. The result is visibly off. What is the best next step?",
      options: [
        "Crop to the header and attach only that region",
        "Paste a higher-resolution export instead",
        "Switch to plan mode so it studies the image first",
        "Ask it to count the pixels in the full screenshot",
      ],
      answer: 0,
      why: "Claude downscales large images before the model sees them, so fine detail in a full-page shot is lost. A cropped region keeps its detail. A higher-resolution export is downscaled too, and plan mode changes permissions, not perception.",
    },
    {
      id: "q4",
      section: "skills",
      q: "A shared deploy skill in `.agents/skills/` has `disable-model-invocation: true`. In Codex it ran without being asked. Why?",
      options: [
        "Codex ignores the key, so the description must say manual only",
        "Codex reads invocation flags only from `metadata.short-description`",
        "The `.claude/skills/` symlink exposed the skill to Codex's catalog",
        "Codex needs `user-invocable: false` instead",
      ],
      answer: 0,
      why: "Codex parses only name, description, and `metadata.short-description`, and can invoke a skill implicitly from its description. A skill with side effects must say 'only run when the user explicitly asks' in the description. Codex reads `.agents/skills/`, not the Claude symlink.",
    },
    {
      id: "q5",
      section: "tools",
      q: "An MCP search tool returns about 40,000 tokens of JSON per call, and the agent starts losing track of the task. What is the best fix?",
      options: [
        "Return fewer ranked results plus a next-page cursor",
        "Raise `MAX_MCP_OUTPUT_TOKENS` so the output stays inline",
        "Mark the tool `readOnlyHint` so its calls run in parallel",
        "Move to a model with a larger context window instead",
      ],
      answer: 0,
      why: "Results should carry what the next decision needs. Ranking, pagination, and semantic names cut tokens and keep attention on the task. Raising the cap adds noise, `readOnlyHint` only enables parallel calls, and larger windows still degrade with length.",
    },
    {
      id: "q6",
      section: "subagents",
      q: "Early in a session you told Claude to skip vendor blogs. You then delegate web research, and the subagent's report cites three vendor blogs. Why?",
      options: [
        "A subagent sees the delegation prompt, not your history",
        "Subagents always run on a small model that drops constraints",
        "The rule was compacted away before the subagent started",
        "WebFetch results override instructions from the user",
      ],
      answer: 0,
      why: "A regular subagent starts with its own prompt, the delegation, CLAUDE.md, and preloaded skills, but none of your conversation. Restate constraints in the delegation or put them in the agent file. Subagent models come from the agent file or the parent, not a fixed small model.",
    },
    {
      id: "q7",
      q: "On a new laptop, Codex ignores the committed `.codex/config.toml` and the repo's AGENTS.md, while Claude Code behaves normally. What is the most likely cause?",
      options: [
        "The project is not trusted in Codex yet",
        "Codex reads config only from `~/.codex/config.toml`",
        "CLAUDE.md hides AGENTS.md from Codex",
        "Codex needs a profile file named after the repo",
      ],
      answer: 0,
      why: "Codex loads project config, hooks, rules, and (since 0.150.0) project AGENTS.md only for trusted projects, recorded per absolute path in `~/.codex/config.toml`. A new clone starts untrusted. Codex never reads CLAUDE.md unless you list it as a fallback filename.",
    },
    {
      id: "q8",
      q: "You want Claude Code never to read `.env`, even in auto mode. Where does that rule belong?",
      options: [
        "A `Read(./.env)` deny rule in `.claude/settings.json`",
        "A clear line in CLAUDE.md that says never to read .env",
        "An ask rule, since auto mode always escalates those",
        "A `.gitignore` entry for the file",
      ],
      answer: 0,
      why: "Deny rules apply in every mode, including auto and bypassPermissions, and a Read deny also blocks Edit and Write on that path. CLAUDE.md is advisory context that the model may not weigh. A `.gitignore` entry does not stop reads.",
    },
    {
      id: "q9",
      q: "Which setup gives both harnesses a single copy of the `explain-diff` skill to maintain?",
      options: [
        "One folder in `.agents/skills/`, linked from `.claude/skills/`",
        "Keep it in `.claude/skills/`, which Codex also scans at startup",
        "Copy it into both folders and let CI diff the two copies",
        "Inline it in AGENTS.md so both harnesses always load it",
      ],
      answer: 0,
      why: "Codex reads `.agents/skills/` from repo root to cwd, and Claude reads `.claude/skills/` and follows symlinked skill folders. One real folder plus a link means one file to review. Inlining in AGENTS.md loads the whole procedure every session and defeats progressive disclosure.",
    },
    {
      id: "q10",
      q: "A scheduled `claude -p` job refuses to edit files that the same prompt edited without trouble in an interactive session. What changed?",
      options: [
        "`-p` starts in Manual mode, not auto mode",
        "Headless runs ignore `.claude/settings.json` entirely",
        "`claude -p` cannot use the Edit tool in any mode",
        "The prompt cache expired",
      ],
      answer: 0,
      why: "Auto mode is the interactive starting mode as of v2.1.283, while `-p` and the Agent SDK start in Manual, so edits without an allow rule are refused. Without `--bare`, headless runs still load settings, hooks, and CLAUDE.md. Codex's `codex exec` similarly always runs with approval `never`.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "See what each harness actually loads",
      goal: "Find out what enters context before you type anything, in both harnesses.",
      steps: [
        "In any repo with an instruction file, start Claude Code and run `/context`. Note the tokens for memory files, skills, and MCP tools.",
        "Run `/memory` and list which CLAUDE.md, rules, or AGENTS.md files loaded.",
        "In the same repo, run `codex debug prompt-input \"hi\" | less` and search for `AGENTS.md instructions for`.",
        "Write one line in your notes: the largest layer in each harness, and whether it could load later.",
      ],
      done: "You can name the largest context layer in each harness, with a token count from `/context` for Claude.",
    },
    {
      id: "build",
      level: "build",
      minutes: 60,
      title: "Wire both harnesses to one source of truth",
      goal: "Make AGENTS.md the rulebook both harnesses load, give each harness explicit permissions, share one skill, add a research subagent, and prove both harnesses read the same rules.",
      steps: [
        "On a branch (`git switch -c feat/harness-wiring`), create `AGENTS.md` and `CLAUDE.md` from the starters below, then run the first prompt in Claude Code to fit them to your repo.",
        "Add `.claude/settings.json` and `.codex/config.toml`. Start `codex` in the repo, trust the folder when asked, and run `/debug-config` to confirm the project layer is active.",
        "Create the shared skill: `mkdir -p .agents/skills/explain-diff .claude/skills`, save `SKILL.md`, then `ln -s ../../.agents/skills/explain-diff .claude/skills/explain-diff`. Confirm it shows in Claude's `/` menu and in Codex's `/skills`.",
        "Add `.claude/agents/researcher.md` and try it: `@agent-researcher What are two documented failure modes of LLM-based feedback triage? Sources required.`",
        "Run the parity prompt headless in both harnesses: `claude -p \"<prompt>\"` and `codex exec --sandbox read-only \"<prompt>\"`. Paste both answers into `lab/02-harness-parity.md` and mark every difference.",
        "Commit and merge: `git add -A && git commit -m \"Wire Claude Code and Codex to AGENTS.md\" && git push -u origin HEAD && gh pr create --fill && gh pr merge --squash --delete-branch`.",
      ],
      prompts: [
        {
          label: "Claude Code: fit the rulebook to the repo",
          text: [
            "Goal: make AGENTS.md the single rulebook for every agent harness in this repo, with CLAUDE.md holding only Claude-specific notes.",
            "",
            "Context: I pasted starters into AGENTS.md and CLAUDE.md. The repo has package.json, tsconfig.json, README.md, and lab/ from Day 1. Codex reads AGENTS.md directly and does not expand @ imports. Claude reads CLAUDE.md, which imports AGENTS.md.",
            "",
            "Do:",
            "1. Check every command, path, and script named in AGENTS.md against the repo. Mark anything that does not exist yet with the day it arrives, for example (Day 4).",
            "2. Move anything tool-neutral from CLAUDE.md into AGENTS.md. CLAUDE.md must keep @AGENTS.md as its first line.",
            "3. Keep AGENTS.md under 120 lines. State each rule once, with its reason when the reason is not obvious. No CRITICAL, MUST, or all caps.",
            "",
            "Verify: run npm run typecheck and wc -l AGENTS.md CLAUDE.md, and show both outputs.",
            "Ask before: creating any other file, adding dependencies, or changing what a rule means.",
          ],
        },
        {
          label: "Claude Code and Codex: parity check (run the same text in both)",
          text: [
            "Read the instruction files this harness loaded for this repo. Do not edit any file. Then answer:",
            "1. Quote, verbatim, the three rules that most constrain how you change code here.",
            "2. Which command must pass before you report a task as done?",
            "3. Which skill would you use to explain a diff, and how do I invoke it in this harness?",
            "4. Name every instruction file you loaded.",
          ],
        },
      ],
      code: [
        { title: "AGENTS.md", lang: "md", file: "d02/AGENTS.md" },
        { title: "CLAUDE.md", lang: "md", file: "d02/CLAUDE.md" },
        { title: ".claude/settings.json", lang: "json", file: "d02/settings.json" },
        { title: ".codex/config.toml", lang: "toml", file: "d02/config.toml" },
        { title: ".agents/skills/explain-diff/SKILL.md", lang: "md", file: "d02/explain-diff/SKILL.md" },
        { title: ".claude/agents/researcher.md", lang: "md", file: "d02/researcher.md" },
      ],
      minimum: "AGENTS.md plus the CLAUDE.md import, with both harnesses quoting the same rules.",
      done: "`lab/02-harness-parity.md` shows Claude Code and Codex quoting the same AGENTS.md rules and naming `explain-diff`. `/explain-diff` runs in Claude and `$explain-diff` in Codex, and the merged PR holds AGENTS.md, CLAUDE.md, both configs, the skill and its symlink, and `researcher.md`.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 45,
      title: "Give Codex the same researcher",
      goal: "Build the Codex twin of your research subagent and compare both on one question, so you know which harness gets research by default.",
      steps: [
        "Save the role below as `.codex/agents/researcher.toml`. Codex keeps `.codex/` read-only inside its sandbox, so create the file yourself.",
        "Start `codex --search` and ask explicitly: `Spawn the researcher agent to answer: which open standards exist for agent instruction files, and who governs each? Return its report.` Codex does not delegate unless asked.",
        "Ask Claude Code the same question with `@agent-researcher`.",
        "Compare the two in `lab/02-harness-parity.md`: sources cited, primary versus secondary, claims you could not verify, and wall-clock time. Check `/usage` in Claude and `/status` in Codex.",
      ],
      code: [{ title: ".codex/agents/researcher.toml", lang: "toml", file: "d02/researcher.toml" }],
      done: "Both reports sit side by side in the lab file with a verdict: which researcher you will use by default, and why.",
    },
  ],
  glossary: [
    ["Permission mode", "Claude Code's session-wide approval behavior: Manual (`default`), `acceptEdits`, `plan`, `auto`, `dontAsk`, or `bypassPermissions`."],
    ["Approval policy", "Codex's rule for when to ask: `on-request` lets the model escalate, and `never` sends failures back to the model."],
    ["Sandbox mode", "Codex's OS-enforced limits: `read-only`, `workspace-write` (no network by default), or `danger-full-access`."],
    ["Workspace trust", "A per-folder decision that gates project config. Codex loads no project config, hooks, rules, or AGENTS.md until you trust the folder."],
    ["Auto mode", "Claude Code's classifier-based mode that approves routine actions and blocks risky ones. The interactive default since v2.1.283."],
    ["Progressive disclosure", "Loading a skill in stages: name and description always, the body when it fires, and files only when the body uses them."],
    ["Tool search", "Deferring tool schemas until the model searches for them, so unused tools cost almost no context."],
    ["Compaction", "Summarizing a long session to free context. Claude re-injects root instructions afterward, but not path-scoped rules."],
    ["Subagent", "A worker with its own context window that returns only a final report to the session that spawned it."],
    ["Code mode", "Exposing tools as a code API the model scripts against, so intermediate results stay out of context."],
  ],
  resources: [
    { title: "Claude Code settings", url: "https://code.claude.com/docs/en/settings", note: "Scopes, precedence, and which keys wait for workspace trust." },
    { title: "Claude Code permission modes", url: "https://code.claude.com/docs/en/permission-modes", note: "Manual, the auto mode classifier, and protected paths." },
    { title: "Claude Code skills", url: "https://code.claude.com/docs/en/skills", note: "The full frontmatter table and the loading lifecycle." },
    { title: "Claude Code subagents", url: "https://code.claude.com/docs/en/sub-agents", note: "Fields, model resolution, forks, and resuming." },
    { title: "Codex config reference", url: "https://developers.openai.com/codex/config-reference", note: "Every config.toml key. Validate edits with `codex exec --strict-config`." },
    { title: "Codex AGENTS.md guide", url: "https://developers.openai.com/codex/guides/agents-md", note: "Discovery order, overrides, and the 32 KiB budget." },
    { title: "Agent Skills specification", url: "https://agentskills.io/specification", note: "The open format both harnesses read, and the fields that travel." },
    { title: "Effective context engineering for AI agents", url: "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents", note: "Anthropic's framing of just-in-time context, compaction, and subagents." },
  ],
  reflect: [
    "Which rule in your current CLAUDE.md or AGENTS.md should really be a permission, a sandbox setting, or a hook?",
    "Which prompt do you repeat often enough to earn a skill, and what would its description say?",
    "Where would a subagent's clean context have saved your main session this week?",
  ],
}
