export default {
  day: 11,
  hook: "When an agent can build three versions of a feature before lunch, the scarce resource becomes deciding which change deserves to exist and what it does to the system.",
  anchor: "You already frame problems, write PRDs, and ship React apps while Claude Code and Codex do most of the typing.",
  plusOne: "Today you treat implementation as cheap and spend your judgment on outcomes, assumptions, and the system diff before any agent builds.",
  tldr: [
    "Output is what ships. An outcome is the behavior change it causes. Agents multiply output, so defining outcomes becomes your main lever.",
    "Human attention is the new bottleneck. Every variant, diff, and review spends it, so point it at decisions, not at reading noise.",
    "Predict the system diff before building, then prototype in loops on synthetic inputs to test assumptions while they are cheap.",
  ],
  outcomes: [
    "Write an outcome, success metric, and non-goals that an agent can build against",
    "Predict a change's system diff across behavior, data, architecture, and operations",
    "Run looped prototypes across both harnesses and pick a direction with evidence",
  ],
  minutes: { learn: 20, practice: 75 },
  map: {
    title: "Where judgment sits when building is cheap",
    mermaid: [
      "flowchart LR",
      '  O["Outcome<br/>behavior change and metric"] --> A["Assumptions<br/>ledger with checks"]',
      '  A --> SD["Expected system diff"]',
      '  SD --> P["Looped prototypes<br/>synthetic inputs"]',
      '  P -->|"evidence"| J["Judgment<br/>pick, cut, or reframe"]',
      '  J -->|"reframe"| O',
      '  J --> B["Brief an agent can build from"]',
    ],
    caption: "Agents make the prototype box almost free. The boxes around it decide whether the cheap build was worth running, and they are where your time now goes.",
  },
  sections: [
    {
      id: "shift",
      title: "Shift",
      lead: "Agents collapse the cost of building. Value moves to choosing what to build and noticing what changed.",
      bites: [
        ["Outcome over output", "Josh Seiden defines an outcome as a change in human behavior that drives business results. Output is the feature that ships. Impact, such as revenue, lags behind both. Agents make output nearly free, so a brief that names only output buys a fast, polished miss."],
        ["Product engineer vs. product manager", "PostHog describes product engineers who own features end to end: they talk to users, make design calls, and shape the roadmap. The PM keeps cross-team discovery and prioritization. With agents doing implementation, one person can hold both loops and skip a lossy handoff."],
        ["Attention as the bottleneck", "Attention is scarce twice. Yours: Herbert Simon's wealth of information creates a poverty of attention, and every agent diff draws on it. The model's: context has an attention budget that degrades with length. Spend both budgets on decisions, not on reading noise."],
        ["Deciding is the new constraint", "Andrew Ng argued in 2025 that the bottleneck has moved to deciding what to build, and described a team proposing one PM for every half engineer. Treat the ratio as anecdote. The direction holds: generation scales with compute, judgment does not."],
      ],
      visual: {
        table: {
          head: ["Level", "What it is", "Forge Inbox example", "Can you steer it this week?"],
          rows: [
            ["Output", "What ships", "Approve, edit, and reject buttons", "Yes, and agents make it cheap"],
            ["Outcome", "A behavior change", "Reviewers decide proposals without opening raw files", "Yes, through product changes"],
            ["Impact", "The business result", "Feedback reaches the roadmap faster", "No, it lags and has many causes"],
          ],
        },
        caption: "Steer by the middle row. Output is too easy to produce and impact moves too slowly to guide this week's work.",
      },
      deeper: {
        title: "The contrarian case for keeping a separate PM",
        body: [
          "Merging the product and engineering loops removes a handoff, but it also removes a check. A separate PM often catches solution bias: the builder favors the approach that is fastest to build. Agents strengthen that bias, because the cheapest thing to build is whatever the agent proposes first.",
          "You can keep the check without the headcount:",
          "- Write the outcome and non-goals before you see any prototype.",
          "- Ask a fresh-context agent to argue against your chosen direction, citing the brief.",
          "- Name whose behavior changes. If you cannot, you are describing output, and no amount of prototyping will fix that.",
          "The PM role that survives is the one that owns cross-team priorities, which no single builder sees.",
        ],
      },
    },
    {
      id: "ownership",
      title: "Ownership",
      lead: "Delegating the work never delegates the accountability. Four lenses make ownership concrete before the first prompt.",
      bites: [
        ["Scope", "Write what is in, what is out, and the non-goals an agent is most likely to add anyway. Agents expand scope by default, because each extra feature looks helpful locally. A non-goal list is the cheapest guardrail you will ever write."],
        ["User impact", "Name who behaves differently and where you will see it. 'Reviewers stop opening raw feedback' shows up in a decision log. 'A better triage experience' shows up nowhere. If a change has no observable behavior, neither you nor the agent can verify it."],
        ["Business value", "Say why now and what it displaces. For the Inbox: every unreviewed proposal is feedback that never reaches the roadmap. Value framing settles later tradeoffs, such as whether to cut inline editing or keyboard shortcuts when the timeline slips."],
        ["Technical consequences", "Blast radius, operability, and cost: what changes, what breaks when it fails, who gets paged, and what it costs per run. Agents rarely volunteer these, because the prompt asked for a feature, not for its consequences."],
        ["Accountability", "A Claude Code routine commits as you and acts through your connectors. A Codex cloud task returns a diff that you apply or open as a PR. Either way, what merges is yours, including every side effect nobody reviewed."],
      ],
      callouts: [
        {
          type: "example",
          title: "An ownership block for the Inbox PR",
          body: [
            "```text",
            "Owner: @you        Outcome: reviewers clear the queue in one sitting",
            "Scope: apps/inbox only. Non-goals: GitHub writes, clusters, auth",
            "Blast radius: new writer to data/decisions.jsonl. Triage untouched",
            "Rollback: stop the Inbox processes. Decisions are append-only",
            "Residual risk: two tabs deciding one proposal (server returns 409)",
            "```",
          ],
        },
        {
          type: "pitfall",
          title: "Green CI does not move ownership",
          body: "If an agent wrote it and CI passed, the outcome is still yours. CI checks what you told it to check. A cost spike or a scope change that no check covers is your gap to close, which Day 14 turns into a quality gate.",
        },
      ],
    },
    {
      id: "judgment",
      title: "Judgment",
      lead: "Agents act on whatever decisions they infer. Judgment means making those decisions explicit before the agent guesses.",
      bites: [
        ["Assumptions", "Cognition's rule: actions carry implicit decisions, and conflicting decisions carry bad results. Keep an assumption ledger with a status per line: confirmed, unverified with a check, or open with an owner. Unverified lines are what your prototypes test first."],
        ["Tradeoffs", "Write the option you chose, the one you declined, and why. 'Keyboard speed over mobile, because review happens at a desk' lets an agent settle the next ten micro-decisions consistently. An unstated tradeoff gets re-decided in every file, differently each time."],
        ["Taste", "Taste can be partly operationalized. Anthropic's app harness graded design quality, originality, craft, and functionality against hard thresholds, and a separate evaluator forced revisions. Output improved measurably. Write your taste as a rubric with examples, then let a reviewer agent apply it."],
        ["Edge cases", "Name the cases where the happy path lies: an empty queue, a proposal already decided in another tab, a 4,000-word feedback item, a duplicate that points at a closed issue. Agents build the happy path and stop. Named edge cases become tomorrow's acceptance criteria."],
        ["Uncertainty", "Label each claim as known, believed, or guessed, and attach a cheap check to every belief. Size evidence to the claim: one prototype session proves feasibility, not reliability. For agent behavior, prefer pass^k (every trial succeeds) over pass@k, which flatters."],
        ["Consequences", "Follow the change one hop past the feature. A faster Inbox means more approvals, which means more issues, which raises duplicate risk downstream. Second-order effects are where agents are weakest, because nothing in the prompt points at them."],
      ],
      visual: {
        md: [
          "```text",
          "A1  One reviewer works the queue at a time        open        owner: you, ask the team",
          "A2  Most edits change severity, labels, or title  unverified  check: count edits in prototypes",
          "A3  Triage only appends, latest line per id wins  confirmed   loadResults, src/tools/inbox.ts",
          "A5  30 seconds per decision is realistic          unverified  check: time five decisions",
          "```",
        ],
        caption: "An assumption ledger from the Inbox brief. Every unverified line needs a check and every open line needs an owner.",
      },
      callouts: [
        {
          type: "pro",
          title: "Ask for assumptions before code",
          body: "Before a build prompt, send: `List the assumptions you would make to implement this, grouped as safe, risky, or blocking. Do not write code.` MAST lists failing to ask for clarification as a common multi-agent failure. This prompt forces the question before the code exists.",
        },
      ],
      deeper: {
        title: "Taste, written as a rubric",
        body: [
          "Anthropic's long-running app harness split generation from evaluation. The evaluator scored each sprint against criteria with hard thresholds and failed anything below them, which forced revisions that a self-grading generator skipped.",
          "The same move works for product taste. The Inbox rubric in your brief has four lines:",
          "- Density: feedback, proposal, and decision controls fit on one screen.",
          "- Speed: every decision has a keyboard path.",
          "- Honesty: low-confidence proposals look different from confident ones.",
          "- Restraint: nothing appears that the brief does not ask for.",
          "Give the rubric and screenshots to a fresh-context reviewer and ask for pass or fail per line, with the evidence it saw. The taste stays yours. Enforcing it becomes cheap and repeatable, and disagreements point at rubric lines you wrote too loosely.",
        ],
      },
    },
    {
      id: "systems-thinking",
      title: "Systems Thinking",
      lead: "A code diff lists edited lines. The system also changes in places nobody edited.",
      bites: [
        ["Architecture", "Name the components, contracts, and trust boundaries before and after. The Inbox adds a UI, a small API, and a new writer to `data/`. That new writer is an architectural fact, even though no existing file changes."],
        ["Dependencies", "Dependencies set both risk and parallelism. Independent parts can go to separate agents at once, while one shared contract serializes everyone behind it. Anthropic's parallel compiler agents stalled on one monolithic build until an oracle let them split the work by file."],
        ["Operational impact", "Operations are architecture you pay for later: processes, ports, env vars, retries, cost per run, and the off switch. Durable retries are at-least-once, so side effects need idempotency keys. If you cannot say how to turn it off, it is not ready."],
        ["System diffs", "This course's working definition: a change stated as deltas to behavior, user experience, data, architecture, complexity, and operations. It builds on blast-radius analysis, change impact analysis, and ADRs. Write the expected diff before building, then compare it with the actual on Day 14."],
      ],
      visual: {
        table: {
          head: ["Change", "Visible in the code diff?", "Where the system diff shows it"],
          rows: [
            ["New React route", "Yes", "User experience: a new screen"],
            ["First writer to `data/decisions.jsonl`", "Partly", "Data: a new append-only record and its consumers"],
            ["GitHub token scope widened to write", "No", "Architecture: a new permission to the outside world"],
            ["Feature flag default flipped", "One line", "Behavior: every user sees the change at once"],
            ["New npm dependency", "Lockfile noise", "Architecture and supply chain"],
          ],
        },
        caption: "The largest system changes often hide behind the smallest code diffs. A token scope or a flag default can outweigh a thousand lines of UI.",
      },
      callouts: [
        {
          type: "example",
          title: "Expected system diff, Inbox v1",
          body: [
            "```text",
            "Behavior      decisions become records instead of hand edits",
            "UX            + local web UI at localhost:5173",
            "Data          reads results and feedback, appends data/decisions.jsonl",
            "Architecture  + apps/inbox UI, + apps/inbox/server.ts, no GitHub access",
            "Complexity    one app, one API, one shared contract file",
            "Operations    two local processes, no secrets, off = stop both",
            "```",
          ],
        },
      ],
      deeper: {
        title: "Why a system diff, and why only six lines",
        body: [
          "No canonical definition of 'system diff' exists. The nearest established ideas are blast radius (the components and consumers exposed to a change), change impact analysis, architecture decision records, and C4 diagrams. The course term packages them for one situation: agents produce large diffs quickly, and reviewer attention is the bottleneck.",
          "A system diff compresses review into effects. It tells a reviewer where to look, and comparing the expected version with the actual one catches scope creep that line-by-line review misses.",
          "The contrarian risk is ceremony. Keep it to the six dimensions, write only the lines that changed, and link each claim to evidence. A system diff longer than the PR description has stopped doing its job.",
        ],
      },
    },
    {
      id: "leverage",
      title: "Leverage",
      lead: "Use cheap generation to buy evidence, not features. Every variant still spends review attention.",
      bites: [
        ["AI-assisted exploration", "Send read-only agents to map before you decide: a Claude Code Explore subagent, or `codex exec --sandbox read-only`, can summarize `src/schema.ts`, the data files, and recent traces. Exploration output is a map for you, not a plan for the agent to execute."],
        ["Looped prototyping", "Generate, run, evaluate, revise. Anthropic's solo agent built a game maker in 20 minutes for $9, and it ignored input. A generator plus a Playwright evaluator took 6 hours and $200, and it worked. The evaluation step bought the working result."],
        ["Generative exploration", "Build divergent variants in parallel, each in its own worktree: `claude -w` in Claude Code, `codex --worktree` in Codex. Diverge on the one question that matters most, keep everything else equal, and compare on the same inputs."],
        ["Synthetic inputs", "Generated data that exercises a prototype: messy feedback from your Day 5 generator, edge-case proposals, random property inputs. It tests behavior and breakage. LLM personas skew optimistic and shallow, so they generate hypotheses and never replace a real reviewer."],
        ["The variant tax", "Cheap generation is not cheap judgment. Anthropic's evaluator harness cost about 20 times the solo run, and every variant is one more thing to review. Cap prototypes at three, time-box them, and delete them after the decision."],
      ],
      visual: {
        mermaid: [
          "flowchart LR",
          '  S["Synthetic inputs<br/>npm run gen:feedback"] --> V1["Variant A<br/>Claude Code worktree"]',
          '  S --> V2["Variant B<br/>Codex worktree"]',
          '  S --> V3["Variant C<br/>either harness"]',
          '  V1 --> E["Evaluate<br/>rubric, screenshots, timings"]',
          '  V2 --> E',
          '  V3 --> E',
          '  E -->|"revise"| V1',
          '  E --> D["Decision record<br/>keep one, delete the rest"]',
        ],
        caption: "Same inputs, same rubric, different bets. The decision record is the only artifact that survives.",
      },
      callouts: [
        {
          type: "pitfall",
          title: "Synthetic users as validation",
          body: "NN/g found synthetic user answers too shallow and sycophantic to trust. Research on LLM personas shows them skewing optimistic. Use synthetic users to find breakage and sharpen questions, then validate direction with a real reviewer, even if that reviewer is you with a timer.",
        },
      ],
      deeper: {
        title: "When synthetic inputs are valid evidence",
        body: [
          "Validity depends on what the input stands in for. Park and colleagues built agents from two-hour interviews, and those agents matched people's survey answers 85% as well as the people matched themselves two weeks later. Grounding carried the result. Personas written from a prompt showed the optimism and sameness that NN/g and others report.",
          "For the Inbox, split the questions:",
          "- Valid: does the layout survive a 4,000-word item, a hundred proposals, missing fields, or a duplicate chain? These are properties of the data.",
          "- Weak: do reviewers want one card at a time or a dense table? That is preference, and a persona will agree with whatever you built.",
          "Tomorrow's spec turns the valid questions into acceptance criteria. The weak ones stay as assumptions until Day 15 produces real decision data.",
        ],
      },
    },
  ],
  quiz: [
    {
      id: "q1",
      section: "shift",
      q: "Which statement is an outcome, rather than an output, for the Forge Inbox?",
      options: [
        "Ship approve, edit, and reject buttons with keyboard shortcuts",
        "Reviewers decide most proposals without opening raw files",
        "Fewer customer complaints go unaddressed on next year's roadmap",
        "Inbox v1 is merged with every acceptance test passing",
      ],
      answer: 1,
      why: "An outcome is a behavior change you can observe and steer within weeks. Buttons and a merged PR are output. Next year's complaint count is closer to impact: it lags and has many causes, so it cannot steer this week's work.",
    },
    {
      id: "q2",
      section: "ownership",
      q: "A Codex cloud task produced a diff that passed CI. You applied and merged it, and it quietly doubled Triage's API cost. Who owns the regression?",
      options: [
        "Codex, because the task ran in its cloud environment",
        "You, as the person who delegated and merged it",
        "The CI workflow, because it should have caught the cost",
        "Nobody, until a postmortem assigns an owner to it",
      ],
      answer: 1,
      why: "Delegation moves work, not accountability. Whoever delegates and merges owns the outcome and its side effects. CI only checks what you configured, so a missing cost check is your gap, which Day 14 turns into a gate.",
    },
    {
      id: "q3",
      section: "judgment",
      q: "You tell an agent to 'make reasonable assumptions' about how editing a proposal should work. What is the main risk?",
      options: [
        "The agent refuses to proceed and asks too many questions",
        "Its assumptions stay hidden and get re-decided per file",
        "Its context fills with assumptions and truncates the output",
        "It defaults to the most expensive implementation available",
      ],
      answer: 1,
      why: "Permission to assume hides decisions instead of surfacing them, so different files end up with different guesses. Ask for an assumption ledger with each line marked confirmed, unverified with a check, or open. Too many questions is the rarer failure.",
    },
    {
      id: "q4",
      section: "systems-thinking",
      q: "Which change most needs a system diff, even though its code diff is a single line?",
      options: [
        "Renaming a React component used on one screen",
        "Widening the GitHub token scope from read to write",
        "Adding a unit test for the decision reducer function",
        "Reformatting server.ts with the project's formatter",
      ],
      answer: 1,
      why: "A scope change alters what the system can do to the outside world, and no reviewer sees that in one edited line. Renames, tests, and formatting stay inside their files. The largest system diffs often hide behind the smallest code diffs.",
    },
    {
      id: "q5",
      section: "leverage",
      q: "You have one afternoon to explore the Inbox layout. Which plan uses AI leverage best?",
      options: [
        "Build eight variants in parallel and keep the best-looking one",
        "Three variants on the same synthetic data and one rubric",
        "One polished variant, then ask synthetic personas to rate it",
        "Skip prototypes and write a detailed spec for the agent first",
      ],
      answer: 1,
      why: "Divergent variants on shared inputs and a shared rubric turn generation into comparable evidence. Eight variants cost more review attention than they return. Synthetic personas rate optimistically, so their scores cannot choose a direction.",
    },
    {
      id: "q6",
      q: "Your brief says 'Build an Inbox for reviewing Triage proposals.' Claude Code returns a polished app with clusters, dark mode, and GitHub publishing. What went wrong first?",
      options: [
        "The model was more capable than the task required",
        "No outcome or non-goals bounded the work",
        "Claude Code should have started in plan mode",
        "The agent had no access to a design system",
      ],
      answer: 1,
      why: "Agents expand scope because each extra feature looks helpful locally. Without an outcome and a non-goal list, nothing said clusters and GitHub writes were out. Plan mode would have produced a careful plan for the same unbounded scope.",
    },
    {
      id: "q7",
      q: "Two prototypes do equally well on synthetic inputs. One needs a new npm dependency and a background worker. The other needs neither. What should decide?",
      options: [
        "Prefer the smaller system diff when the evidence ties",
        "Pick the one the agent built faster, as a sign of simplicity",
        "Pick whichever one the synthetic personas rated higher",
        "Pick the one with more features, since building was cheap",
      ],
      answer: 0,
      why: "When outcome evidence ties, fewer new components, dependencies, and processes mean less to run, review, and roll back. Build speed reflects the agent, not the design. Persona ratings skew optimistic, and extra features are a cost.",
    },
    {
      id: "q8",
      q: "What is the most valid use of synthetic inputs for the Inbox prototypes?",
      options: [
        "Validating that real reviewers will adopt the Inbox",
        "Stress-testing layout and throughput with messy data",
        "Replacing the success metric with persona satisfaction",
        "Choosing between prototypes by majority persona vote",
      ],
      answer: 1,
      why: "Synthetic inputs test properties of the data and the interface: long text, volume, missing fields, duplicate chains. They cannot show whether people want the product, because LLM personas skew optimistic and shallow. Use them for breakage and hypotheses.",
    },
    {
      id: "q9",
      q: "Which statement about attention in AI-assisted product work is accurate?",
      options: [
        "More parallel agents reduce the total attention a feature needs",
        "Human review time and model recall both degrade with volume",
        "Attention limits models, but humans can skim agent output safely",
        "Long context windows remove the attention constraint for models",
      ],
      answer: 1,
      why: "Reviewers have finite attention for diffs and variants, and models recall less as context grows. More parallel agents usually raise review load. A larger window raises the ceiling but does not stop context rot.",
    },
  ],
  tasks: [
    {
      id: "quick",
      level: "quick",
      minutes: 10,
      title: "Turn an output into an outcome in both harnesses",
      goal: "Practice separating output from outcome, and see how each harness frames the same feature.",
      steps: [
        "Pick a feature you shipped recently and write its output in one line.",
        "Run `claude -p \"Rewrite this feature as an outcome: whose behavior changes, how we would observe it within two weeks, and one guardrail metric. Three lines only. Feature: <your line>\"`.",
        "Run the same prompt through `codex exec --sandbox read-only \"...\"` and compare the two answers.",
        "Keep the stronger outcome and note in one line what the weaker answer missed.",
      ],
      done: "You have one feature written as output and as outcome, with a metric you could check within two weeks.",
    },
    {
      id: "build",
      level: "build",
      minutes: 75,
      title: "Frame the Inbox product",
      goal: "Write the one-page brief for the Forge Inbox, then run three throwaway prototypes across both harnesses and record which direction wins and why.",
      steps: [
        "Make synthetic inputs: `npm run gen:feedback`, then `npm run triage`, until `data/triage/results.jsonl` holds 30 or more proposals. Add three edge cases by hand: a very long item, a low-confidence proposal, and a duplicate.",
        "Copy the brief template to `docs/product/inbox-brief.md`. Fill Outcome, User, Metrics, and Non-goals yourself before any agent reads it.",
        "Run the interrogation prompt in Claude Code. Record every assumption and question it raises in the brief's ledger and Open questions.",
        "Create one worktree per variant: `claude -w inbox-proto-a` and `claude -w inbox-proto-c` for Claude Code, and `codex --worktree` for variant B. Worktrees are fresh checkouts, so copy `data/` in if it is gitignored. Codex's `workspace-write` sandbox has no network by default, so run `npm install` in its worktree yourself.",
        "Paste the variant prompt into each session with its bet filled in. Then paste two screenshots per variant into Claude Code with the brief's Taste rubric and ask for pass or fail per line, with evidence.",
        "Time five decisions per variant and fill `docs/product/inbox-prototypes.md`. Update the brief's ledger and expected system diff, commit only the two docs, and remove the losing worktrees.",
      ],
      prompts: [
        {
          label: "Claude Code: interrogate the brief",
          text: [
            "Read docs/product/inbox-brief.md, src/schema.ts, AGENTS.md, and the first 20 lines of data/triage/results.jsonl.",
            "Goal: find what this brief leaves an implementer to guess. Do not write code or edit files.",
            "",
            "Return three lists:",
            "1. Assumptions the brief does not state, each marked safe, risky, or blocking.",
            "2. Contradictions between the brief, the schema, and AGENTS.md.",
            "3. At most five questions whose answers would change the design.",
            "",
            "Cite the line or schema field behind each item. If the brief is already clear on a point, say so rather than inventing a concern.",
          ],
        },
        {
          label: "Claude Code or Codex: one prototype variant",
          text: [
            "Build a throwaway prototype of the Forge Inbox under prototypes/inbox/ on this branch. It will never merge.",
            "Read docs/product/inbox-brief.md first. This variant's bet: <A: dense table, keyboard first | B: one card at a time, raw feedback beside it | C: split list and detail, inline edit>.",
            "",
            "Constraints:",
            "- Vite and React, loading data/triage/results.jsonl and data/inbox/*.jsonl through a small read-only loader. No API server and no GitHub calls.",
            "- Approve, edit, and reject change local state only. Never write to data/.",
            "- Dependencies limited to vite, @vitejs/plugin-react, react, and react-dom.",
            "- Stop once the decision flow works on the real data, including the three edge cases in the brief.",
            "",
            "Verify with a production build (npx vite build) and a typecheck, then give me the exact command to start the dev server so I can review it myself.",
            "Ask before adding any other dependency or touching files outside prototypes/.",
          ],
        },
      ],
      code: [
        { title: "docs/product/inbox-brief.md", lang: "md", file: "d11/inbox-brief.md" },
        { title: "docs/product/inbox-prototypes.md", lang: "md", file: "d11/inbox-prototypes.md" },
      ],
      minimum: "The brief with outcome, metric, assumptions, non-goals, and expected system diff, plus one prototype evaluated against its rubric.",
      done: "`docs/product/inbox-brief.md` and `docs/product/inbox-prototypes.md` are committed, and the decision record names the winning variant with screenshots, five timed decisions per variant, and the assumptions each variant confirmed or broke.",
    },
    {
      id: "stretch",
      level: "stretch",
      minutes: 45,
      title: "Best-of-N against deliberate variants",
      goal: "Compare Codex cloud's built-in best-of-N with your three deliberate variants, and learn which kind of exploration each one buys.",
      steps: [
        "Push the repo so the cloud can clone it. Create a Codex cloud environment for `agent-forge` (per OpenAI's docs this lives in ChatGPT's Codex settings) with Node 22 and `npm ci` as the setup script.",
        "Run `codex cloud exec --env ENV_ID --attempts 3 \"<variant B prompt>\"`. Attempts are capped at 4.",
        "Inspect the attempts with `codex cloud status TASK_ID` and `codex cloud diff TASK_ID`, then apply the best one in a scratch worktree with `codex cloud apply TASK_ID --attempt N`.",
        "Claude Code has no built-in best-of-N. Its nearest equivalent is running one prompt in several worktrees or cloud sessions yourself, so note the setup cost of each route.",
        "Add a section to `docs/product/inbox-prototypes.md`: how different were the three attempts, compared with your three deliberate bets?",
      ],
      done: "The prototypes record has a best-of-N section with one sentence on when sampling one bet beats diverging on several.",
    },
  ],
  glossary: [
    ["Outcome", "A change in human behavior that drives a business result. Observable and steerable within weeks, unlike output or impact."],
    ["Output", "What ships: features, screens, endpoints. Agents make it cheap, which makes it a weak measure of progress."],
    ["Product engineer", "An engineer who owns a feature end to end, including user contact, design decisions, and roadmap input."],
    ["Assumption ledger", "The beliefs a plan rests on, each marked confirmed, unverified with a check, or open with an owner."],
    ["Non-goal", "Work deliberately excluded and written down, so agents do not add it because it looks helpful."],
    ["Blast radius", "The components, users, and data exposed when a change fails."],
    ["System diff", "This course's term: a change stated as deltas to behavior, user experience, data, architecture, complexity, and operations."],
    ["Looped prototyping", "Generate, run, evaluate against a real check, then revise. The evaluation step separates it from generating once."],
    ["Synthetic input", "Generated data that exercises a prototype or test. Strong evidence about breakage, weak evidence about preference."],
  ],
  resources: [
    { title: "Seiden: user outcomes versus business outcomes", url: "https://medium.com/@jseiden/whats-the-difference-between-user-outcomes-and-business-outcomes-588952071552", note: "The output, outcome, and impact distinction from the author of Outcomes Over Output." },
    { title: "PostHog: what is a product engineer", url: "https://posthog.com/product-engineer/what-is-a-product-engineer", note: "A concrete description of the role from a company organized around it." },
    { title: "Harness design for long-running apps", url: "https://www.anthropic.com/engineering/harness-design-long-running-apps", note: "Generator and evaluator loops, graded taste, and the $9 versus $200 comparison." },
    { title: "Cognition: Don't Build Multi-Agents", url: "https://cognition.com/blog/dont-build-multi-agents", note: "Why implicit decisions inside actions collide, the argument behind assumption ledgers." },
    { title: "NN/g: synthetic users", url: "https://www.nngroup.com/articles/synthetic-users/", note: "Where synthetic research participants fail, with examples." },
    { title: "Measuring AI agent autonomy in practice", url: "https://www.anthropic.com/research/measuring-agent-autonomy", note: "Field data on how experienced users shift from approving actions to monitoring them." },
    { title: "OpenAI Codex repository and releases", url: "https://github.com/openai/codex", note: "Source and release notes for `codex cloud`, `--worktree`, and sandbox defaults." },
  ],
  reflect: [
    "Which feature you shipped last quarter was output without an outcome, and what should the outcome have been?",
    "When agents work for you, where does your attention actually go: reading diffs, fixing drift, or deciding?",
    "Which assumption in the Inbox brief would hurt most if it turned out wrong, and what is its check?",
  ],
}
